export const stages = [
 {id:'cell',name:'Célula',subtitle:'O contexto do material genético',tag:'ESCALA CELULAR',description:'Explore uma célula nucleada em corte. O núcleo abriga a maior parte do DNA; as mitocôndrias também possuem DNA próprio.',parts:[['membrane','Membrana celular','Delimita a célula e controla trocas com o meio.'],['nucleus','Núcleo','Compartimento que abriga o DNA nuclear.'],['mitochondria','Mitocôndrias','Organelas com genoma próprio, distinto do DNA nuclear.']],takeaway:'Nem todo DNA da célula está no núcleo.',question:'Qual estrutura também possui DNA próprio?',options:['Mitocôndria','Membrana celular','Citoplasma como um todo'],answer:0,why:'Além do DNA nuclear, há DNA mitocondrial.',source:'https://www.genome.gov/genetics-glossary/Mitochondrial-DNA'},
 {id:'nucleus',name:'Núcleo',subtitle:'DNA organizado em cromatina',tag:'ORGANIZAÇÃO NUCLEAR',description:'Na intérfase, o DNA está associado a proteínas e organizado em cromatina. O modelo destaca o envoltório, os poros e o nucléolo.',parts:[['envelope','Envoltório nuclear','Duas membranas separam o núcleo do citoplasma.'],['chromatin','Cromatina','Complexo de DNA e proteínas; sua organização muda ao longo do ciclo celular.'],['nucleolus','Nucléolo','Região envolvida na produção de RNA ribossômico e na montagem de subunidades ribossômicas.'],['pores','Poros nucleares','Controlam o transporte entre núcleo e citoplasma.']],takeaway:'Cromatina é DNA associado a proteínas.',question:'O que constitui a cromatina?',options:['Apenas RNA','DNA associado a proteínas','Somente proteínas'],answer:1,why:'A associação com proteínas permite organizar e regular o acesso ao DNA.',source:'https://www.genome.gov/genetics-glossary/Chromatin'},
 {id:'chromosome',name:'Cromossomo',subtitle:'Duplicado e condensado',tag:'ANTES DA SEPARAÇÃO',description:'Aqui você vê um cromossomo duplicado: duas cromátides-irmãs unidas na região do centrômero. Essa forma condensada não é a aparência do DNA durante toda a vida celular.',parts:[['sisterA','Cromátide-irmã 1','Contém uma molécula de DNA de dupla fita associada a proteínas.'],['sisterB','Cromátide-irmã 2','É a outra cópia formada pela replicação do DNA.'],['centromere','Centrômero','Região em que se organiza o cinetócoro, importante para a segregação cromossômica.'],['telomeres','Telômeros','Regiões nas extremidades de cada cromátide que protegem as pontas do DNA linear.']],takeaway:'Duas cromátides-irmãs ainda formam um cromossomo duplicado.',question:'Antes da separação, esta estrutura representa:',options:['Dois cromossomos homólogos','Um cromossomo duplicado','Uma molécula de RNA'],answer:1,why:'As cromátides-irmãs permanecem unidas até sua separação.',source:'https://www.genome.gov/genetics-glossary/Chromatid'},
 {id:'nucleosome',name:'Nucleossomo',subtitle:'A primeira unidade de organização',tag:'DNA + HISTONAS',description:'O DNA se enrola em um núcleo de proteínas histonas. Observe o segmento entre unidades: o DNA de ligação. A linha representa a dupla hélice de forma simplificada.',parts:[['histones','Histonas','O núcleo do nucleossomo contém oito histonas.'],['wrapped','DNA enrolado','O DNA dá aproximadamente 1,7 volta ao redor do núcleo de histonas.'],['linker','DNA de ligação','Conecta nucleossomos vizinhos.']],takeaway:'O DNA é organizado, não substituído, pelas histonas.',question:'O DNA se enrola ao redor de:',options:['Histonas','Ribossomos','Lipídios'],answer:0,why:'As histonas formam o núcleo proteico do nucleossomo.',source:'https://www.genome.gov/genetics-glossary/Nucleosome'},
 {id:'dna',name:'DNA',subtitle:'Duas fitas. Bases complementares.',tag:'ESTRUTURA MOLECULAR',description:'As bases ficam voltadas para o interior; o esqueleto açúcar-fosfato fica do lado de fora. As fitas têm sentidos opostos: são antiparalelas.',parts:[['backbone','Açúcar-fosfato','Forma o esqueleto externo de cada fita de DNA.'],['at','Adenina · Timina','A pareia com T por duas ligações de hidrogênio.'],['gc','Guanina · Citosina','G pareia com C por três ligações de hidrogênio.']],takeaway:'A–T e G–C: a sequência está nas bases.',question:'Qual é o pareamento correto no DNA?',options:['A–G e T–C','A–T e G–C','A–C e T–G'],answer:1,why:'Adenina pareia com timina; guanina, com citosina.',source:'https://www.genome.gov/genetics-glossary/Deoxyribonucleic-Acid-DNA'}
];
export const palette={teal:'#7bc9bc',copper:'#dfac85',violet:'#afa3da',ivory:'#e1e9e5'};
export function helixPoint(t,phase=0,radius=1){return [radius*Math.cos(t+phase),t/(Math.PI*2)*2.45,-radius*Math.sin(t+phase)]}
export function complementary(base){return ({A:'T',T:'A',G:'C',C:'G'})[base]}
