const input=(id,label,min,max,step=.1)=>({id,label,min,max,step});
const weight=input('weight','Peso (kg)',20,350),height=input('height','Altura (cm)',100,230);
export const calculators=[
{id:'bmi',name:'Índice de massa corporal',area:'Clínica Médica',summary:'Relação entre peso e altura em adultos.',inputs:[weight,height],unit:'kg/m²',formula:'Peso ÷ (altura em metros)²',source:'https://www.cdc.gov/growth-chart-training/hcp/using-bmi/calculating-bmi.html',note:'Não usar isoladamente para avaliar composição corporal. Categorias pediátricas e gestação exigem outras referências.',calc:v=>v.weight/(v.height/100)**2},
{id:'bsa',name:'Superfície corporal · Mosteller',area:'Clínica Médica',summary:'Estimativa de superfície corporal em adultos.',inputs:[weight,height],unit:'m²',formula:'√(altura em cm × peso em kg ÷ 3.600)',source:'https://pubmed.ncbi.nlm.nih.gov/3657876/',note:'Estimativa antropométrica. Não calcula dose de medicamentos.',calc:v=>Math.sqrt(v.height*v.weight/3600)},
{id:'egfr',name:'TFG estimada · CKD-EPI 2021',area:'Nefrologia',summary:'Creatinina, idade e sexo da equação; sem coeficiente racial.',inputs:[input('age','Idade (anos)',18,120,1),input('creatinine','Creatinina (mg/dL)',.1,30,.01),{id:'female',label:'Sexo usado na equação',options:[['1','Feminino'],['0','Masculino']]}],unit:'mL/min/1,73 m²',formula:'142 × min(Cr/κ,1)^α × max(Cr/κ,1)^−1,200 × 0,9938^idade × 1,012 (feminino). κ: 0,7/0,9; α: −0,241/−0,302 (feminino/masculino).',source:'https://www.niddk.nih.gov/research-funding/research-programs/kidney-clinical-research-epidemiology/laboratory/glomerular-filtration-rate-equations/adults',note:'Adultos com creatinina estável. Não usar em lesão renal aguda ou gestação. Um resultado isolado não diagnostica doença renal crônica.',calc:v=>{const f=v.female===1,k=f?.7:.9,a=f?-.241:-.302;return 142*Math.min(v.creatinine/k,1)**a*Math.max(v.creatinine/k,1)**-1.2*.9938**v.age*(f?1.012:1)}},
{id:'gap',name:'Ânion gap',area:'Nefrologia',summary:'Diferença entre os cátions e ânions medidos, sem potássio.',inputs:[input('na','Sódio (mEq/L)',80,200),input('cl','Cloreto (mEq/L)',50,170),input('hco','Bicarbonato (mEq/L)',1,60)],unit:'mEq/L',formula:'Na − (Cl + HCO₃)',source:'https://www.merckmanuals.com/professional/nephrology/acid-base-regulation-and-disorders/acid-base-disorders',note:'Sem correção pela albumina. Compare com o intervalo de referência do laboratório; hipoalbuminemia pode mascarar aumento.',calc:v=>v.na-v.cl-v.hco},
{id:'winter',name:'Compensação de Winter',area:'Nefrologia',summary:'PaCO₂ esperada na acidose metabólica.',inputs:[input('hco','Bicarbonato (mEq/L)',1,30)],unit:'mmHg',formula:'PaCO₂ esperada = 1,5 × HCO₃ + 8 ± 2',source:'https://www.merckmanuals.com/professional/nephrology/acid-base-regulation-and-disorders/acid-base-disorders',note:'Aplicar apenas na acidose metabólica e comparar com a PaCO₂ medida. Não indica parâmetros de ventilação.',calc:v=>1.5*v.hco+8,range:2},

// --- Ampliação (24/09/2026): fórmulas clássicas. `detail(v)` devolve linhas extras de leitura.
{id:'holliday',name:'Hidratação de manutenção · Holliday-Segar',area:'Pediatria',summary:'Volume de manutenção por peso (regra 4-2-1).',inputs:[input('kg','Peso (kg)',.5,150,.1)],unit:'mL/h',formula:'100 mL/kg/dia até 10 kg + 50 mL/kg/dia de 10 a 20 kg + 20 mL/kg/dia acima de 20 kg; ÷ 24 h (equivale a 4-2-1 mL/kg/h).',source:'https://pubmed.ncbi.nlm.nih.gov/13431307/',note:'Estimativa de manutenção, não de reposição de perdas ou déficit. A AAP (2018) recomenda solução isotônica com glicose para manutenção de 28 dias a 18 anos. Ajuste para insuficiência cardíaca, renal, SIADH e outras condições.',calc:v=>(Math.min(v.kg,10)*100+Math.max(0,Math.min(v.kg,20)-10)*50+Math.max(0,v.kg-20)*20)/24,detail:v=>[`${Math.round(Math.min(v.kg,10)*100+Math.max(0,Math.min(v.kg,20)-10)*50+Math.max(0,v.kg-20)*20)} mL/dia`]},
{id:'infusao',name:'Taxa de infusão · drogas vasoativas',area:'Emergência',summary:'Converte dose em mcg/kg/min para mL/h na bomba.',inputs:[input('dose','Dose (mcg/kg/min)',.01,50,.01),input('kg','Peso (kg)',1,300,.1),input('conc','Concentração da solução (mcg/mL)',1,5000,.1)],unit:'mL/h',formula:'mL/h = dose (mcg/kg/min) × peso (kg) × 60 ÷ concentração (mcg/mL). Concentração = quantidade do fármaco (mcg) ÷ volume final (mL).',source:'https://www.ncbi.nlm.nih.gov/books/NBK551684/',note:'Exemplos de concentração: noradrenalina 4 mg em 250 mL = 16 mcg/mL; dobutamina 250 mg em 250 mL = 1.000 mcg/mL. Diluições variam por instituição: confira o protocolo local e dupla-checagem de enfermagem.',calc:v=>v.dose*v.kg*60/v.conc},
{id:'dose-kg',name:'Dose por peso',area:'Pediatria',summary:'Dose em mg e volume a administrar a partir de mg/kg.',inputs:[input('mgkg','Dose prescrita (mg/kg/dose)',.01,100,.01),input('kg','Peso (kg)',.5,150,.1),input('conc','Concentração (mg/mL)',.1,1000,.1)],unit:'mg por dose',formula:'mg = mg/kg × peso; mL = mg ÷ concentração (mg/mL).',source:'https://www.ncbi.nlm.nih.gov/books/NBK513349/',note:'Sempre confira a dose máxima por dose e por dia na bula e respeite a dose de adulto como teto.',calc:v=>v.mgkg*v.kg,detail:v=>[`${(v.mgkg*v.kg/v.conc).toLocaleString('pt-BR',{maximumFractionDigits:2})} mL por dose`]},
{id:'ca-corr',name:'Cálcio corrigido pela albumina',area:'Clínica Médica',summary:'Cálcio total ajustado para hipoalbuminemia.',inputs:[input('ca','Cálcio total (mg/dL)',2,20,.1),input('alb','Albumina (g/dL)',.5,6,.1)],unit:'mg/dL',formula:'Ca corrigido = Ca medido + 0,8 × (4 − albumina)',source:'https://www.ncbi.nlm.nih.gov/books/NBK430912/',note:'Estimativa imprecisa, sobretudo em doença crítica e renal; prefira o cálcio iônico quando disponível.',calc:v=>v.ca+.8*(4-v.alb)},
{id:'na-glic',name:'Sódio corrigido pela glicemia',area:'Endocrinologia',summary:'Sódio esperado após normalizar a glicose (hiperglicemia).',inputs:[input('na','Sódio (mEq/L)',100,180),input('glic','Glicose (mg/dL)',100,3000,1)],unit:'mEq/L',formula:'Katz: Na + 1,6 × (glicose − 100) ÷ 100. Hillier: fator 2,4.',source:'https://pubmed.ncbi.nlm.nih.gov/10225241/',note:'Útil na cetoacidose e no estado hiperosmolar para interpretar a natremia real.',calc:v=>v.na+1.6*(v.glic-100)/100,detail:v=>[`Hillier (2,4): ${(v.na+2.4*(v.glic-100)/100).toLocaleString('pt-BR',{maximumFractionDigits:1})} mEq/L`]},
{id:'osm',name:'Osmolalidade sérica calculada',area:'Nefrologia',summary:'Com sódio, glicose e ureia (mg/dL).',inputs:[input('na','Sódio (mEq/L)',100,200),input('glic','Glicose (mg/dL)',10,3000,1),input('ureia','Ureia (mg/dL)',1,500,1)],unit:'mOsm/kg',formula:'2 × Na + glicose ÷ 18 + ureia ÷ 6 (ureia ÷ 6 ≈ BUN ÷ 2,8).',source:'https://www.ncbi.nlm.nih.gov/books/NBK567764/',note:'Gap osmolar = osmolalidade medida − calculada; gap elevado sugere álcoois tóxicos, entre outras causas.',calc:v=>2*v.na+v.glic/18+v.ureia/6},
{id:'agua-livre',name:'Déficit de água livre',area:'Nefrologia',summary:'Água a repor na hipernatremia.',inputs:[input('na','Sódio (mEq/L)',141,200),input('kg','Peso (kg)',1,300,.1),{id:'fator',label:'Água corporal total',options:[['0.6','Homem adulto (0,6)'],['0.5','Mulher adulta ou homem idoso (0,5)'],['0.45','Mulher idosa (0,45)'],['0.6','Criança (0,6)']]}],unit:'L',formula:'Fator × peso × (Na ÷ 140 − 1)',source:'https://www.ncbi.nlm.nih.gov/books/NBK441960/',note:'Não inclui perdas em curso. Na hipernatremia crônica, reduza o sódio no máximo cerca de 10 mEq/L em 24 h.',calc:v=>v.fator*v.kg*(v.na/140-1)},
{id:'qtc',name:'QT corrigido (QTc)',area:'Cardiologia',summary:'Bazett e Fridericia a partir do QT e da frequência.',inputs:[input('qt','QT medido (ms)',200,700,1),input('fc','Frequência cardíaca (bpm)',30,220,1)],unit:'ms (Bazett)',formula:'Bazett: QT ÷ √RR; Fridericia: QT ÷ ∛RR; RR = 60 ÷ FC (s).',source:'https://www.ncbi.nlm.nih.gov/books/NBK551542/',note:'Bazett superestima com FC alta; Fridericia é preferível em taquicardia. QTc >500 ms aumenta o risco de torsades.',calc:v=>v.qt/Math.sqrt(60/v.fc),detail:v=>[`Fridericia: ${Math.round(v.qt/Math.cbrt(60/v.fc))} ms`]},
{id:'pam',name:'Pressão arterial média',area:'Emergência',summary:'Estimativa a partir das pressões sistólica e diastólica.',inputs:[input('pas','PA sistólica (mmHg)',40,300,1),input('pad','PA diastólica (mmHg)',20,200,1)],unit:'mmHg',formula:'PAM = (PAS + 2 × PAD) ÷ 3',source:'https://www.ncbi.nlm.nih.gov/books/NBK538226/',note:'Na sepse, a meta inicial usual é PAM ≥65 mmHg.',calc:v=>(v.pas+2*v.pad)/3},
{id:'cockcroft',name:'Clearance de creatinina · Cockcroft-Gault',area:'Nefrologia',summary:'Estimativa usada em ajuste de doses.',inputs:[input('age','Idade (anos)',18,120,1),input('kg','Peso (kg)',20,300,.1),input('creatinine','Creatinina (mg/dL)',.1,30,.01),{id:'female',label:'Sexo',options:[['1','Feminino'],['0','Masculino']]}],unit:'mL/min',formula:'(140 − idade) × peso ÷ (72 × creatinina) × 0,85 se feminino',source:'https://pubmed.ncbi.nlm.nih.gov/1244564/',note:'Muitas bulas de ajuste renal usam Cockcroft-Gault. Em obesidade, o peso a usar varia entre referências.',calc:v=>(140-v.age)*v.kg/(72*v.creatinine)*(v.female===1?.85:1)},
{id:'aa',name:'Gradiente alvéolo-arterial de O₂',area:'Pneumologia',summary:'Diferença entre O₂ alveolar e arterial ao nível do mar.',inputs:[input('fio2','FiO₂ (0,21 a 1)',.21,1,.01),input('paco2','PaCO₂ (mmHg)',5,150),input('pao2','PaO₂ (mmHg)',20,700)],unit:'mmHg',formula:'PAO₂ = FiO₂ × (760 − 47) − PaCO₂ ÷ 0,8; gradiente = PAO₂ − PaO₂.',source:'https://www.ncbi.nlm.nih.gov/books/NBK545153/',note:'Em ar ambiente, o gradiente esperado é cerca de idade ÷ 4 + 4. Pressão barométrica diferente em altitude.',calc:v=>v.fio2*713-v.paco2/.8-v.pao2},
{id:'pf',name:'Relação PaO₂/FiO₂',area:'Pneumologia',summary:'Oxigenação; critério de gravidade da SDRA (Berlim).',inputs:[input('pao2','PaO₂ (mmHg)',20,700),input('fio2','FiO₂ (0,21 a 1)',.21,1,.01)],unit:'',formula:'PaO₂ ÷ FiO₂',source:'https://pubmed.ncbi.nlm.nih.gov/22797452/',note:'SDRA (Berlim, com PEEP ≥5): leve 200–300, moderada 100–200, grave ≤100.',calc:v=>v.pao2/v.fio2},
{id:'peso-ideal',name:'Peso ideal · Devine',area:'Clínica Médica',summary:'Usado em ventilação protetora e em algumas doses.',inputs:[height,{id:'female',label:'Sexo',options:[['1','Feminino'],['0','Masculino']]}],unit:'kg',formula:'Homem: 50 + 0,91 × (altura cm − 152,4). Mulher: 45,5 + 0,91 × (altura cm − 152,4).',source:'https://www.ardsnet.org/files/ventilator_protocol_2008-07.pdf',note:'Ventilação protetora: volume corrente de 6 mL/kg de peso predito.',calc:v=>(v.female===1?45.5:50)+.91*(v.height-152.4),detail:v=>[`6 mL/kg: ${Math.round(6*((v.female===1?45.5:50)+.91*(v.height-152.4)))} mL · 8 mL/kg: ${Math.round(8*((v.female===1?45.5:50)+.91*(v.height-152.4)))} mL`]},
{id:'ldl',name:'LDL-colesterol · Friedewald',area:'Cardiologia',summary:'LDL estimado a partir do perfil lipídico.',inputs:[input('ct','Colesterol total (mg/dL)',50,1000,1),input('hdl','HDL (mg/dL)',5,200,1),input('tg','Triglicerídeos (mg/dL)',10,399,1)],unit:'mg/dL',formula:'LDL = CT − HDL − TG ÷ 5',source:'https://pubmed.ncbi.nlm.nih.gov/4337382/',note:'Não usar com triglicerídeos ≥400 mg/dL; Martin-Hopkins é mais preciso com LDL baixo ou TG elevado.',calc:v=>v.ct-v.hdl-v.tg/5},
{id:'gap-alb',name:'Ânion gap corrigido pela albumina',area:'Nefrologia',summary:'Evita subestimar o gap na hipoalbuminemia.',inputs:[input('na','Sódio (mEq/L)',80,200),input('cl','Cloreto (mEq/L)',50,170),input('hco','Bicarbonato (mEq/L)',1,60),input('alb','Albumina (g/dL)',.5,6,.1)],unit:'mEq/L',formula:'AG + 2,5 × (4 − albumina)',source:'https://pubmed.ncbi.nlm.nih.gov/9635385/',note:'Compare com o intervalo do laboratório.',calc:v=>v.na-(v.cl+v.hco)+2.5*(4-v.alb)},
{id:'fena',name:'Fração de excreção de sódio (FENa)',area:'Nefrologia',summary:'Ajuda a separar causa pré-renal de necrose tubular.',inputs:[input('una','Sódio urinário (mEq/L)',1,300),input('pna','Sódio sérico (mEq/L)',100,200),input('ucr','Creatinina urinária (mg/dL)',1,500),input('pcr','Creatinina sérica (mg/dL)',.1,30,.01)],unit:'%',formula:'(Na urinário × Cr sérica) ÷ (Na sérico × Cr urinária) × 100',source:'https://www.ncbi.nlm.nih.gov/books/NBK546638/',note:'<1% sugere pré-renal; >2% sugere lesão tubular. Diuréticos invalidam: prefira a FEUreia.',calc:v=>v.una*v.pcr/(v.pna*v.ucr)*100},
{id:'parkland',name:'Reposição em queimados · Parkland',area:'Cirurgia',summary:'Volume de cristaloide nas primeiras 24 h.',inputs:[input('kg','Peso (kg)',1,300,.1),input('scq','Superfície corporal queimada (%)',1,100,1)],unit:'mL em 24 h',formula:'4 mL × peso × %SCQ (queimaduras de 2º grau profundo e 3º grau); metade nas primeiras 8 h desde a queimadura.',source:'https://www.ncbi.nlm.nih.gov/books/NBK537190/',note:'Ponto de partida: ajuste pela diurese (0,5 mL/kg/h em adultos). Várias diretrizes iniciam com 2 mL/kg/%SCQ.',calc:v=>4*v.kg*v.scq,detail:v=>[`Primeiras 8 h: ${Math.round(2*v.kg*v.scq)} mL (${Math.round(2*v.kg*v.scq/8)} mL/h)`]},
{id:'choque',name:'Índice de choque',area:'Emergência',summary:'FC ÷ PAS: sinal precoce de hipoperfusão.',inputs:[input('fc','Frequência cardíaca (bpm)',20,250,1),input('pas','PA sistólica (mmHg)',30,300,1)],unit:'',formula:'Índice de choque = FC ÷ PAS',source:'https://pubmed.ncbi.nlm.nih.gov/7803359/',note:'Normal ≈ 0,5–0,7; ≥1,0 sugere choque e maior risco de transfusão e mortalidade.',calc:v=>v.fc/v.pas},
{id:'maco',name:'Carga tabágica',area:'Pneumologia',summary:'Anos-maço acumulados.',inputs:[input('cig','Cigarros por dia',1,120,1),input('anos','Anos fumando',1,90,1)],unit:'anos-maço',formula:'(cigarros por dia ÷ 20) × anos',source:'https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/lung-cancer-screening',note:'USPSTF: rastrear câncer de pulmão com TC de baixa dose de 50 a 80 anos com ≥20 anos-maço, fumantes ou que pararam há menos de 15 anos.',calc:v=>v.cig/20*v.anos},
{id:'maddrey',name:'Função discriminante de Maddrey',area:'Gastroenterologia',summary:'Gravidade da hepatite alcoólica.',inputs:[input('tp','Tempo de protrombina do paciente (s)',8,100),input('tpc','Tempo de protrombina controle (s)',8,20),input('bt','Bilirrubina total (mg/dL)',.1,60)],unit:'',formula:'4,6 × (TP paciente − TP controle) + bilirrubina total',source:'https://pubmed.ncbi.nlm.nih.gov/352788/',note:'≥32 indica hepatite alcoólica grave (considerar corticoide, se não houver contraindicação).',calc:v=>4.6*(v.tp-v.tpc)+v.bt}
];
export function calculate(id,raw){const c=calculators.find(c=>c.id===id);if(!c)return {error:'Calculadora não encontrada.'};const values={};for(const f of c.inputs){const text=String(raw[f.id]??'').trim().replace(',','.');if(!text)return {pending:true};const n=Number(text);if(!Number.isFinite(n)||(f.options?!f.options.some(([v])=>Number(v)===n):n<f.min||n>f.max||(f.step===1&&!Number.isInteger(n))))return {error:`Confira ${f.label.toLowerCase()}.`};values[f.id]=n;}return {value:c.calc(values),range:c.range,unit:c.unit,detail:c.detail?.(values)};}
