const input=(id,label,min,max,step=.1)=>({id,label,min,max,step});
const weight=input('weight','Peso (kg)',20,350),height=input('height','Altura (cm)',100,230);
export const calculators=[
{id:'bmi',name:'Índice de massa corporal',area:'Clínica Médica',summary:'Relação entre peso e altura em adultos.',inputs:[weight,height],unit:'kg/m²',formula:'Peso ÷ (altura em metros)²',source:'https://www.cdc.gov/growth-chart-training/hcp/using-bmi/calculating-bmi.html',note:'Não usar isoladamente para avaliar composição corporal. Categorias pediátricas e gestação exigem outras referências.',calc:v=>v.weight/(v.height/100)**2},
{id:'bsa',name:'Superfície corporal · Mosteller',area:'Clínica Médica',summary:'Estimativa de superfície corporal em adultos.',inputs:[weight,height],unit:'m²',formula:'√(altura em cm × peso em kg ÷ 3.600)',source:'https://pubmed.ncbi.nlm.nih.gov/3657876/',note:'Estimativa antropométrica. Não calcula dose de medicamentos.',calc:v=>Math.sqrt(v.height*v.weight/3600)},
{id:'egfr',name:'TFG estimada · CKD-EPI 2021',area:'Nefrologia',summary:'Creatinina, idade e sexo da equação; sem coeficiente racial.',inputs:[input('age','Idade (anos)',18,120,1),input('creatinine','Creatinina (mg/dL)',.1,30,.01),{id:'female',label:'Sexo usado na equação',options:[['1','Feminino'],['0','Masculino']]}],unit:'mL/min/1,73 m²',formula:'142 × min(Cr/κ,1)^α × max(Cr/κ,1)^−1,200 × 0,9938^idade × 1,012 (feminino). κ: 0,7/0,9; α: −0,241/−0,302 (feminino/masculino).',source:'https://www.niddk.nih.gov/research-funding/research-programs/kidney-clinical-research-epidemiology/laboratory/glomerular-filtration-rate-equations/adults',note:'Adultos com creatinina estável. Não usar em lesão renal aguda ou gestação. Um resultado isolado não diagnostica doença renal crônica.',calc:v=>{const f=v.female===1,k=f?.7:.9,a=f?-.241:-.302;return 142*Math.min(v.creatinine/k,1)**a*Math.max(v.creatinine/k,1)**-1.2*.9938**v.age*(f?1.012:1)}},
{id:'gap',name:'Ânion gap',area:'Nefrologia',summary:'Diferença entre os cátions e ânions medidos, sem potássio.',inputs:[input('na','Sódio (mEq/L)',80,200),input('cl','Cloreto (mEq/L)',50,170),input('hco','Bicarbonato (mEq/L)',1,60)],unit:'mEq/L',formula:'Na − (Cl + HCO₃)',source:'https://www.merckmanuals.com/professional/nephrology/acid-base-regulation-and-disorders/acid-base-disorders',note:'Sem correção pela albumina. Compare com o intervalo de referência do laboratório; hipoalbuminemia pode mascarar aumento.',calc:v=>v.na-v.cl-v.hco},
{id:'winter',name:'Compensação de Winter',area:'Nefrologia',summary:'PaCO₂ esperada na acidose metabólica.',inputs:[input('hco','Bicarbonato (mEq/L)',1,30)],unit:'mmHg',formula:'PaCO₂ esperada = 1,5 × HCO₃ + 8 ± 2',source:'https://www.merckmanuals.com/professional/nephrology/acid-base-regulation-and-disorders/acid-base-disorders',note:'Aplicar apenas na acidose metabólica e comparar com a PaCO₂ medida. Não indica parâmetros de ventilação.',calc:v=>1.5*v.hco+8,range:2},
];
export function calculate(id,raw){const c=calculators.find(c=>c.id===id);if(!c)return {error:'Calculadora não encontrada.'};const values={};for(const f of c.inputs){const text=String(raw[f.id]??'').trim().replace(',','.');if(!text)return {pending:true};const n=Number(text);if(!Number.isFinite(n)||(f.options?!f.options.some(([v])=>Number(v)===n):n<f.min||n>f.max||(f.step===1&&!Number.isInteger(n))))return {error:`Confira ${f.label.toLowerCase()}.`};values[f.id]=n;}return {value:c.calc(values),range:c.range,unit:c.unit};}
