// Original fictional teaching questions. No copied exam items or patient records.
const tri=(pt,en,es)=>[pt,en,es];
export const challengeSources={
 nnt:{name:'Oxford CEBM · NNT',url:'https://www.cebm.ox.ac.uk/resources/ebm-tools/number-needed-to-treat-nnt/'},
 risk:{name:'Oxford CEBM · Making a decision',url:'https://www.cebm.ox.ac.uk/resources/ebm-tools/making-a-decision'},
 accuracy:{name:'Cochrane · Diagnostic test accuracy',url:'https://www.cochrane.org/about-us/news/what-are-diagnostic-test-accuracy-reviews'},
 predictive:{name:'Cochrane · DTA Handbook, chapter 11',url:'https://training.cochrane.org/sites/training.cochrane.org/files/public/uploads/resources/downloadable_resources/English/DTA_Handbook_v1/DTA%20Handbook%20Chapter%2011%20201312.pdf'},
 randomized:{name:'NCI · Randomized clinical trial',url:'https://www.cancer.gov/publications/dictionaries/cancer-terms/def/randomized-clinical-trial'},
 prevalence:{name:'CDC · Analyzing and interpreting data',url:'https://www.cdc.gov/field-epi-manual/php/chapters/analyze-interpret-data.html'},
 design:{name:'CDC · Analytic studies',url:'https://www.cdc.gov/field-epi-manual/php/chapters/design-conduct-analyze-field-studies.html'},
};
export const challenges=[
 {id:'nnt',topic:tri('Benefício absoluto','Absolute benefit','Beneficio absoluto'),question:tri('Em um estudo fictício de 1 ano, o risco cai de 12% para 8%. Qual é o NNT para evitar um evento nesse período?','In a fictional 1-year study, risk falls from 12% to 8%. What is the NNT to prevent one event over that period?','En un estudio ficticio de 1 año, el riesgo baja del 12% al 8%. ¿Cuál es el NNT para evitar un evento en ese período?'),options:[tri('4','4','4'),tri('25','25','25'),tri('33','33','33'),tri('100','100','100')],answer:1,explanation:tri('A redução absoluta é 0,12 − 0,08 = 0,04. NNT = 1 ÷ 0,04 = 25, em 1 ano.','Absolute reduction is 0.12 − 0.08 = 0.04. NNT = 1 ÷ 0.04 = 25, over 1 year.','La reducción absoluta es 0,12 − 0,08 = 0,04. NNT = 1 ÷ 0,04 = 25, en 1 año.'),memory:tri('NNT: um dividido pelo benefício absoluto.','NNT: one divided by absolute benefit.','NNT: uno dividido por el beneficio absoluto.'),source:'nnt'},
 {id:'relative-risk',topic:tri('Relativo não é absoluto','Relative is not absolute','Relativo no es absoluto'),question:tri('Um estudo fictício reduz eventos de 10% para 5%. Qual é a redução relativa do risco?','A fictional study reduces events from 10% to 5%. What is the relative risk reduction?','Un estudio ficticio reduce eventos del 10% al 5%. ¿Cuál es la reducción relativa del riesgo?'),options:[tri('5%','5%','5%'),tri('50%','50%','50%'),tri('95%','95%','95%'),tri('2%','2%','2%')],answer:1,explanation:tri('(10 − 5) ÷ 10 = 50%. A redução absoluta é de 5 pontos percentuais. São medidas diferentes.','(10 − 5) ÷ 10 = 50%. Absolute reduction is 5 percentage points. These are different measures.','(10 − 5) ÷ 10 = 50%. La reducción absoluta es de 5 puntos porcentuales. Son medidas distintas.'),memory:tri('Relativo compara; absoluto dimensiona.','Relative compares; absolute gives scale.','Relativo compara; absoluto dimensiona.'),source:'risk'},
 {id:'sensitivity',topic:tri('Quem tem a doença','People with the disease','Personas con la enfermedad'),question:tri('Entre 100 pessoas com a doença, um teste identifica 90. Qual é sua sensibilidade nesta amostra?','Among 100 people with the disease, a test identifies 90. What is its sensitivity in this sample?','Entre 100 personas con la enfermedad, una prueba identifica a 90. ¿Cuál es su sensibilidad en esta muestra?'),options:[tri('10%','10%','10%'),tri('90%','90%','90%'),tri('100%','100%','100%'),tri('Não é possível calcular','Cannot be calculated','No se puede calcular')],answer:1,explanation:tri('Sensibilidade = positivos verdadeiros ÷ todas as pessoas com a doença: 90 ÷ 100 = 90%.','Sensitivity = true positives ÷ all people with the disease: 90 ÷ 100 = 90%.','Sensibilidad = verdaderos positivos ÷ todas las personas con la enfermedad: 90 ÷ 100 = 90%.'),memory:tri('Sensibilidade começa pelos doentes.','Sensitivity starts with the diseased group.','Sensibilidad empieza por los enfermos.'),source:'accuracy'},
 {id:'positive-predictive',topic:tri('O que significa positivo?','What does positive mean?','¿Qué significa positivo?'),question:tri('Em um cenário fictício, 100 testes são positivos, mas só 20 pessoas têm a doença. Qual é o valor preditivo positivo?','In a fictional scenario, 100 tests are positive, but only 20 people have the disease. What is the positive predictive value?','En un escenario ficticio, 100 pruebas son positivas, pero solo 20 personas tienen la enfermedad. ¿Cuál es el valor predictivo positivo?'),options:[tri('80%','80%','80%'),tri('100%','100%','100%'),tri('20%','20%','20%'),tri('5%','5%','5%')],answer:2,explanation:tri('VPP = positivos verdadeiros ÷ todos os positivos: 20 ÷ 100 = 20%. Resultado positivo não garante doença.','PPV = true positives ÷ all positives: 20 ÷ 100 = 20%. A positive result does not guarantee disease.','VPP = verdaderos positivos ÷ todos los positivos: 20 ÷ 100 = 20%. Un resultado positivo no garantiza enfermedad.'),memory:tri('VPP começa pelos positivos.','PPV starts with positive results.','VPP empieza por los positivos.'),source:'predictive'},
 {id:'randomization',topic:tri('Desenho de pesquisa','Study design','Diseño de investigación'),question:tri('O que define a alocação em um ensaio randomizado?','What determines allocation in a randomized trial?','¿Qué determina la asignación en un ensayo aleatorizado?'),options:[tri('Preferência do médico','Physician preference','Preferencia médica'),tri('Chance','Chance','Azar'),tri('Gravidade, sempre','Severity, always','Gravedad, siempre'),tri('Escolha do participante','Participant choice','Elección del participante')],answer:1,explanation:tri('A alocação é feita por um processo aleatório. Randomização não significa que participantes e pesquisadores desconhecem o grupo.','Allocation uses a random process. Randomization does not mean participants and researchers are unaware of the assigned group.','La asignación usa un proceso aleatorio. Aleatorización no significa que participantes e investigadores desconozcan el grupo asignado.'),memory:tri('Sorteio é alocação; cegamento é informação.','Randomization assigns; blinding conceals information.','Aleatorizar asigna; cegar oculta información.'),source:'randomized'},
 {id:'prevalence',topic:tri('Retrato da população','Population snapshot','Fotografía de la población'),question:tri('Hoje, 80 de 1.000 pessoas de uma população têm uma condição. Qual é a prevalência pontual?','Today, 80 of 1,000 people in a population have a condition. What is the point prevalence?','Hoy, 80 de 1.000 personas de una población tienen una condición. ¿Cuál es la prevalencia puntual?'),options:[tri('0,8%','0.8%','0,8%'),tri('8%','8%','8%'),tri('80%','80%','80%'),tri('92%','92%','92%')],answer:1,explanation:tri('80 ÷ 1.000 = 8%. Contamos casos existentes naquele momento, não apenas casos novos.','80 ÷ 1,000 = 8%. We count existing cases at that moment, not just new cases.','80 ÷ 1.000 = 8%. Contamos casos existentes en ese momento, no solo casos nuevos.'),memory:tri('Prevalência: retrato. Incidência: casos novos.','Prevalence: snapshot. Incidence: new cases.','Prevalencia: fotografía. Incidencia: casos nuevos.'),source:'prevalence'},
 {id:'case-control',topic:tri('Do desfecho à exposição','From outcome to exposure','Del desenlace a la exposición'),question:tri('Um estudo seleciona pessoas com e sem uma doença e compara exposições anteriores. Qual é o desenho?','A study selects people with and without a disease and compares earlier exposures. What is the design?','Un estudio selecciona personas con y sin una enfermedad y compara exposiciones previas. ¿Cuál es el diseño?'),options:[tri('Ensaio randomizado','Randomized trial','Ensayo aleatorizado'),tri('Série de casos','Case series','Serie de casos'),tri('Caso-controle','Case-control','Casos y controles'),tri('Revisão sistemática','Systematic review','Revisión sistemática')],answer:2,explanation:tri('A seleção começa pelo desfecho. Em seguida, comparam-se as exposições entre casos e controles.','Selection starts with the outcome. Exposures are then compared between cases and controls.','La selección empieza por el desenlace. Después se comparan exposiciones entre casos y controles.'),memory:tri('Caso-controle: comece pelo caso.','Case-control: start with the case.','Casos y controles: empieza por el caso.'),source:'design'},
];
export function localDay(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
export function dailyChallenge(day=localDay()){let hash=0;for(const c of day)hash=(hash*31+c.charCodeAt(0))>>>0;return challenges[hash%challenges.length];}
export function resolveChallenge(id,day){return challenges.find(q=>q.id===id)||dailyChallenge(day);}
export function challengeUrl(origin,base,id){if(!challenges.some(q=>q.id===id))throw Error('Unknown challenge');const url=new URL(base,origin);url.search='';url.hash=`desafio?id=${encodeURIComponent(id)}`;return url.href;}
export function readChallengeProgress(storage){try{const raw=JSON.parse(storage.getItem('2doctor-challenges-v1')||'{}');return Object.fromEntries(challenges.filter(q=>Number.isInteger(raw?.[q.id])&&raw[q.id]>=0&&raw[q.id]<q.options.length).map(q=>[q.id,raw[q.id]]));}catch{return {};}}
export function recordChallenge(progress,id,answer){const q=challenges.find(q=>q.id===id);if(!q||!Number.isInteger(answer)||answer<0||answer>=q.options.length||Number.isInteger(progress[id]))return progress;return {...progress,[id]:answer};}
