// Resource directory, not a claim of exam accreditation or local clinical validation.
export const countryResources = [
 {code:'BR',exam:'ENAMED',label:'Inep',url:'https://www.gov.br/inep/pt-br/areas-de-atuacao/avaliacao-e-exames-educacionais/enamed',tools:['enamed','questoes','caso'],focus:['Revisão de clínica, saúde coletiva e raciocínio por casos.','Review clinical medicine, public health and case-based reasoning.','Repasa clínica, salud pública y razonamiento por casos.']},
 {code:'PT',exam:'PNA',label:'ACSS · Internato Médico',url:'https://www.acss.min-saude.pt/category/profissionais/carreiras/medica/',tools:['caso','scores','anatomia'],focus:['Pratique a apresentação de casos e consulte as regras da formação especializada.','Practise case presentation and check specialty training requirements.','Practica la presentación de casos y consulta los requisitos de formación especializada.']},
 {code:'US',exam:'USMLE',label:'USMLE · Exam resources',url:'https://www.usmle.org/exam-resources',tools:['anatomia','genetica','desafio'],focus:['Conecte mecanismos básicos, raciocínio clínico e interpretação de evidências.','Connect basic mechanisms, clinical reasoning and evidence interpretation.','Conecta mecanismos básicos, razonamiento clínico e interpretación de evidencia.']},
 {code:'GB',exam:'MLA / PLAB',label:'GMC · MLA content map',url:'https://www.gmc-uk.org/education/medical-licensing-assessment/mla-content-map',tools:['caso','scores','desafio'],focus:['Treine comunicação, raciocínio e reconhecimento das suas incertezas.','Practise communication, reasoning and recognising uncertainty.','Practica comunicación, razonamiento y reconocimiento de la incertidumbre.']},
 {code:'ES',exam:'MIR',label:'Ministerio de Sanidad · FSE',url:'https://www.sanidad.gob.es/areas/profesionesSanitarias/formacionEspecializada/',tools:['caso','imagens','desafio'],focus:['Revise casos, imagens e leitura crítica; confira a convocatória oficial.','Review cases, images and critical appraisal; check the official call.','Repasa casos, imágenes y lectura crítica; consulta la convocatoria oficial.']},
 {code:'MX',exam:'ENARM',label:'CIFRHS · ENARM 2026',url:'https://www.cifrhs.salud.gob.mx/site1/enarm/2026/index.html',tools:['caso','scores','desafio'],focus:['Pratique raciocínio clínico e consulte as orientações da CIFRHS.','Practise clinical reasoning and consult CIFRHS guidance.','Practica razonamiento clínico y consulta las indicaciones de la CIFRHS.']},
 {code:'AR',exam:'Residencias',label:'Ministerio de Salud · Ingreso a residencias',url:'https://www.argentina.gob.ar/node/311392',tools:['caso','desafio','pesquisa'],focus:['Consulte o ingresso nas residências e exercite a discussão de casos.','Check residency entry information and practise discussing cases.','Consulta el ingreso a residencias y practica la discusión de casos.']},
 {code:'CO',exam:'Formação e registro',label:'Ministerio de Salud · ReTHUS',url:'https://www2.minsalud.gov.co/salud/PO/Paginas/registro-unico-nacional-del-talento-humano-en-salud-rethus.aspx',tools:['caso','scores','pesquisa'],focus:['Encontre o registro profissional e ferramentas de estudo; processos de residência variam por instituição.','Find the professional register and study tools; residency selection varies by institution.','Consulta el registro profesional y las herramientas de estudio; la selección de residencia varía por institución.']},
 {code:'CL',exam:'EUNACOM',label:'EUNACOM · Contenidos',url:'https://www.eunacom.cl/contenidos/contenidos.html',tools:['caso','scores','desafio'],focus:['Consulte a matriz e o perfil de conhecimentos antes de organizar a revisão.','Check the content matrix and knowledge profile before planning revision.','Consulta la matriz y el perfil de conocimientos antes de planificar el repaso.']},
 {code:'CA',exam:'MCCQE',label:'Medical Council of Canada',url:'https://mcc.ca/examinations-assessments/mccqe/',tools:['caso','desafio','pesquisa'],focus:['Pratique decisão clínica e avaliação crítica; confira os requisitos no MCC.','Practise clinical decision-making and critical appraisal; check MCC requirements.','Practica decisiones clínicas y evaluación crítica; consulta los requisitos del MCC.']},
 {code:'AU',exam:'AMC',label:'Australian Medical Council · Standard pathway',url:'https://www.amc.org.au/pathways/standard-pathway/',tools:['caso','desafio','anatomia'],focus:['Explore raciocínio clínico e os caminhos de avaliação descritos pelo AMC.','Explore clinical reasoning and the assessment pathways described by the AMC.','Explora razonamiento clínico y las vías de evaluación descritas por el AMC.']},
 {code:'IN',exam:'NEET-PG / FMGE',label:'NBEMS',url:'https://www.natboard.edu.in/index',tools:['anatomia','microbiologia','desafio'],focus:['Revise ciências básicas e casos; os exames têm finalidades e critérios distintos.','Review basic sciences and cases; these exams have different purposes and eligibility rules.','Repasa ciencias básicas y casos; estos exámenes tienen objetivos y requisitos distintos.']},
];
export const verifiedOn='2026-09-25';
export const pickText=(text,locale='pt-BR')=>Array.isArray(text)?text[locale==='en'?1:locale==='es'?2:0]:text;
export function countryProfile(code){return countryResources.find(item=>item.code===code)||null;}
