import type {Score} from './scores';
const yes=(id:string,pergunta:string,valor=1)=>({id,pergunta,valor,tipo:'checkbox' as const});
const options=(id:string,pergunta:string,rows:[string,number][])=>({id,pergunta,tipo:'opcoes' as const,opcoes:rows.map(([rotulo,valor])=>({rotulo,valor}))});
export const EXTRA_SCORES:Score[]=[{
 id:'wells-tvp',nome:'Wells · trombose venosa profunda',sigla:'TVP',especialidade:'Emergência',descricao:'Probabilidade clínica de TVP em adultos, classificação em dois níveis.',fonte:'NICE NG158 · https://www.nice.org.uk/guidance/ng158/chapter/recommendations',observacao:'Não confirma nem exclui TVP isoladamente. Uso combinado com avaliação clínica, dímero D e ultrassonografia conforme o protocolo.',criterios:[yes('cancer','Câncer ativo: tratamento atual, nos últimos 6 meses ou paliativo'),yes('paresia','Paresia, paralisia ou imobilização gessada recente de membro inferior'),yes('leito','Restrição ao leito por 3 dias ou mais, ou cirurgia de grande porte nas últimas 12 semanas sob anestesia geral/regional'),yes('dor','Dor localizada ao longo do sistema venoso profundo'),yes('edema','Edema de toda a perna'),yes('panturrilha','Panturrilha pelo menos 3 cm maior que a contralateral, medida 10 cm abaixo da tuberosidade tibial'),yes('cacifo','Edema com cacifo restrito à perna sintomática'),yes('colaterais','Veias superficiais colaterais não varicosas'),yes('previa','TVP documentada anteriormente'),yes('alternativo','Outro diagnóstico pelo menos tão provável quanto TVP',-2)],faixas:[{min:-2,max:1,texto:'TVP improvável pela classificação de Wells (≤1). Não é exclusão diagnóstica.',cor:'verde'},{min:2,max:9,texto:'TVP provável pela classificação de Wells (≥2). Prosseguir investigação conforme protocolo.',cor:'vermelho'}]
},{id:'4ts',nome:'4Ts · suspeita de HIT',sigla:'HIT',especialidade:'Hematologia',descricao:'Probabilidade pré-teste de trombocitopenia induzida por heparina.',fonte:'ASH 2018 · https://www.hematology.org/-/media/hematology/files/education/clinicians/guidelines-quality/documents/ash_vte_hit_pocketguide.pdf',observacao:'Dados incompletos reduzem a confiabilidade; reavaliar conforme evolução. O escore não confirma HIT.',criterios:[
options('queda','Queda de plaquetas e nadir (×10⁹/L)',[['Queda >50% e nadir ≥20',2],['Queda 30–50% ou nadir 10–19',1],['Queda <30% ou nadir <10',0]]),
options('tempo','Tempo em relação à heparina',[['Início claro nos dias 5–14; ou ≤1 dia com exposição nos últimos 30 dias',2],['Dias 5–14 sem cronologia clara; após dia 14; ou ≤1 dia com exposição há 30–100 dias',1],['Até 4 dias, sem exposição recente',0]]),
options('trombose','Trombose e manifestações',[['Trombose nova confirmada, necrose cutânea, reação após bolus IV ou hemorragia adrenal',2],['Trombose progressiva/recorrente ou suspeita; lesões cutâneas sem necrose',1],['Nenhuma',0]]),
options('outras','Outras causas para a queda',[['Nenhuma aparente',2],['Possíveis',1],['Definidas',0]])],faixas:[{min:0,max:3,texto:'Baixa probabilidade (0–3).',cor:'verde'},{min:4,max:5,texto:'Probabilidade intermediária (4–5).',cor:'amarelo'},{min:6,max:8,texto:'Alta probabilidade (6–8).',cor:'vermelho'}]}];
