import test from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';
import {chatContent} from '../shared/chat-content.mjs';import {validateAttachments,assistantPayload} from '../shared/chat-attachments.mjs';import {chat} from '../server/vytal-assistant.mjs';
const pdf={kind:'pdf',name:'teste.pdf',data:Buffer.from('%PDF-1.4\n'+ 'x'.repeat(110)).toString('base64')};
const image={kind:'image',name:'teste.jpg',mediaType:'image/jpeg',data:Buffer.from([255,216,255,224,0,0]).toString('base64')};
test('topic metadata becomes clean text plus actionable topics, including saved answers',()=>{const d=chatContent('Resposta médica.\n###TEMAS### ["Otalgia","Otite","Otalgia"]');assert.equal(d.text,'Resposta médica.');assert.deepEqual(d.topics,['Otalgia','Otite']);assert.equal(chatContent('Resposta\n###TEMAS### lixo').text,'Resposta');assert.deepEqual(chatContent('Resposta\n###TEMAS### [42,{},"Tema"] ').topics,['Tema']);});
test('streaming hides every partial protocol suffix without changing normal Markdown',()=>{const suffix='###TEMAS### ["Otalgia"]';for(let n=1;n<suffix.length;n++){assert.equal(chatContent('Resposta\n'+suffix.slice(0,n)).text,'Resposta');}assert.equal(chatContent('### Diagnóstico\nTexto').text,'### Diagnóstico\nTexto');assert.equal(chatContent('Linguagem C#').text,'Linguagem C#');});
test('binary limits, signature, total text length, count and PDF count are enforced',()=>{assert.equal(validateAttachments([pdf,image]).length,2);for(const a of [[{...pdf,data:'AAAA'}],[pdf,pdf],[{...image,mediaType:'text/html'}],[{kind:'text',name:'large.txt',text:'x'.repeat(12001)}],Array(6).fill(image),[{...pdf,data:Buffer.from('%PDF-'+ 'x'.repeat(3*1024*1024)).toString('base64')}]])assert.throws(()=>validateAttachments(a));});
test('documents survive existing 10-message and 4000-character API limits without truncation',()=>{const text='a'.repeat(11990)+'FINAL_TEST';const attachments=validateAttachments([{kind:'text',name:'texto.txt',text},image,pdf]);const result=assistantPayload({question:'Resuma',history:Array.from({length:6},()=>({role:'user',content:'antes'}))},attachments);assert.ok(result.historico.length<=10);assert.ok(result.historico.every(m=>m.content.length<=4000));assert.ok(result.historico.some(m=>m.content.includes('FINAL_TEST')));assert.equal(result.historico.at(-1).content,'Resuma');assert.deepEqual(result.imagens,[{mediaType:image.mediaType,data:image.data}]);assert.deepEqual(result.pdfs,[{nome:pdf.name,data:pdf.data}]);});
test('authenticated proxy forwards attachments to the existing assistant and keeps streaming',async()=>{const req={method:'POST',headers:{host:'www.vytalsaude.com.br',origin:'https://www.vytalsaude.com.br','x-wmed-request':'1',cookie:'__Secure-wmed_vytal=header.payload.signature'},body:{question:'Explique os arquivos',attachments:[pdf,image,{kind:'text',name:'nota.txt',text:'Texto de teste.'}]}};const res=Object.assign(new EventEmitter(),{out:'',setHeader(){},write(t){this.out+=t},end(t=''){this.out+=t}});await chat(req,res,{fetchImpl:async(url,options)=>{const data=JSON.parse(options.body);assert.ok(url.endsWith('/estudante/tutor/chat-stream'));assert.equal(data.pdfs.length,1);assert.equal(data.imagens.length,1);assert.ok(data.historico[0].content.includes('Texto de teste.'));return new Response('data: {"t":"Resposta"}\n\ndata: {"done":true}\n\n',{headers:{'content-type':'text/event-stream'}});}});assert.match(res.out,/event: done/);assert.doesNotMatch(res.out,/JVBER/);});
