import test from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';
import {discoveryInput,searchTrials,discovery} from '../server/discovery.mjs';
function mock(body,headers={}){return [{method:'POST',body,headers:{host:'2doctor.example',origin:'https://2doctor.example','x-wmed-request':'1','x-forwarded-for':Math.random().toString(),...headers}},Object.assign(new EventEmitter(),{statusCode:0,out:'',headers:{},setHeader(k,v){this.headers[k]=v},end(s=''){this.out+=s}})];}
test('Discovery accepts bounded topics and known providers only',()=>{assert.deepEqual(discoveryInput({query:'  asthma  ',kind:'trials'}),{query:'asthma',kind:'trials'});for(const b of [{query:'a',kind:'articles'},{query:'a'.repeat(161),kind:'articles'},{query:'asthma',kind:'https://evil.example'}])assert.throws(()=>discoveryInput(b));});
test('Clinical trial search uses a fixed registry, strips contacts and verifies NCT identifiers',async()=>{
 const result=await searchTrials('asthma',{fetchImpl:async(url,opts)=>{assert.equal(url.origin,'https://clinicaltrials.gov');assert.equal(url.searchParams.get('query.cond'),'asthma');assert.equal(opts.redirect,'error');return Response.json({totalCount:2,studies:[{protocolSection:{identificationModule:{nctId:'NCT12345678',briefTitle:'<b>Study</b>'},descriptionModule:{briefSummary:'Public summary'},statusModule:{overallStatus:'RECRUITING'},contactsLocationsModule:{centralContacts:[{email:'private'}],locations:[{country:'Brazil'},{country:'Brazil'}]}}},{protocolSection:{identificationModule:{nctId:'javascript:bad',briefTitle:'Bad'}}}]});}});
 assert.equal(result.items.length,1);assert.deepEqual(result.items[0].countries,['Brazil']);assert.equal(result.items[0].url,'https://clinicaltrials.gov/study/NCT12345678');assert.doesNotMatch(JSON.stringify(result),/private|javascript|<b>/);
});
test('Discovery returns bibliographic metadata and retrieval date without model synthesis',async()=>{const[req,res]=mock({query:'asthma',kind:'articles'});await discovery(req,res,{articleSearch:async()=>({total:1,query:'asthma',sources:[{id:'MED:1',url:'https://europepmc.org/article/MED/1',abstract:'x'.repeat(1200),title:'Review'}]}),now:()=>100000});const data=JSON.parse(res.out);assert.equal(res.statusCode,200);assert.equal(data.items[0].summary.length,900);assert.equal(data.items[0].abstract,undefined);assert.equal(data.retrievedAt,'1970-01-01T00:01:40.000Z');assert.equal(res.headers['Cache-Control'],'no-store');});
test('Discovery rejects cross-origin requests and oversized bodies before network',async()=>{for(const headers of [{origin:'https://evil.example'},{'x-wmed-request':undefined}]){const[req,res]=mock({query:'asthma',kind:'articles'},headers);await discovery(req,res,{articleSearch:()=>assert.fail()});assert.equal(res.statusCode,403);}const[req,res]=mock('x'.repeat(2050));await discovery(req,res,{articleSearch:()=>assert.fail()});assert.equal(res.statusCode,413);});
test('Provider failures become a retryable error without leaking provider details',async()=>{const[req,res]=mock({query:'asthma',kind:'articles'});await discovery(req,res,{articleSearch:()=>{throw Error('sensitive provider error')}});assert.equal(res.statusCode,502);assert.deepEqual(JSON.parse(res.out),{code:'SEARCH_UNAVAILABLE'});});
test('Discovery rate limit is enforced before calling the provider',async()=>{let called=0;for(let n=0;n<13;n++){const[req,res]=mock({query:'asthma',kind:'articles'},{'x-forwarded-for':'fixture-limited'});await discovery(req,res,{articleSearch:async()=>{called++;return {sources:[],total:0}},now:()=>200000});assert.equal(res.statusCode,n===12?429:200);}assert.equal(called,12);});
