import test from 'node:test';import assert from 'node:assert/strict';
import {createLocalPersistence,parseRecovery,holdWriter} from '../src/questions/persistence.mjs';
function memory(){const entries=new Map();return {getItem:k=>entries.get(k)||null,setItem:(k,v)=>entries.set(k,v),entries};}
const tick=()=>new Promise(resolve=>setImmediate(resolve));
test('quota failure stays dirty through later updates; recovery contains answer, session and hint',()=>{const disk=memory(),original=disk.setItem;let full=false;disk.setItem=(k,v)=>{if(full&&v.length>100)throw new DOMException('Quota','QuotaExceededError');original(k,v);};const key='quota-A',p=createLocalPersistence(disk,key);assert.equal(p.save({ledger:{attempts:[]}}),true);full=true;const ledger={attempts:[{id:'unique',answer:'B',hinted:true,activeMs:1300}]};assert.equal(p.save({ledger}),false);assert.equal(p.isDirty(),true);assert.equal(p.save({session:{runId:'run',answers:{q:'B'}}}),false);assert.equal(p.isDirty(),true);const recovery=parseRecovery(p.recovery(),key);assert.deepEqual(recovery.ledger,ledger);assert.equal(recovery.session.answers.q,'B');full=false;assert.equal(p.retry(),true);assert.equal(p.isDirty(),false);assert.deepEqual(createLocalPersistence(disk,key).read('ledger'),ledger);});
test('storage unavailable preserves a recoverable snapshot and warning; another account cannot restore it',()=>{const disk={getItem(){throw Error('Denied');},setItem(){throw Error('Denied');}},p=createLocalPersistence(disk,'denied-A');assert.equal(p.isDirty(),true);assert.equal(p.save({ledger:{attempts:[{answer:'C'}]}}),false);assert.equal(p.retry(),false);assert.equal(parseRecovery(p.recovery(),'denied-A').ledger.attempts[0].answer,'C');assert.throws(()=>parseRecovery(p.recovery(),'denied-B'));});
test('account switch keeps unsaved state in memory without contaminating another account',()=>{const disk=memory();disk.setItem=()=>{throw Error('Quota');};const a=createLocalPersistence(disk,'switch-A');a.save({ledger:{attempts:[{id:'A'}]},session:{runId:'A'}});const b=createLocalPersistence(disk,'switch-B');assert.equal(b.read('ledger'),null);const again=createLocalPersistence(disk,'switch-A');assert.equal(again.isDirty(),true);assert.equal(again.read('ledger').attempts[0].id,'A');assert.equal(again.read('session').runId,'A');});
test('atomic snapshot never partially writes ledger/session when quota fails',()=>{const disk=memory(),p=createLocalPersistence(disk,'atomic');p.save({ledger:{attempts:[]},session:{answers:{}}});const before=disk.entries.get('atomic:snapshot');disk.setItem=()=>{throw Error('Quota');};p.save({ledger:{attempts:[{id:'x'}]},session:{answers:{q:'B'}}});assert.equal(disk.entries.get('atomic:snapshot'),before);assert.equal(parseRecovery(p.recovery(),'atomic').session.answers.q,'B');});
function locks(){const held=new Set();return {request:async(name,options,callback)=>{if(held.has(name))return callback(null);held.add(name);try{return await callback({name});}finally{held.delete(name);}}};}
test('same account second tab is denied before writes; close releases and next tab reads latest session',async()=>{const manager=locks(),statesA=[],statesB=[],disk=memory();const close=holdWriter(manager,'owner',s=>{statesA.push(s);if(s==='ready')createLocalPersistence(disk,'owner').save({ledger:{attempts:[{id:'first'}]},session:{answers:{q:'B'}}});});const cancel=holdWriter(manager,'owner',s=>{statesB.push(s);if(s==='ready')throw Error('Second writer must not mount');});await tick();assert.deepEqual(statesA,['ready']);assert.deepEqual(statesB,['busy']);cancel();close();await tick();let status;const closeNext=holdWriter(manager,'owner',s=>{status=s;});await tick();assert.equal(status,'ready');assert.equal(createLocalPersistence(disk,'owner').read('ledger').attempts.length,1);assert.equal(createLocalPersistence(disk,'owner').read('session').answers.q,'B');closeNext();});
test('different accounts get independent locks; switching/cancelling pending acquisition cannot mount stale account',async()=>{const manager=locks();const results=[];const a=holdWriter(manager,'A',s=>results.push('A:'+s)),b=holdWriter(manager,'B',s=>results.push('B:'+s));await tick();assert.deepEqual(results,['A:ready','B:ready']);a();b();let run;const late={request:(name,options,cb)=>{run=()=>cb({name});return Promise.resolve();}};let mounted=false;const cancel=holdWriter(late,'old-account',()=>{mounted=true;});cancel();await run();assert.equal(mounted,false);});
test('unsupported browser fails closed instead of permitting conflicting writes',()=>{let status;holdWriter(null,'account',s=>{status=s;})();assert.equal(status,'unsupported');});
test('explicit validated recovery can restore after initial storage denial is removed',()=>{const disk=memory(),read=disk.getItem;disk.getItem=()=>{throw Error('Denied');};const p=createLocalPersistence(disk,'recover-denied');p.save({ledger:{attempts:[{answer:'D'}]}});const state=parseRecovery(p.recovery(),'recover-denied');disk.getItem=read;assert.equal(p.replace(state),true);assert.equal(p.isDirty(),false);assert.equal(p.readUnavailable(),false);assert.equal(createLocalPersistence(disk,'recover-denied').read('ledger').attempts[0].answer,'D');});
