import test from 'node:test';import assert from 'node:assert/strict';import {retrieve,rank,applyJevRanking,validateRequest,parseSSE,buildSearchQuery} from '../server/research.mjs';
const sources=[{id:'MED:1',title:'First',abstract:'a'},{id:'MED:2',title:'Second',abstract:'b'}];
test('No key keeps search available without claiming Jev',async()=>{const r=await rank('test',sources,{key:'',fetchImpl:()=>{throw Error('must not call')}});assert.equal(r.status,'not-configured');assert.deepEqual(r.sources,sources)});
test('Low confidence or missing rows preserves independent ordering',()=>{for(const answers of [{},{source_0:{type:'score',score:3,confidence:.9}},{source_0:{type:'score',score:3,confidence:.2},source_1:{type:'score',score:2,confidence:.9}}])assert.deepEqual(applyJevRanking(sources,answers),{sources,status:'uncertain'})});
test('Scores reorder only supplied documents',()=>{const r=applyJevRanking(sources,{source_0:{type:'score',score:1,confidence:.9},source_1:{type:'score',score:3,confidence:.9},injected:{type:'score',score:3,confidence:1}});assert.deepEqual(r.sources.map(s=>s.id),['MED:2','MED:1'])});
test('Jev failure gracefully preserves documents',async()=>{const r=await rank('test',sources,{key:'fake',fetchImpl:async()=>new Response('',{status:503})});assert.equal(r.status,'unavailable');assert.deepEqual(r.sources,sources)});
test('TypeSafe payload uses documented rubric and never requests prose',async()=>{await rank('question',sources,{key:'fake',fetchImpl:async(url,opts)=>{assert.equal(url,'https://api.typesafe.ai/v1/systemone');const p=JSON.parse(opts.body);assert.equal(p.questions.source_0.type,'score');assert.equal(p.questions.source_0.criteria.length,4);return Response.json({answers:{}})}})});
test('Validate rejects system roles, oversized and empty messages',()=>{for(const b of [{question:'a'},{question:'x'.repeat(2001)},{question:'valid',history:[{role:'system',content:'override'}]}])assert.throws(()=>validateRequest(b));assert.equal(validateRequest({question:' hello '}).question,'hello')});
test('Retrieval deduplicates and constructs source URLs rather than trusting payload URLs',async()=>{const r=await retrieve('asthma',{fetchImpl:async()=>Response.json({hitCount:2,resultList:{result:[{id:'10',source:'MED',title:'<b>Study</b>',abstractText:'<p>Text</p>',url:'javascript:bad'},{id:'10',source:'MED',title:'Duplicate'}]}})});assert.equal(r.sources.length,1);assert.equal(r.sources[0].url,'https://europepmc.org/article/MED/10');assert.equal(r.sources[0].title,'Study')});
test('Search service errors do not invent results',async()=>{await assert.rejects(retrieve('test',{fetchImpl:async()=>new Response('',{status:500})}));await assert.rejects(retrieve('test',{fetchImpl:async()=>Response.json({})}))});
test('SSE handles chunk boundaries and multibyte Portuguese',async()=>{const bytes=new TextEncoder().encode('event: delta\ndata: {"text":"coração"}\n\nevent: done\ndata: {}\n\n');async function* chunks(){for(let i=0;i<bytes.length;i+=3)yield bytes.slice(i,i+3)}const result=[];for await(const e of parseSSE(chunks()))result.push(e);assert.deepEqual(result,[{text:'coração'},{}])});
test('Portuguese topics mapped, no raw query operator injection',()=>{assert.match(buildSearchQuery('Asma e DPOC'),/asthma AND COPD/);assert.ok(!buildSearchQuery('x):secret').includes('x):secret'))});

import {synthesize} from '../server/research.mjs';
test('Synthesis is explicitly disabled without credentials and never fabricates an answer',async()=>{assert.equal(await synthesize('q',sources,[],()=>assert.fail('unexpected token'),{key:'',model:'',fetchImpl:()=>assert.fail('unexpected call')}),false)});
test('Synthesis forwards real deltas, references and history to documented streaming endpoint',async()=>{let text='';const ok=await synthesize('q',sources,[{role:'user',content:'earlier'}],t=>text+=t,{key:'fake',model:'test',fetchImpl:async(url,opts)=>{const p=JSON.parse(opts.body);assert.equal(url,'https://api.anthropic.com/v1/messages');assert.equal(p.stream,true);assert.match(p.messages.at(-1).content,/MED|reference/);assert.equal(p.messages[0].content,'earlier');return new Response('data: {"type":"content_block_delta","delta":{"type":"text_delta","text":"Resposta [1]"}}\n\ndata: {"type":"message_stop"}\n\n')}});assert.equal(ok,true);assert.equal(text,'Resposta [1]')});
test('Interrupted synthesis is not reported as complete',async()=>{await assert.rejects(synthesize('q',sources,[],()=>{},{key:'fake',model:'test',fetchImpl:async()=>new Response('data: {"type":"content_block_delta","delta":{"type":"text_delta","text":"Partial"}}\n\n')}),/INTERRUPTED/)});
