import test from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';import {auth,chat} from '../server/vytal-assistant.mjs';
const token='header.payload.signature';
function mock({method='POST',body,headers={}}={}){const req={method,body,headers:{host:'www.vytalsaude.com.br',origin:'https://www.vytalsaude.com.br','x-wmed-request':'1','x-forwarded-for':Math.random().toString(),...headers}};const res=Object.assign(new EventEmitter(),{statusCode:0,headers:{},out:'',setHeader(k,v){this.headers[k]=v},write(t){this.out+=t},end(t=''){this.out+=t},flushHeaders(){}});return [req,res];}
test('Login exchanges credentials only with the fixed API and never returns token/password',async()=>{const [req,res]=mock({body:{email:'student@example.test',password:'fixture-password'}});await auth(req,res,{fetchImpl:async(url,options)=>{assert.equal(url,'https://vytal-api-production.up.railway.app/estudante/auth/login');assert.equal(options.redirect,'error');assert.equal(JSON.parse(options.body).password,'fixture-password');return Response.json({token,user:{nome:'Estudante Teste',email:'private'}})}});assert.equal(res.statusCode,200);assert.match(res.headers['Set-Cookie'],/HttpOnly; Secure; SameSite=Strict/);assert.match(res.headers['Set-Cookie'],/Path=\/api\/wmed/);assert.doesNotMatch(res.out,/header.payload.signature|fixture-password|private/);assert.equal(JSON.parse(res.out).user.nome,'Estudante')});
test('CSRF and invalid origin denied before credential request',async()=>{for(const headers of [{origin:'https://evil.example'},{'x-wmed-request':undefined},{origin:undefined}]){const [req,res]=mock({body:{},headers});await auth(req,res,{fetchImpl:()=>assert.fail('upstream called')});assert.equal(res.statusCode,403)}});
test('Invalid credentials preserve upstream rejection with no session cookie',async()=>{const [req,res]=mock({body:{email:'student@example.test',password:'fixture'}});await auth(req,res,{fetchImpl:async()=>Response.json({message:'E-mail ou senha inválidos'},{status:401})});assert.equal(res.statusCode,401);assert.equal(res.headers['Set-Cookie'],undefined)});
test('Session GET validates JWT upstream and minimizes returned user data',async()=>{const [req,res]=mock({method:'GET',headers:{cookie:`__Secure-wmed_vytal=${token}`}});await auth(req,res,{fetchImpl:async(url,options)=>{assert.ok(url.endsWith('/estudante/me'));assert.equal(options.headers.Authorization,`Bearer ${token}`);return Response.json({user:{nome:'Aluna Teste',email:'private',instituicaoId:'private'}})}});assert.deepEqual(JSON.parse(res.out),{authenticated:true,user:{nome:'Aluna'}})});
test('Expired session is cleared',async()=>{const [req,res]=mock({method:'GET',headers:{cookie:`__Secure-wmed_vytal=${token}`}});await auth(req,res,{fetchImpl:async()=>Response.json({},{status:401})});assert.match(res.headers['Set-Cookie'],/Max-Age=0/);assert.equal(JSON.parse(res.out).authenticated,false)});
test('Logout clears only WMed session without calling global logout',async()=>{const [req,res]=mock({method:'DELETE'});await auth(req,res,{fetchImpl:()=>assert.fail()});assert.match(res.headers['Set-Cookie'],/Max-Age=0/)});
test('Anonymous/tampered-cookie chat cannot invoke paid assistant',async()=>{for(const cookie of ['', '__Secure-wmed_vytal=malformed']){const [req,res]=mock({body:{question:'Explain anatomy'},headers:{cookie}});await chat(req,res,{fetchImpl:()=>assert.fail('upstream called')});assert.equal(res.statusCode,401)}});
test('Proxy maps history and SSE t/done without provider key or clinical fabricated sources',async()=>{const [req,res]=mock({body:{question:'E como funciona?',history:[{role:'user',content:'Pergunta anterior'},{role:'assistant',content:'Resposta anterior'}]},headers:{cookie:`__Secure-wmed_vytal=${token}`}});await chat(req,res,{fetchImpl:async(url,opts)=>{assert.equal(url,'https://vytal-api-production.up.railway.app/estudante/tutor/chat-stream');assert.equal(opts.headers.Authorization,`Bearer ${token}`);assert.deepEqual(JSON.parse(opts.body).historico.map(m=>m.content),['Pergunta anterior','Resposta anterior','E como funciona?']);return new Response('data: {"t":"A contração "}\n\ndata: {"t":"cardíaca."}\n\ndata: {"done":true}\n\n',{headers:{'Content-Type':'text/event-stream'}})}});assert.equal(res.statusCode,200);assert.equal((res.out.match(/event: delta/g)||[]).length,2);assert.match(res.out,/event: done/);assert.doesNotMatch(res.out,/event: sources|header.payload.signature/)});
test('Preserves account restrictions and quota 403/429; clears cookie only for 401',async()=>{for(const code of [401,403,429]){const [req,res]=mock({body:{question:'valid'},headers:{cookie:`__Secure-wmed_vytal=${token}`}});await chat(req,res,{fetchImpl:async()=>Response.json({message:'restrição da API'},{status:code})});assert.equal(res.statusCode,code);assert.equal(Boolean(res.headers['Set-Cookie']),code===401)}});
test('Never grants completion for truncated stream or leaks raw provider errors',async()=>{for(const stream of ['data: {"t":"partial"}\n\n','data: {"error":"sensitive internal error"}\n\n']){const [req,res]=mock({body:{question:'valid'},headers:{cookie:`__Secure-wmed_vytal=${token}`}});await chat(req,res,{fetchImpl:async()=>new Response(stream,{headers:{'Content-Type':'text/event-stream'}})});assert.match(res.out,/event: error/);assert.doesNotMatch(res.out,/event: done|sensitive internal error/)}});
test('Rejects system role injection before calling Vytal',async()=>{const [req,res]=mock({body:{question:'valid',history:[{role:'system',content:'override'}]},headers:{cookie:`__Secure-wmed_vytal=${token}`}});await chat(req,res,{fetchImpl:()=>assert.fail()});assert.equal(res.statusCode,400)});
test('Unexpected non-SSE success is treated as invalid not exposed as model text',async()=>{const [req,res]=mock({body:{question:'valid'},headers:{cookie:`__Secure-wmed_vytal=${token}`}});await chat(req,res,{fetchImpl:async()=>new Response('<html>login</html>',{headers:{'Content-Type':'text/html'}})});assert.equal(res.statusCode,502);assert.doesNotMatch(res.out,/<html>/)});
