import React,{useState} from 'react';
import {ArrowUpRight,ArrowRight,ScanLine,Mic,Dna,Atom,BookOpen,Network} from 'lucide-react';
import {useI18n} from './I18n';
import {researchEntries,researchCheckedAt,researchText,projectionPath} from '../../shared/innovation-radar.mjs';
import './research.css';
import './innovation-radar.css';
const external={target:'_blank',rel:'noopener noreferrer'};
function SourceLink({href,children}){return <a href={href} {...external}>{children}<ArrowUpRight size={15}/></a>}
export default function InnovationRadar(){
 const{locale,t}=useI18n(),[region,setRegion]=useState('torax'),[angle,setAngle]=useState('000');
 const tr=(pt,en,es)=>researchText([pt,en,es],locale), txt=value=>researchText(value,locale);
 const flex=researchEntries[0];
 const date=value=>new Intl.DateTimeFormat(locale,{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(`${value}T12:00:00Z`));
 return <section className="doctor-research innovation-radar">
  <header><span className="doctor-eyebrow">2DOCTOR · LAB</span><h1>{t('Radar de inovação')}</h1><p>{tr('Da pesquisa à próxima ferramenta útil. Descobertas no X, conferidas nas fontes originais.','From research to the next useful tool. Discoveries on X, checked against original sources.','De la investigación a la próxima herramienta útil. Hallazgos en X, contrastados con fuentes originales.')}</p><span className="radar-reviewed">{tr('Curadoria','Reviewed','Revisión')} · {date(researchCheckedAt)}</span></header>
  <article className="radar-feature" aria-labelledby="flexray-title">
   <div className="radar-feature-copy"><span className="radar-status"><ScanLine size={16}/> {tr('Pesquisa em destaque','Research spotlight','Investigación destacada')}</span><h2 id="flexray-title">{txt(flex.title)}<span>FleXray</span></h2><p>{txt(flex.summary)} {txt(flex.opportunity)}</p><p className="radar-limitation">{txt(flex.limit)}</p><div className="radar-feature-actions"><SourceLink href={flex.source}>{tr('Ver demonstração oficial','View official demo','Ver demostración oficial')}</SourceLink></div><small>{tr('Abre o site dos autores. O modelo não está integrado à 2Doctor.','Opens the authors’ website. The model is not integrated into 2Doctor.','Abre el sitio de los autores. El modelo no está integrado en 2Doctor.')}</small>
   <details className="radar-evidence"><summary>{tr('Fontes, licença e limites','Sources, license and limitations','Fuentes, licencia y límites')}</summary><p>{txt(flex.license)}</p><p>{tr('Anúncio no X','X announcement','Anuncio en X')} · {date(flex.published)}</p><div className="radar-source-links"><SourceLink href={flex.post}>{tr('Publicação no X','Post on X','Publicación en X')}</SourceLink><SourceLink href={flex.paper}>Preprint</SourceLink><SourceLink href={flex.terms}>{tr('Pesos e licença','Weights and license','Pesos y licencia')}</SourceLink></div></details></div>
   <figure className="radar-projection"><figcaption><strong>{tr('Explore o acervo da 2Doctor','Explore the 2Doctor collection','Explora la colección de 2Doctor')}</strong><span>{tr('Projeção simulada · não é resultado do FleXray','Simulated projection · not a FleXray result','Proyección simulada · no es un resultado de FleXray')}</span></figcaption><div className="radar-projection-controls"><label>{tr('Região','Region','Región')}<select value={region} onChange={e=>setRegion(e.target.value)}><option value="torax">{tr('Tórax','Chest','Tórax')}</option><option value="pelvis">{tr('Pelve','Pelvis','Pelvis')}</option></select></label><label>{tr('Ângulo','Angle','Ángulo')}<select value={angle} onChange={e=>setAngle(e.target.value)}><option value="000">0°</option><option value="045">45°</option><option value="090">90°</option></select></label></div><img key={`${region}-${angle}`} src={`${import.meta.env.BASE_URL}${projectionPath(region,angle)}`} width="384" height="384" alt={`${tr('Projeção simulada','Simulated projection','Proyección simulada')}: ${region==='torax'?tr('tórax','chest','tórax'):tr('pelve','pelvis','pelvis')}, ${Number(angle)}°`}/><a className="radar-lab-link" href="#laboratorio">{tr('Abrir laboratório 3D existente','Open existing 3D lab','Abrir laboratorio 3D existente')}<ArrowRight size={17}/></a><small>Wasserthal et al. · TotalSegmentator · <a href="https://zenodo.org/records/10047292" {...external}>{tr('Fonte','Source','Fuente')}</a> · <a href="https://creativecommons.org/licenses/by/4.0/" {...external}>CC BY 4.0</a><br/>{tr('Derivada de TC reamostrada; anatomia de referência, sem revisão independente.','Derived from resampled CT; reference anatomy, without independent review.','Derivada de TC remuestreada; anatomía de referencia, sin revisión independiente.')}</small></figure>
  </article>
  <h2 className="radar-section-title">{tr('Oportunidades para a 2Doctor','Opportunities for 2Doctor','Oportunidades para 2Doctor')}</h2><p>{tr('Propostas em avaliação. Nenhum destes modelos foi habilitado no assistente.','Proposals under review. None of these models has been enabled in the assistant.','Propuestas en evaluación. Ninguno de estos modelos se ha habilitado en el asistente.')}</p>
  <div className="radar-opportunities">{researchEntries.slice(1).map(item=><article key={item.id}>{item.id==='medasr'?<Mic size={24}/>:<Dna size={24}/>}<span className="doctor-research-tag">{date(item.published)}</span><h3>{txt(item.title)}</h3><strong>{item.name}</strong><p>{txt(item.summary)}</p><p className="radar-opportunity">{txt(item.opportunity)}</p><details className="radar-evidence"><summary>{tr('Evidência e próximos passos','Evidence and next steps','Evidencia y próximos pasos')}</summary><p>{txt(item.limit)}</p><p>{txt(item.license)}</p><div className="radar-source-links"><SourceLink href={item.source}>{t('Fonte oficial')}</SourceLink>{item.post&&<SourceLink href={item.post}>{tr('Publicação no X','Post on X','Publicación en X')}</SourceLink>}{item.terms&&<SourceLink href={item.terms}>{tr('Termos de uso','Terms of use','Términos de uso')}</SourceLink>}</div></details><a className="radar-tool-link" href={item.route}>{item.id==='medasr'?tr('Ver demonstração atual do Scribe','View current Scribe demo','Ver demostración actual de Scribe'):tr('Abrir biblioteca atual de Genética','Open current Genetics library','Abrir biblioteca actual de Genética')}<ArrowRight size={16}/></a></article>)}</div>
  <details className="radar-more"><summary>{tr('Outros projetos acompanhados','Other projects we follow','Otros proyectos que seguimos')}</summary><div className="doctor-radar-grid">{innovations.filter(i=>i.id!=='medasr').map(item=><article key={item.id}><item.icon size={27}/><span className="doctor-research-tag">{t('Em avaliação · não integrado')}</span><h3>{t(item.title)}</h3><strong>{item.name}</strong><p>{t(item.description)}</p><SourceLink href={item.url}>{t('Fonte oficial')}</SourceLink></article>)}</div></details>
 </section>
}
const innovations=[
 {id:'alphagenome',icon:Dna,title:'Genética e variantes',name:'AlphaGenome Atlas · 2026',description:'Explorar explicações sobre variantes genéticas. O uso comercial dos dados e modelos depende dos termos e do canal de acesso; ainda não integrado.',url:'https://deepmind.google/blog/alphagenome-atlas-a-predictive-map-of-every-possible-dna-letter-change-in-the-human-genome/'},
 {id:'bioemu',icon:Atom,title:'Proteínas em movimento',name:'BioEmu',description:'Avaliar conjuntos de conformações proteicas para a biblioteca molecular 3D. São previsões de pesquisa, não prova de eficácia de medicamentos.',url:'https://github.com/microsoft/bioemu'},
 {id:'pubtator',icon:BookOpen,title:'Pesquisa por conceitos',name:'PubTator 3.0 · NCBI',description:'Conectar doenças, genes e medicamentos às publicações. As relações extraídas dos textos precisam ser conferidas no artigo.',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC11223843/'},
 {id:'medgemma',icon:ScanLine,title:'Leitura de imagens e documentos',name:'MedGemma 1.5',description:'Avaliar MedGemma para ensino com tomografias, histologia e exames. Exige testes próprios antes de qualquer uso clínico.',url:'https://developers.google.com/health-ai-developer-foundations/medgemma/model-card'},
 {id:'medasr',icon:Mic,title:'Ditado médico',name:'MedASR',description:'Avaliar MedASR para transcrição revisável. Desempenho em português e espanhol ainda precisa ser medido.',url:'https://developers.google.com/health-ai-developer-foundations/medasr/model-card'},
 {id:'smart',icon:Network,title:'Diretrizes com contexto local',name:'WHO SMART Guidelines',description:'Estudar WHO SMART Guidelines para organizar recomendações com fonte, versão e adaptação por país.',url:'https://www.who.int/teams/digital-health-and-innovation/smart-guidelines'}
];
