import React, {useEffect,useRef,useState} from 'react';
import {Menu,X,Plus,History,MessageSquare,Stethoscope,GraduationCap,FlaskConical,Search,ArrowUpRight,ChevronRight,Palette,Check,UserRound,BookOpen,Calculator,FileText} from 'lucide-react';
import {moduleItems} from '../Modules';
import {searchNavigation,navigationGroups} from '../../shared/product.mjs';
const groupIcons={plantao:Stethoscope,estudos:GraduationCap,laboratorio:FlaskConical};
export function Mark({className=''}){return <svg className={className} viewBox="0 0 175 124" fill="currentColor" aria-hidden="true"><path fillRule="evenodd" d="M5 34C13 12 32 0 58 0H112C151 0 175 25 175 61C175 99 150 124 112 124H0V113C0 92 11 78 32 64L51 52C63 44 66 37 63 32C59 23 42 25 36 34ZM84 26C94 52 82 67 56 82L34 99H109C134 99 147 84 147 62C147 40 134 26 112 26Z"/></svg>}
export function Rail({module,navigate,onNew,onHistory,onAccount,onMenu,busy}){
 return <aside className="doctor-rail" aria-label="Acessos rápidos"><button className="doctor-rail-brand" onClick={()=>navigate('chat')} aria-label="2Doctor início"><Mark/></button><button onClick={onMenu} title="Abrir menu" aria-label="Abrir menu"><Menu size={21}/></button><button onClick={onNew} title="Nova conversa" aria-label="Nova conversa"><Plus size={22}/></button><button onClick={onHistory} disabled={busy} title="Histórico de conversas" aria-label="Histórico de conversas"><History size={21}/></button><span className="doctor-rail-rule"/><button aria-current={module==='chat'?'page':undefined} onClick={()=>navigate('chat')} title="Chat" aria-label="Chat"><MessageSquare size={21}/></button>{navigationGroups.map(group=>{const Icon=groupIcons[group.id];return <button key={group.id} aria-current={group.modules.includes(module)?'page':undefined} onClick={()=>onMenu(group.id)} title={group.label} aria-label={group.label}><Icon size={21}/></button>})}<div className="doctor-rail-space"/><button onClick={onAccount} title="Minha conta" aria-label="Minha conta"><UserRound size={21}/></button></aside>
}
export function Header({module,onHome,onMenu,onNew,onHistory,onAccount,session,theme,setTheme,themes,busy}){
 return <header className="doctor-header"><button className="doctor-mobile-menu" aria-label="Abrir menu" onClick={onMenu}><Menu size={21}/></button><a className="doctor-wordmark" href="#chat" onClick={e=>{e.preventDefault();onHome();}}><Mark/><span>2Doctor</span></a><span className="doctor-header-divider"/><span className="doctor-page-name">{module==='chat'?'Seu assistente médico':moduleItems.find(item=>item.id===module)?.label}</span><span className="doctor-header-space"/><button className="doctor-mobile-action" aria-label="Histórico de conversas" disabled={busy} onClick={onHistory}><History size={20}/></button><button className="doctor-mobile-action" aria-label="Nova conversa" onClick={onNew}><Plus size={22}/></button><details className="theme-picker"><summary aria-label="Escolher aparência"><Palette size={19}/></summary><div className="theme-options" role="group" aria-label="Tema de cores">{themes.map(([id,label])=><button key={id} aria-pressed={theme===id} onClick={e=>{setTheme(id);e.currentTarget.closest('details').open=false;}}><span className={`theme-dot ${id}`}/>{label}{theme===id&&<Check size={15}/>}</button>)}</div></details><button className="doctor-account" onClick={onAccount}>{session?.authenticated?<><UserRound size={16}/><span>Minha conta</span></>:'Entrar'}</button></header>
}
export function Drawer({onClose,onNavigate,onNew,onHistory,onSources,onAccount,module,initialGroup,busy}){
 const [query,setQuery]=useState('');const ref=useRef(null);const groups=searchNavigation(moduleItems,query);
 useEffect(()=>{const prev=document.activeElement;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';ref.current.querySelector('input')?.focus();if(initialGroup)ref.current.querySelector(`#doctor-group-${initialGroup}`)?.scrollIntoView({block:'nearest'});return()=>{document.body.style.overflow=overflow;prev?.focus?.();};},[]);
 function keys(e){if(e.key==='Escape'){e.preventDefault();onClose();}if(e.key==='Tab'){const elements=[...ref.current.querySelectorAll('button:not(:disabled), input, a[href]')];if(e.shiftKey&&document.activeElement===elements[0]){e.preventDefault();elements.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===elements.at(-1)){e.preventDefault();elements[0]?.focus();}}}
 return <div className="doctor-drawer-shade" onClick={onClose}><section ref={ref} className="doctor-drawer" role="dialog" aria-modal="true" aria-label="Menu 2Doctor" onClick={e=>e.stopPropagation()} onKeyDown={keys}><header><a className="doctor-wordmark" href="#chat" onClick={()=>onNavigate('chat')}><Mark/><span>2Doctor</span></a><button aria-label="Fechar menu" onClick={onClose}><X size={21}/></button></header><label className="doctor-nav-search"><Search size={18}/><input placeholder="Buscar ferramenta ou matéria" aria-label="Buscar ferramenta ou matéria" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="doctor-nav-shortcuts"><button onClick={()=>{onNew();onClose();}}><Plus size={18}/>Nova conversa</button><button onClick={()=>{onHistory();onClose();}} disabled={busy}><History size={18}/>Histórico</button></div><nav aria-label="Ferramentas 2Doctor" className="doctor-nav-scroll">{groups.length?groups.map(group=><section id={`doctor-group-${group.id}`} key={group.id}><h2>{group.label}</h2>{group.items.map(item=><button key={item.id} aria-current={module===item.id?'page':undefined} onClick={()=>onNavigate(item.id)}><item.icon size={19}/><span>{item.id==='laboratorio'?'Radiografia em 3D':item.label}<small>{item.id==='laboratorio'?'Protótipo interativo':item.description}</small></span><ChevronRight size={15}/></button>)}</section>):<p className="doctor-no-results">Nenhuma ferramenta encontrada.</p>}</nav><footer><button onClick={()=>{onSources();onClose();}}><BookOpen size={17}/>Fontes da conversa</button><button onClick={()=>{onAccount();onClose();}}><UserRound size={17}/>Minha conta</button></footer></section></div>
}
export function Welcome(){return <div className="doctor-welcome"><div className="doctor-hero-mark"><Mark/></div><p className="doctor-eyebrow">NO PLANTÃO. NOS ESTUDOS.</p><h1>Como posso ajudar hoje?</h1><p>Conecte o que você sabe ao que precisa descobrir.</p></div>}
export function QuickActions({navigate,onCase,onPrompt}){
 return <div className="doctor-quick-area"><div className="doctor-quick-actions"><button onClick={onCase}><FileText size={20}/><span>Discutir um caso<small>Organize o raciocínio clínico</small></span><ArrowUpRight size={17}/></button><button onClick={()=>navigate('scores')}><Calculator size={20}/><span>Consultar um score<small>Calculadoras à mão</small></span><ArrowUpRight size={17}/></button><button onClick={()=>navigate('questoes')}><GraduationCap size={21}/><span>Estudar para provas<small>Questões e comentários</small></span><ArrowUpRight size={17}/></button></div><div className="doctor-suggestions"><span>Experimente</span>{['Compare asma e DPOC','Explique o ciclo cardíaco'].map(text=><button key={text} onClick={()=>onPrompt(text)}>{text}<ArrowUpRight size={13}/></button>)}</div></div>
}
