import React,{useState} from 'react';
import {ArrowUpRight,Globe2,Search} from 'lucide-react';
import {useI18n} from './I18n';
import {countries} from '../../shared/international.mjs';
import {sourceDirectory,sourceCategories,sourceText,sourceReviewedOn} from '../../shared/official-sources.mjs';
import './official-sources.css';
const copy={
 title:['Fontes oficiais','Official sources','Fuentes oficiales'],intro:['Encontre a referência do país em que você atua.','Find references for the country where you work.','Encuentra referencias del país donde trabajas.'],country:['País desta consulta','Country for this lookup','País de esta consulta'],pick:['Escolha um país','Choose a country','Elige un país'],other:['Outro país','Another country','Otro país'],search:['Filtrar fontes por nome ou órgão','Filter sources by name or organisation','Filtrar fuentes por nombre u organismo'],all:['Tudo','All','Todo'],medicines:['Medicamentos','Medicines','Medicamentos'],guidelines:['Diretrizes','Guidelines','Guías'],vaccines:['Vacinação','Vaccination','Vacunación'],coding:['Códigos SUS','SUS codes','Códigos SUS'],filters:['Tipo de referência','Reference type','Tipo de referencia'],regional:['Referências do país','Country references','Referencias del país'],international:['Referência internacional','International reference','Referencia internacional'],choose:['Escolha um país acima para ver as fontes locais.','Choose a country above to see local sources.','Elige un país arriba para ver fuentes locales.'],missing:['Ainda não temos fontes locais cadastradas para este país. Não substituímos por fontes de outro país.','Local sources for this country are not listed yet. We do not substitute another country’s sources.','Aún no tenemos fuentes locales para este país. No las sustituimos por fuentes de otro país.'],empty:['Nenhuma fonte cadastrada para este filtro.','No listed sources match this filter.','Ninguna fuente registrada coincide con este filtro.'],reset:['Limpar filtros','Clear filters','Limpiar filtros'],open:['Abrir fonte','Open source','Abrir fuente'],newTab:['abre em outra aba','opens in a new tab','abre en otra pestaña'],language:['Idioma da fonte','Source language','Idioma de la fuente'],reviewed:['Seleção revisada em','Directory reviewed on','Selección revisada el'],note:['Você abre o site original. Confira a versão e a aplicabilidade local do documento. Estes links não são referências verificadas de uma resposta do chat.','You open the original website. Check the document’s version and local applicability. These links are not verified citations for a chat answer.','Se abre el sitio original. Revisa la versión y la aplicación local. Estos enlaces no son citas verificadas de una respuesta del chat.'],independent:['Esta escolha não altera o país do chat.','This selection does not change the chat country.','Esta selección no cambia el país del chat.'],filterNote:['Filtro só nesta lista; não pesquisa dentro dos documentos.','Filters this list only, not document contents.','Filtra solo esta lista, no el contenido de los documentos.'],link:['Consultar fontes oficiais','Consult official sources','Consultar fuentes oficiales']};
export function OfficialSourcesLink(){const{locale}=useI18n();return <a className="official-entry" href="#fontes-oficiais"><Globe2 size={17}/>{sourceText(copy.link,locale)}<ArrowUpRight size={16}/></a>;}
export default function OfficialSources(){
 const{locale,country}=useI18n();const [region,setRegion]=useState(country),[category,setCategory]=useState('all'),[query,setQuery]=useState('');
 const tr=key=>sourceText(copy[key],locale),names=new Intl.DisplayNames([locale],{type:'region'});
 const result=sourceDirectory({region,category,query,locale});
 function cards(items){return <div className="official-cards">{items.map(s=><article key={s.id}><div className="official-meta"><span>{tr(s.category)}</span><span>{s.region==='global'?'WHO':names.of(s.region)}</span></div><h3>{s.name}</h3><p className="official-owner">{s.owner}</p><p>{sourceText(s.description,locale)}</p><div className="official-language">{tr('language')}: {s.language==='English / outros'?(locale==='en'?'English / others':locale==='es'?'English / otros':s.language):s.language}</div><a href={s.url} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer" aria-label={`${tr('open')}: ${s.name} (${tr('newTab')})`}>{tr('open')}<ArrowUpRight size={17}/></a></article>)}</div>;}
 return <section className="doctor-official"><header><Globe2 size={24}/><h1>{tr('title')}</h1><p>{tr('intro')}</p></header><div className="official-controls"><label>{tr('country')}<select value={region} onChange={e=>setRegion(e.target.value)}>{countries.map(c=><option key={c} value={c}>{c==='global'?tr('pick'):c==='other'?tr('other'):names.of(c)}</option>)}</select><small>{tr('independent')}</small></label><label>{tr('search')}<div className="official-search"><Search size={18}/><input type="search" value={query} onChange={e=>setQuery(e.target.value)} maxLength={120}/></div><small>{tr('filterNote')}</small></label></div><div className="official-filters" role="group" aria-label={tr('filters')}>{sourceCategories.map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{tr(c)}</button>)}</div><section aria-label={tr('regional')}><h2>{tr('regional')}{region!=='global'&&region!=='other'?` · ${names.of(region)}`:''}</h2>{result.regional.length?cards(result.regional):<p className="official-empty" role="status">{region==='global'?tr('choose'):!result.covered?tr('missing'):tr('empty')}</p>}{(query||category!=='all')&&<button className="official-reset" onClick={()=>{setQuery('');setCategory('all');}}>{tr('reset')}</button>}</section>{result.international.length>0&&<section aria-label={tr('international')}><h2>{tr('international')}</h2>{cards(result.international)}</section>}<footer><p>{tr('note')}</p><small>{tr('reviewed')} {new Date(sourceReviewedOn+'T12:00:00').toLocaleDateString(locale)}.</small></footer></section>;
}
