import React,{useState,useEffect,useRef} from 'react';
import {Copy,Download} from 'lucide-react';
import {exportReferences,selectedReferences} from '../../shared/reference-export.mjs';
export default function ReferenceExport({items,selected,onSelect,locale,retrievedAt,panelRef}) {
 const [message,setMessage]=useState(null); const [preview,setPreview]=useState(false);
 const i=locale==='en'?1:locale==='es'?2:0;
 const strings={title:['Sua seleção','Your selection','Tu selección'],hint:['Selecione artigos para copiar ou baixar as referências. A seleção vale para esta busca.','Select articles to copy or download references. Selection applies to this search.','Selecciona artículos para copiar o descargar referencias. La selección corresponde a esta búsqueda.'],all:['Selecionar todos','Select all','Seleccionar todos'],clear:['Limpar seleção','Clear selection','Borrar selección'],copy:['Copiar lista','Copy list','Copiar lista'],download:['Baixar .txt','Download .txt','Descargar .txt'],preview:['Ver texto da lista','Preview list text','Ver texto de la lista'],note:['Formato simples, sem resumos. Confira os dados na fonte antes de citar.','Simple format, without abstracts. Check source metadata before citing.','Formato simple, sin resúmenes. Revisa los datos en la fuente antes de citar.'],copied:['Lista copiada.','List copied.','Lista copiada.'],failed:['Não foi possível copiar. Selecione o texto abaixo e copie manualmente.','Could not copy. Select the text below and copy manually.','No se pudo copiar. Selecciona el texto de abajo y cópialo manualmente.'],downloaded:['Arquivo preparado. Confira os downloads do navegador.','File prepared. Check your browser downloads.','Archivo preparado. Revisa las descargas del navegador.'],downloadFailed:['Não foi possível baixar. Você pode copiar o texto abaixo.','Could not download. You can copy the text below.','No se pudo descargar. Puedes copiar el texto de abajo.']};
 const tr=k=>strings[k][i]; const chosen=selectedReferences(items,selected); const output=exportReferences(chosen,locale,retrievedAt);
 const current=useRef(output);current.current=output;
 useEffect(()=>{setMessage(null);},[output]);
 useEffect(()=>()=>{current.current=null;},[]);
 async function copy(){const snapshot=output;try{await navigator.clipboard.writeText(snapshot);if(current.current===snapshot)setMessage('copied');}catch{if(current.current===snapshot){setMessage('failed');setPreview(true);}}}
 function download(){let url;try{url=URL.createObjectURL(new Blob([output],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='2doctor-references.txt';document.body.append(link);link.click();link.remove();setMessage('downloaded');}catch{setMessage('downloadFailed');setPreview(true);}finally{if(url)setTimeout(()=>URL.revokeObjectURL(url),1000);}}
 return <aside ref={panelRef} tabIndex={-1} className="research-export" aria-label={tr('title')}><div className="research-export-heading"><h2>{tr('title')} <span>{chosen.length}/{items.length}</span></h2><button onClick={()=>onSelect(chosen.length===items.length?[]:items.map(item=>item.id))}>{tr(chosen.length===items.length?'clear':'all')}</button></div><p>{tr('hint')}</p><div className="research-export-actions"><button disabled={!chosen.length} onClick={copy}><Copy size={16}/>{tr('copy')}</button><button disabled={!chosen.length} onClick={download}><Download size={16}/>{tr('download')}</button></div>{chosen.length>0&&<details open={preview} onToggle={e=>setPreview(e.currentTarget.open)}><summary>{tr('preview')}</summary><p>{tr('note')}</p><textarea readOnly aria-label={tr('preview')} value={output} rows={9}/></details>}{message&&<p role="status">{tr(message)}</p>}</aside>;
}
