import React,{useReducer,useState,useRef,useLayoutEffect} from 'react';
import {FilePenLine,ArrowRight,Copy,Check,RotateCcw,BookOpen} from 'lucide-react';
import {useI18n} from './I18n';
import {createDemo,demoReducer,demoCases,missingText,exportDemo,isEdited,supportedLocale} from '../../shared/scribe-demo.mjs';
import './scribe.css';
const words={
 'pt-BR':{
 badge:'PROTÓTIPO · EXEMPLOS FICTÍCIOS',title:'Scribe',intro:'Do relato à nota organizada.',notice:'Experimente com os relatos abaixo. A organização é demonstrativa, sem IA ou gravação ativa.',choose:'Escolha um exemplo',source:'Relato original',note:'Nota SOAP',organize:'Organizar exemplo',empty:'Veja o relato ganhar estrutura.',emptyBody:'Cada seção manterá os trechos informados. O que faltar continuará em branco.',hint:'S · História relatada   O · Achados observados   A · Avaliação   P · Plano',origin:'Ver trecho de origem',edited:'Editado por você',original:'Texto do exemplo',absent:'Sem trecho de origem',editedHint:'A origem abaixo corresponde ao exemplo inicial. Confira suas alterações.',placeholder:'Não informado no relato.',review:'Revisei o exemplo e minhas alterações.',copy:'Copiar exemplo revisado',copied:'Exemplo copiado.',fallback:'Selecione o texto abaixo para copiar.',reset:'Recomeçar',discard:'Substituir suas alterações por outro exemplo?',yes:'Substituir',cancel:'Manter alterações',temporary:'Use apenas texto fictício. Este rascunho não é salvo; ao sair desta tela, suas alterações serão descartadas.',lang:'O exemplo mantém o idioma em que foi aberto.',reload:'Carregar exemplo no idioma atual',export:'Texto para copiar',reference:'Sobre o formato SOAP',limit:'Esta demonstração não transcreve consultas nem gera recomendações clínicas.',step1:'1 · Relato',step2:'2 · Nota e revisão',characters:'caracteres'},
 en:{badge:'PROTOTYPE · FICTIONAL EXAMPLES',title:'Scribe',intro:'From an account to a structured note.',notice:'Try the examples below. This is a demonstration, with no active AI or recording.',choose:'Choose an example',source:'Original account',note:'SOAP note',organize:'Organise example',empty:'Give the account a structure.',emptyBody:'Each section will retain the supplied passages. Missing information stays blank.',hint:'S · Reported history   O · Observed findings   A · Assessment   P · Plan',origin:'View source passage',edited:'Edited by you',original:'Example text',absent:'No source passage',editedHint:'The source below belongs to the initial example. Check your changes.',placeholder:'Not reported in the account.',review:'I reviewed the example and my changes.',copy:'Copy reviewed example',copied:'Example copied.',fallback:'Select the text below to copy.',reset:'Start over',discard:'Replace your changes with another example?',yes:'Replace',cancel:'Keep changes',temporary:'Use fictional text only. This draft is not saved; leaving this screen discards your changes.',lang:'The example keeps the language in which it was opened.',reload:'Load example in the current language',export:'Text to copy',reference:'About the SOAP format',limit:'This demonstration does not transcribe consultations or generate clinical recommendations.',step1:'1 · Account',step2:'2 · Note and review',characters:'characters'},
 es:{badge:'PROTOTIPO · EJEMPLOS FICTICIOS',title:'Scribe',intro:'Del relato a la nota organizada.',notice:'Prueba los ejemplos de abajo. Es una demostración, sin IA ni grabación activa.',choose:'Elige un ejemplo',source:'Relato original',note:'Nota SOAP',organize:'Organizar ejemplo',empty:'Dale estructura al relato.',emptyBody:'Cada sección conservará los fragmentos proporcionados. Lo que falte quedará en blanco.',hint:'S · Historia referida   O · Hallazgos observados   A · Evaluación   P · Plan',origin:'Ver fragmento de origen',edited:'Editado por ti',original:'Texto del ejemplo',absent:'Sin fragmento de origen',editedHint:'El origen de abajo corresponde al ejemplo inicial. Revisa tus cambios.',placeholder:'No informado en el relato.',review:'Revisé el ejemplo y mis cambios.',copy:'Copiar ejemplo revisado',copied:'Ejemplo copiado.',fallback:'Selecciona el texto de abajo para copiar.',reset:'Empezar de nuevo',discard:'¿Reemplazar tus cambios por otro ejemplo?',yes:'Reemplazar',cancel:'Conservar cambios',temporary:'Usa solo texto ficticio. Este borrador no se guarda; al salir de esta pantalla se descartan los cambios.',lang:'El ejemplo mantiene el idioma en el que se abrió.',reload:'Cargar ejemplo en el idioma actual',export:'Texto para copiar',reference:'Sobre el formato SOAP',limit:'Esta demostración no transcribe consultas ni genera recomendaciones clínicas.',step1:'1 · Relato',step2:'2 · Nota y revisión',characters:'caracteres'},
};
const formatWords={
 'pt-BR':{choose:'Formato do exemplo',soap:'Nota SOAP',sbar:'Passagem SBAR',hint:'S · Situação   B · Contexto   A · Avaliação   R · Recomendação ou pedido',explain:'Organize a comunicação com a equipe. Os pedidos vêm do relato; o sistema não cria condutas.',reference:'Sobre o formato SBAR',discard:'Recarregar o exemplo? Suas alterações serão descartadas.'},
 en:{choose:'Example format',soap:'SOAP note',sbar:'SBAR handoff',hint:'S · Situation   B · Background   A · Assessment   R · Recommendation or request',explain:'Structure communication with the team. Requests come from the account; the system does not create a care plan.',reference:'About the SBAR format',discard:'Reload the example? Your changes will be discarded.'},
 es:{choose:'Formato del ejemplo',soap:'Nota SOAP',sbar:'Entrega SBAR',hint:'S · Situación   B · Antecedentes   A · Evaluación   R · Recomendación o solicitud',explain:'Organiza la comunicación con el equipo. Las solicitudes vienen del relato; el sistema no crea conductas.',reference:'Sobre el formato SBAR',discard:'¿Recargar el ejemplo? Tus cambios se descartarán.'},
};
function NoteField({value,...props}){
 const ref=useRef(null);
 useLayoutEffect(()=>{
  const el=ref.current;
  if(!el)return;
  const resize=()=>{el.style.height='auto';el.style.height=`${el.scrollHeight+2}px`;};
  resize();
  const observer=new ResizeObserver(()=>{if(el.clientWidth!==previousWidth){previousWidth=el.clientWidth;resize();}});
  let previousWidth=el.clientWidth;observer.observe(el);
  return ()=>observer.disconnect();
 },[value]);
 return <textarea ref={ref} rows={2} value={value} {...props}/>;
}
export default function Scribe(){
 const {locale}=useI18n(),language=supportedLocale(locale),w=words[language],f=formatWords[language];
 const [state,dispatch]=useReducer(demoReducer,null,()=>createDemo('history',language));
 const [pane,setPane]=useState('source'),[pending,setPending]=useState(null),[copied,setCopied]=useState(false),[copyError,setCopyError]=useState(false),[exportVisible,setExportVisible]=useState(false);
 const clearCopy=()=>{setCopied(false);setCopyError(false);setExportVisible(false);};
 function load(id,format=state.format){const request={id,format};if(isEdited(state)){setPending(request);return;}replace(request);}
 function replace({id,format}){dispatch({type:'load',id,format,locale:language});setPane('source');setPending(null);clearCopy();}
 async function copy(){const text=exportDemo(state);if(!text)return;setExportVisible(true);try{await navigator.clipboard.writeText(text);setCopied(true);setCopyError(false);}catch{setCopyError(true);}}
 return <section className="doctor-scribe"><header className="scribe-heading"><span className="scribe-badge"><FilePenLine size={15}/>{w.badge}</span><h1>{w.title}<span>{w.intro}</span></h1><p>{w.notice}</p></header>
 <div className="scribe-format" role="group" aria-label={f.choose}>{['SOAP','SBAR'].map(format=><button key={format} aria-pressed={state.format===format} onClick={()=>{if(state.format!==format)load(state.id,format);}}>{format==='SOAP'?f.soap:f.sbar}</button>)}</div>
 {state.format==='SBAR'&&<p className="scribe-format-help">{f.explain}</p>}
 <div className="scribe-toolbar"><label>{w.choose}<select value={state.id} onChange={e=>load(e.target.value)}>{demoCases.map(c=><option key={c.id} value={c.id}>{c.title[language]}</option>)}</select></label><button onClick={()=>load(state.id)}><RotateCcw size={16}/>{w.reset}</button></div>
 {pending&&<div className="scribe-confirm" role="alert"><strong>{f.discard}</strong><div><button onClick={()=>replace(pending)}>{w.yes}</button><button onClick={()=>setPending(null)}>{w.cancel}</button></div></div>}
 {state.locale!==language&&<div className="scribe-language-note"><p>{w.lang}</p><button onClick={()=>load(state.id)}>{w.reload}</button></div>}
 <div className="scribe-mobile-switch" role="group" aria-label={w.title}><button aria-pressed={pane==='source'} onClick={()=>setPane('source')}>{w.step1}</button><button aria-pressed={pane==='note'} onClick={()=>setPane('note')}>{w.step2}</button></div>
 <div className={`scribe-workspace scribe-show-${pane}`}>
 <article className="scribe-source" aria-label={w.source}><div className="scribe-card-heading"><BookOpen size={19}/><h2>{w.source}</h2></div><div lang={state.locale}>{state.source.map((s,index)=><div className="scribe-passage" key={s.id}><span>{String(index+1).padStart(2,'0')}</span><p>{s.text}</p></div>)}</div><button className="scribe-primary" onClick={()=>{dispatch({type:'organize'});setPane('note');clearCopy();}} disabled={state.organized}>{w.organize}<ArrowRight size={17}/></button><p className="scribe-fine">{w.limit}</p></article>
 <article className="scribe-note" aria-label={state.format==='SBAR'?f.sbar:w.note}><div className="scribe-card-heading"><FilePenLine size={19}/><h2>{state.format==='SBAR'?f.sbar:w.note}</h2><span>{state.format}</span></div>{!state.organized?<div className="scribe-empty"><FilePenLine size={36}/><h3>{w.empty}</h3><p>{w.emptyBody}</p><small>{state.format==='SBAR'?f.hint:w.hint}</small></div>:<>
 <div lang={state.locale}>{state.sections.map((s,index)=>{const edited=s.text!==state.original[s.key];return <section className="scribe-field" key={s.key}><label htmlFor={`scribe-${s.key}`}><span>{state.format[index]}</span>{s.label}</label><small className={edited?'scribe-edited':''}>{edited?w.edited:s.sourceIds.length?w.original:w.absent}</small><NoteField id={`scribe-${s.key}`} maxLength={6000} placeholder={missingText[state.locale]} value={s.text} onChange={e=>{dispatch({type:'edit',key:s.key,text:e.target.value});clearCopy();}}/>{s.text.length>5700&&<small>{s.text.length}/6000 {w.characters}</small>}{s.sourceIds.length>0&&<details><summary>{w.origin}</summary>{edited&&<p className="scribe-fine">{w.editedHint}</p>}{s.sourceIds.map(id=><blockquote key={id}>{state.source.find(p=>p.id===id).text}</blockquote>)}</details>}</section>;})}</div>
 <footer className="scribe-review"><p className="scribe-fine">{w.temporary}</p><label><input type="checkbox" checked={state.reviewed} onChange={e=>{dispatch({type:'review',value:e.target.checked});clearCopy();}}/>{w.review}</label><button className="scribe-primary" disabled={!state.reviewed} onClick={copy}>{copied?<Check size={17}/>:<Copy size={17}/>} {w.copy}</button><p role="status">{copyError?w.fallback:copied?w.copied:''}</p>{exportVisible&&state.reviewed&&<label className="scribe-export">{w.export}<textarea readOnly rows={8} value={exportDemo(state)} onFocus={e=>e.target.select()}/></label>}</footer></>}
 </article></div><a className="scribe-reference" href={state.format==='SBAR'?'https://www.ahrq.gov/teamstepps-program/curriculum/communication/tools/sbar.html':'https://health.maryland.gov/bacc/Pages/Professional-Documentation-(SOAP-Notes).aspx'} target="_blank" rel="noopener noreferrer">{state.format==='SBAR'?f.reference:w.reference} ↗</a></section>;
}
