import React,{useState} from 'react';
import {Clock3,Copy,RotateCcw} from 'lucide-react';
import {useI18n} from './I18n';
import {divideShift,clockLabel} from '../../shared/shift-divider.mjs';
import './shift-divider.css';
const words={
 'pt-BR':{title:'Dividir plantão',intro:'Distribua um período em partes iguais.',start:'Início',end:'Fim',people:'Pessoas',calculate:'Dividir horários',clear:'Limpar',person:'Pessoa',duration:'Duração',hour:'h',minute:'min',next:'dia seguinte',total:'Período total',copy:'Copiar divisão',copied:'Divisão copiada.',fallback:'Selecione o texto abaixo para copiar.',result:'Divisão dos horários',note:'Horários locais. Se o fim for anterior ao início, ele será no dia seguinte. Em mudanças de horário de verão, confira os intervalos.',time:'Preencha os dois horários.',equal:'Início e fim devem ser diferentes.',short:'O período precisa ter ao menos um minuto por pessoa.',invalid:'Escolha de 1 a 12 pessoas.',export:'Texto para copiar'},
 en:{title:'Split a shift',intro:'Divide a time period into equal parts.',start:'Start',end:'End',people:'People',calculate:'Split times',clear:'Clear',person:'Person',duration:'Duration',hour:'h',minute:'min',next:'next day',total:'Total period',copy:'Copy schedule',copied:'Schedule copied.',fallback:'Select the text below to copy.',result:'Time allocation',note:'Local clock times. An end earlier than the start means the next day. Check intervals when daylight saving time changes.',time:'Enter both times.',equal:'Start and end must differ.',short:'Allow at least one minute per person.',invalid:'Choose 1 to 12 people.',export:'Text to copy'},
 es:{title:'Dividir guardia',intro:'Distribuye un período en partes iguales.',start:'Inicio',end:'Fin',people:'Personas',calculate:'Dividir horarios',clear:'Limpiar',person:'Persona',duration:'Duración',hour:'h',minute:'min',next:'día siguiente',total:'Período total',copy:'Copiar distribución',copied:'Distribución copiada.',fallback:'Selecciona el texto de abajo para copiar.',result:'Distribución de horarios',note:'Horarios locales. Si el fin es anterior al inicio, será al día siguiente. Revisa los intervalos cuando cambie el horario de verano.',time:'Completa ambos horarios.',equal:'Inicio y fin deben ser diferentes.',short:'El período debe tener al menos un minuto por persona.',invalid:'Elige de 1 a 12 personas.',export:'Texto para copiar'},
};
export default function ShiftDivider(){
 const {locale}=useI18n(),w=words[locale]||words['pt-BR'];
 const [form,setForm]=useState({start:'19:00',end:'07:00',people:'3'}),[result,setResult]=useState(null),[copy,setCopy]=useState('');
 const duration=n=>`${Math.floor(n/60)} ${w.hour} ${n%60} ${w.minute}`;
 const time=n=>`${clockLabel(n)}${n>=1440?' · '+w.next:''}`;
 const update=(key,value)=>{setForm(v=>({...v,[key]:value}));setResult(null);setCopy('');};
 const text=result?.periods?[w.title,`${w.total}: ${duration(result.total)}`,...result.periods.map(p=>`${w.person} ${p.position}: ${time(p.start)} – ${time(p.end)} (${duration(p.duration)})`)].join('\n'):'';
 async function copySchedule(){try{await navigator.clipboard.writeText(text);setCopy('ok');}catch{setCopy('fallback');}}
 return <section className="doctor-shift"><header><Clock3 size={24}/><h1>{w.title}</h1><p>{w.intro}</p></header><form onSubmit={e=>{e.preventDefault();setResult(divideShift(form));setCopy('');}}><div className="shift-inputs"><label>{w.start}<input type="time" value={form.start} onChange={e=>update('start',e.target.value)}/></label><label>{w.end}<input type="time" value={form.end} onChange={e=>update('end',e.target.value)}/></label><label>{w.people}<select value={form.people} onChange={e=>update('people',e.target.value)}>{Array.from({length:12},(_,i)=><option key={i+1}>{i+1}</option>)}</select></label></div><div className="shift-actions"><button className="shift-primary" type="submit">{w.calculate}</button><button type="button" onClick={()=>{setForm({start:'',end:'',people:'3'});setResult(null);setCopy('');}}><RotateCcw size={16}/>{w.clear}</button></div><p className="shift-note">{w.note}</p></form>{result?.error&&<p role="alert" className="shift-error">{({time:w.time,equal:w.equal,people:w.invalid,short:w.short})[result.error]}</p>}{result?.periods&&<section className="shift-result" aria-label={w.result}><div className="shift-total"><span>{w.total}</span><strong>{duration(result.total)}</strong></div><ol>{result.periods.map(p=><li key={p.position}><span className="shift-number">{String(p.position).padStart(2,'0')}</span><div><h2>{w.person} {p.position}</h2><p><time>{time(p.start)}</time><span aria-hidden="true"> → </span><time>{time(p.end)}</time></p><small>{w.duration}: {duration(p.duration)}</small></div></li>)}</ol><button className="shift-primary" onClick={copySchedule}><Copy size={16}/>{w.copy}</button><p role="status">{copy==='ok'?w.copied:copy?w.fallback:''}</p>{copy&&<label className="shift-export">{w.export}<textarea readOnly rows={6} value={text} onFocus={e=>e.target.select()}/></label>}</section>}</section>;
}
