import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowDownToLine,ArrowLeft,ArrowRight,ArrowUpRight,Bookmark,BookOpen,Check,CheckCheck,ChevronLeft,ChevronRight,ClipboardList,FileUp,Filter,GraduationCap,Search,Target,X} from 'lucide-react';
import {createQuestionModel,emptyFilters,questions as legacyQuestions,type Question,type QuestionId,type Filters,type Progress,type Session} from './model';
import {cleanLedger,emptyLedger,track,record,firstAttempts,metrics,reviewIds} from './attempts.mjs';
import {createLocalPersistence,browserStorage,parseRecovery,holdWriter,hasPendingSnapshots} from './persistence.mjs';
import {assertCatalog} from './editorial.mjs';
import ChallengeIllustration from '../doctor/ChallengeIllustration';
import './questions.css';
import {useWorkspaceHeight} from '../academic/useWorkspaceHeight';
import {useI18n} from '../doctor/I18n';

function readStored(key:string) {try{return JSON.parse(localStorage.getItem(key)||'null');}catch{return null;}}
function QuestionBankView({storageKey,standalone=false,catalog, catalogId,editorialPreview=false}:{storageKey:string;standalone?:boolean;catalog?:Question[];catalogId?:string;editorialPreview?:boolean}) {
 const enhanced=!!catalog;
 if(enhanced&&!new RegExp(`^2doctor:qbank:${catalogId}:(guest|[a-f0-9]{64})$`).test(storageKey))throw Error('Catalog requires isolated account storage');
 const {questions,byId,areas,areaOf,cleanBookmarks,cleanProgress,cleanSession,filterQuestions,parseBackup,sessionResult}=useMemo(()=>createQuestionModel(catalog?assertCatalog(catalog,{preview:editorialPreview&&import.meta.env.DEV}):legacyQuestions),[catalog,editorialPreview]);
 const banks=[...new Set(questions.map(q=>q.banca))];
 const persistence=useRef(enhanced?createLocalPersistence(browserStorage(),storageKey):null);
 const readPart=(part,suffix)=>enhanced?persistence.current.read(part):readStored(storageKey+suffix);
 function persist(patch){if(enhanced)setSaveError(!persistence.current.save(patch));}

 const [ledger,setLedger]=useState(()=>cleanLedger(readPart('ledger',':attempts'),catalogId,questions));
 const ledgerRef=useRef(ledger);
 const attemptId=useRef(readPart('attemptId',':attemptId')||crypto.randomUUID());
 function renewAttempt(){attemptId.current=crypto.randomUUID();if(enhanced)persist({attemptId:attemptId.current});}
 function updateLedger(next){ledgerRef.current=next;setLedger(next);persist({ledger:next});}
 function submitAttempt(q,answer,mode,id){const next=record(ledgerRef.current,q,{id,answer,mode});updateLedger(next);const first=firstAttempts(next).find(a=>a.questionId===q.n);if(first)setProgress(p=>({...p,[q.n]:{answer:first.answer,correct:first.correct}}));}
 const stats=metrics(ledger);
 const versionStamp=questions.map(q=>`${q.n}@${q.version||'legacy'}`).join('|');
 const rawView=enhanced?readPart('view',':view'):null;
 const storedView=rawView?.versionStamp===versionStamp?rawView:null;
 const {t,locale}=useI18n();
 const Main=standalone?'main':'div';
 const workspace=useWorkspaceHeight();
 const listRef=useRef<HTMLDivElement>(null);
 const [pageSize,setPageSize]=useState(6);
 const [progress,setProgress]=useState<Progress>(()=>enhanced?Object.fromEntries(firstAttempts(ledger).map(a=>[a.questionId,{answer:a.answer,correct:a.correct}])):cleanProgress(readStored(storageKey)));
 const [bookmarks,setBookmarks]=useState<QuestionId[]>(()=>cleanBookmarks(readPart('bookmarks',':bookmarks')));
 const [session,setSession]=useState<Session|null>(()=>cleanSession(readPart('session',':session')));
 const [filters,setFilters]=useState<Filters>(emptyFilters);
 const [page,setPage]=useState(0);
 const [mode,setMode]=useState<'banks'|'library'|'study'|'exam'>(()=>storedView?.mode==='study'&&Array.isArray(storedView.queue)&&storedView.queue.length&&storedView.queue.every(id=>byId.has(id))?'study':storedView?.mode==='exam'&&session?'exam':'banks');
 const [queue,setQueue]=useState<QuestionId[]>(()=>storedView?.queue?.filter(id=>byId.has(id))||[]);
 const [index,setIndex]=useState(()=>Math.max(0,Math.min(storedView?.index||0,(storedView?.queue?.length||1)-1)));
 const [picked,setPicked]=useState(()=>storedView?.picked||'');
 const [confirmed,setConfirmed]=useState(()=>storedView?.confirmed||'');
 const [examSize,setExamSize]=useState(Math.min(20,questions.length));
 const [confirmFinish,setConfirmFinish]=useState(false);
 const [notice,setNotice]=useState('');
 const [bankSearch,setBankSearch]=useState('');
 const [saveError,setSaveError]=useState(()=>enhanced&&persistence.current.isDirty());
 const recoveryRef=useRef<HTMLInputElement>(null);
 const importRef=useRef<HTMLInputElement>(null);
 const heading=useRef<HTMLHeadingElement>(null);
 const filtered=useMemo(()=>filters.status==='assisted'?filterQuestions({...filters,status:''},progress,bookmarks).filter(q=>reviewIds(ledger,'assisted').includes(q.n)):filterQuestions(filters,progress,bookmarks),[filters,progress,bookmarks,ledger]);
 const totalDone=Object.keys(progress).length, correct=Object.values(progress).filter(p=>p.correct).length, review=totalDone-correct;
 const visibleIds=mode==='exam'?session?.ids||[]:queue;
 const position=mode==='exam'?session?.index||0:index;
 const current=byId.get(visibleIds[position]);
 const answer=mode==='exam'?session?.answers[current?.n||0]||'':confirmed;
 const revealed=mode==='exam'?!!session?.finished:!!confirmed;
 const outcome=mode==='exam'&&session?.finished?sessionResult(session):null;
 useEffect(()=>{
   if(enhanced){persist({progress,bookmarks,session});return;}
   try {localStorage.setItem(storageKey,JSON.stringify(progress));localStorage.setItem(storageKey+':bookmarks',JSON.stringify(bookmarks));localStorage.setItem(storageKey+':session',JSON.stringify(session));setSaveError(false);}catch{setSaveError(true);}
 },[storageKey,progress,bookmarks,session]);
 useEffect(()=>{if(enhanced)persist({view:{mode,queue,index,picked,confirmed,versionStamp}})},[enhanced,storageKey,mode,queue,index,picked,confirmed]);
 useEffect(()=>{
  if(!enhanced||!current||revealed||!['study','exam'].includes(mode))return;
  let last=performance.now();
  const timer=setInterval(()=>{const now=performance.now(),elapsed=now-last;last=now;if(document.visibilityState==='visible'&&document.hasFocus())updateLedger(track(ledgerRef.current,current,{elapsed,mode}));},1000);
  return()=>clearInterval(timer);
 },[enhanced,current,mode,revealed]);
 useEffect(()=>{setPage(0);},[filters]);
 useEffect(()=>{setPage(p=>Math.min(p,Math.max(0,Math.ceil(filtered.length/pageSize)-1)));},[filtered.length,pageSize]);
 useEffect(()=>{
  const el=listRef.current;if(!el||mode!=='library')return;
  const observer=new ResizeObserver(([entry])=>{setPageSize(window.innerWidth>900?Math.max(2,Math.min(12,Math.floor(entry.contentRect.height/68))):6);});
  observer.observe(el);return()=>observer.disconnect();
 },[mode]);
 function focusQuestion(){requestAnimationFrame(()=>{heading.current?.focus({preventScroll:true});document.querySelectorAll('.qb-question-reading,.qb-answer-reading').forEach(el=>el.scrollTo({top:0}));if(window.innerWidth<=900)heading.current?.scrollIntoView({block:'start',behavior:'smooth'});});}
 function study(ids:QuestionId[],at=0) {renewAttempt();setQueue(ids);setIndex(at);setMode('study');const previous=progress[ids[at]]?.answer||'';setPicked(previous);setConfirmed(previous);focusQuestion();}
 function navigate(to:number) {renewAttempt();setPicked('');if(mode==='exam')setSession(s=>s?{...s,index:to}:s);else{setIndex(to);const previous=progress[queue[to]]?.answer||'';setPicked(previous);setConfirmed(previous);}focusQuestion();}
 function choose(value:string){if(revealed)return;if(mode==='exam'&&current)setSession(s=>s?{...s,answers:{...s.answers,[current.n]:value}}:s);else setPicked(value);}
 function confirm(){if(!current||!picked||confirmed)return;setConfirmed(picked);if(enhanced)submitAttempt(current,picked,'study',attemptId.current);else setProgress(p=>({...p,[current.n]:{answer:picked,correct:picked===current.gabarito}}));requestAnimationFrame(()=>workspace.current?.querySelector('.qb-explanation')?.scrollIntoView({block:'nearest',behavior:'smooth'}));}
 function startExam(){if(enhanced)updateLedger({...ledgerRef.current,drafts:Object.fromEntries(Object.entries(ledgerRef.current.drafts).filter(([key])=>!key.startsWith('exam:')))});const ids=filtered.slice(0,examSize).map(q=>q.n);if(!ids.length)return;setSession({ids,index:0,answers:{},finished:false,runId:crypto.randomUUID(),versions:Object.fromEntries(ids.map(id=>[id,byId.get(id)?.version]))});setMode('exam');setPicked('');setConfirmFinish(false);focusQuestion();}
 function finish(){if(!session||session.finished)return;if(enhanced){for(const id of session.ids){const q=byId.get(id);if(q&&session.answers[id])submitAttempt(q,session.answers[id],'exam',`${session.runId}:${id}`);}}const next=cleanProgress(Object.fromEntries(Object.entries(session.answers).map(([id,answer])=>[id,{answer}])));if(!enhanced)setProgress(p=>({...p,...next}));setSession({...session,finished:true});setConfirmFinish(false);focusQuestion();}
 function toggleBookmark(id:QuestionId){setBookmarks(b=>b.includes(id)?b.filter(v=>v!==id):[...b,id]);}
 function exportProgress(){const blob=new Blob([JSON.stringify({format:'vytal-questions',version:1,progress,bookmarks},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='wmed-meu-progresso.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Arquivo de progresso preparado. Guarde para continuar em outro navegador.');}
 async function importProgress(file?:File){if(!file)return;try{if(file.size>2_000_000)throw Error('Escolha um arquivo de progresso de até 2 MB.');const data=parseBackup(await file.text());setProgress(p=>({...data.progress,...p}));setBookmarks(b=>[...new Set([...b,...data.bookmarks])]);setNotice('Progresso importado. Suas respostas atuais foram preservadas.');}catch(e){setNotice(e instanceof Error?e.message:'Não foi possível importar esse arquivo.');}if(importRef.current)importRef.current.value='';}

 function exportRecovery(){const blob=new Blob([persistence.current.recovery()],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='2doctor-qbank-recovery.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function restoreRecovery(file?:File){if(!file)return;try{const data=parseRecovery(await file.text(),storageKey),nextLedger=cleanLedger(data.ledger,catalogId,questions),nextBookmarks=cleanBookmarks(data.bookmarks),nextSession=cleanSession(data.session);const nextProgress=Object.fromEntries(firstAttempts(nextLedger).map(a=>[a.questionId,{answer:a.answer,correct:a.correct}]));const view=data.view?.versionStamp===versionStamp?data.view:null;const nextId=typeof data.attemptId==='string'?data.attemptId:crypto.randomUUID();ledgerRef.current=nextLedger;setLedger(nextLedger);setProgress(nextProgress);setBookmarks(nextBookmarks);setSession(nextSession);attemptId.current=nextId;setQueue(view?.queue?.filter(id=>byId.has(id))||[]);setIndex(view?.index||0);setPicked(view?.picked||'');setConfirmed(view?.confirmed||'');setMode(view?.mode==='exam'&&nextSession?'exam':view?.mode==='study'?'study':'banks');setSaveError(!persistence.current.replace({ledger:nextLedger,progress:nextProgress,bookmarks:nextBookmarks,session:nextSession,view,attemptId:nextId}));setNotice('Recovery loaded for this account and catalog.');}catch(e){setNotice(e instanceof Error?e.message:'Recovery could not be loaded.');}if(recoveryRef.current)recoveryRef.current.value='';}
 function resetFilters(){setFilters({...emptyFilters,bank:filters.bank});setPage(0);}
 return <div ref={workspace} className={'qb-root qb-workspace '+(standalone?'qb-standalone':'')+' qb-mode-'+mode}>
 {standalone&&<header className="qb-public-nav"><a className="qb-brand" href="https://www.vytalsaude.com.br/"><img src="/bancodequestoes/vytal-logo.png" alt="Vytal"/><span>{t('ACADÊMICO')}</span></a><span className="qb-nav-label">{t('UM ESPAÇO PARA APRENDER')}</span><a className="qb-button" href="https://app.vytalsaude.com.br/estudante/questoes">{t('Entrar no Acadêmico')} <ArrowUpRight size={17}/></a></header>}
 <Main className="qb-main">
 {enhanced&&<><p className="qb-notice">{editorialPreview?'Local editorial preview — pending review. Do not publish.':'Original learning catalog'}</p><p role="status" className="qb-notice">First attempts: {stats.answered} · Correct without hint: {stats.unassisted} · Correct with hint: {stats.assistedCorrect} · Used hint: {stats.assisted} · Wrong: {stats.wrong} · Active time: {Math.round(stats.activeMs/1000)}s</p><button className="qb-button" disabled={!stats.assisted} onClick={()=>{setFilters({...emptyFilters,status:'assisted'});setMode('library')}}>Review assisted answers</button></>}

 <div className="qb-page-title"><div><span className="qb-eyebrow">{questions.length} {t('QUESTÕES')} · {banks.length} {t('PROVAS')}</span><h1>{t('Banco de questões')}<span>.</span></h1></div><div className="qb-backups" hidden={enhanced}><button onClick={exportProgress}><ArrowDownToLine size={16}/>{t('Salvar progresso')}</button><button onClick={()=>importRef.current?.click()}><FileUp size={16}/>{t('Importar')}</button><input ref={importRef} type="file" accept=".json,application/json" hidden onChange={e=>void importProgress(e.target.files?.[0])}/></div></div>
 
 {enhanced&&<div className="qb-backups"><button onClick={exportRecovery}>Download recovery</button><button onClick={()=>recoveryRef.current?.click()}>Restore recovery</button><input ref={recoveryRef} type="file" accept=".json,application/json" hidden onChange={e=>void restoreRecovery(e.target.files?.[0])}/></div>}
 {saveError&&<div role="alert" className="qb-notice">{enhanced?(persistence.current.readUnavailable()?'Saved progress could not be read. Changes are in memory only. Download recovery; after storage is available, reopen and restore it.':'Unsaved changes — answers remain in memory only. Download recovery before closing, reloading or switching account.'):t('O navegador não permitiu salvar seu progresso. Use “Salvar progresso” antes de sair.')}{enhanced&&<button onClick={()=>setSaveError(!persistence.current.retry())}>Retry saving</button>}</div>}
 {notice&&<div role="status" className="qb-notice">{t(notice)}<button aria-label={t('Fechar aviso')} onClick={()=>setNotice('')}><X size={16}/></button></div>}
 {mode==='banks'?<section className="qb-exam-library">
   <div className="qb-home-actions"><button onClick={()=>{setFilters(emptyFilters);setMode('library')}}><BookOpen size={19}/><span><strong>{t('Estudar por tema')}</strong><small>{t('Busque em todas as provas')}</small></span><ArrowRight size={16}/></button><button disabled={!review} onClick={()=>{setFilters({...emptyFilters,status:'review'});setMode('library')}}><Target size={19}/><span><strong>{t('Revisar erros')}</strong><small>{review} {t('para revisar')}</small></span><ArrowRight size={16}/></button><button disabled={!bookmarks.length} onClick={()=>{setFilters({...emptyFilters,status:'saved'});setMode('library')}}><Bookmark size={19}/><span><strong>{t('Questões salvas')}</strong><small>{bookmarks.length} {t('favoritas')}</small></span><ArrowRight size={16}/></button></div>
   <div className="qb-library-heading"><div><h2>{t('Escolha uma prova')}</h2><p>{t('Abra uma prova ou use os atalhos para estudar por tema.')}</p></div><button className="qb-button" onClick={()=>{setFilters(emptyFilters);setMode('library');}}>{t('Ver todas as questões')} <ArrowRight size={16}/></button></div>
   <label className="qb-search qb-bank-search"><Search size={17}/><input aria-label={t('Buscar prova cadastrada')} placeholder={t('Buscar uma prova')} value={bankSearch} onChange={e=>setBankSearch(e.target.value)}/></label><div className="qb-exam-catalog">{banks.filter(b=>b.toLocaleLowerCase().includes(bankSearch.toLocaleLowerCase())).map(bank=>{
     const items=questions.filter(q=>q.banca===bank);
     const done=items.filter(q=>progress[q.n]).length;
     return <button key={bank} className="qb-exam-card" onClick={()=>{setFilters({...emptyFilters,bank});setPage(0);setMode('library');}}>
       <span className="qb-exam-card-icon"><ClipboardList size={22}/><ArrowUpRight size={18}/></span>
       <strong>{bank}</strong><span>{items.length} {t('questões')} · {done} {t('respondidas')}</span>
       <span className="qb-exam-card-progress" aria-label={`${done} ${t('de')} ${items.length} ${t('respondidas')}`}><i style={{width:`${done/items.length*100}%`}}/></span>
       <small>{t('Abrir prova')} →</small>
     </button>;
   })}</div>
   {bankSearch&&!banks.some(b=>b.toLocaleLowerCase().includes(bankSearch.toLocaleLowerCase()))&&<p>{t('Nenhuma prova com esse nome.')}</p>}
   {session&&!session.finished&&<button className="qb-button" onClick={()=>{setMode('exam');focusQuestion();}}>{t('Retomar meu simulado')} <ArrowRight size={16}/></button>}
 </section>:mode==='library'?<>
 <section className="qb-quickstart"><div className="qb-quick-stats"><span><strong>{totalDone}</strong> {t('respondidas')}</span><span><strong>{review}</strong> {t('para revisar')}</span><span><strong>{bookmarks.length}</strong> {t('salvas')}</span></div><button className="qb-button qb-primary" disabled={!filtered.length} onClick={()=>study(filtered.map(q=>q.n),Math.max(0,filtered.findIndex(q=>!progress[q.n])))}>{t(totalDone?'Continuar estudando':'Começar a estudar')} <ArrowRight size={16}/></button><div className="qb-quick-sim">{session&&!session.finished?<button className="qb-button" onClick={()=>{setMode('exam');focusQuestion();}}>{t('Retomar simulado')} <ArrowRight size={16}/></button>:<><select aria-label={t('Quantidade de questões no simulado')} value={examSize} onChange={e=>setExamSize(Number(e.target.value))}>{(enhanced?[questions.length]:[10,20,40]).map(n=><option key={n} value={n}>{n} {t('questões')}</option>)}</select><button className="qb-button" disabled={!filtered.length} onClick={startExam}>{t('Iniciar simulado')}</button></>}</div></section>
 <section className="qb-library" id="qb-library"><div className="qb-library-heading"><div><button className="qb-back-to-exams" onClick={()=>setMode('banks')}>← {t('Provas cadastradas')}</button><h2>{filters.bank || t('Todas as questões')}</h2><p>{filtered.length} {t('questões')} · {t('escolha uma para responder')}</p></div><div className="qb-list-tabs" aria-label={t('Filtrar por progresso')}>{[['','Todas'],['new','Não respondidas'],['review','Revisar'],['saved','Salvas']].map(([value,label])=><button key={value} aria-pressed={filters.status===value} className={filters.status===value?'is-active':''} onClick={()=>setFilters(f=>({...f,status:value}))}>{t(label)}{value==='saved'&&<Bookmark size={13}/>}</button>)}</div></div>
 <div className="qb-filters"><select aria-label={t('Área de estudo')} value={filters.area} onChange={e=>setFilters(f=>({...f,area:e.target.value}))}><option value="">{t('Todas as áreas')}</option>{areas.map(area=><option key={area} value={area}>{t(area)}</option>)}</select><label className="qb-search"><Search size={18}/><input aria-label={t('Buscar questões')} placeholder={t('Busque um tema ou uma palavra')} value={filters.search} onChange={e=>setFilters(f=>({...f,search:e.target.value}))}/></label><select aria-label={t('Prova')} value={filters.bank} onChange={e=>setFilters(f=>({...f,bank:e.target.value}))}><option value="">{t('Todas as provas')}</option>{banks.map(bank=><option key={bank}>{bank}</option>)}</select><details className="qb-filter-more"><summary><Filter size={16}/>{t('Filtros')}</summary><div><label>{t('Dificuldade')}<select value={filters.difficulty} onChange={e=>setFilters(f=>({...f,difficulty:e.target.value}))}><option value="">{t('Todas')}</option>{['Fácil','Médio','Difícil'].map(d=><option key={d} value={d}>{t(d)}</option>)}</select></label><label><input type="checkbox" checked={filters.imageOnly} onChange={e=>setFilters(f=>({...f,imageOnly:e.target.checked}))}/>{enhanced?'With illustration':t('Com imagem descrita')}</label></div></details></div>
 {Object.values(filters).some(Boolean)&&<div className="qb-active-filters"><span>{t(filters.area||'Todas as áreas')}{filters.difficulty?' · '+t(filters.difficulty):''}{filters.imageOnly?' · '+t('Imagem descrita'):''}</span><button onClick={resetFilters}>{t('Limpar filtros')} <X size={13}/></button></div>}
 <div ref={listRef} className="qb-question-list">{filtered.slice(page*pageSize,(page+1)*pageSize).map(q=><article className="qb-row" key={q.n}><span className={'qb-row-state '+(progress[q.n]?.correct?'is-done':progress[q.n]?'is-review':'')} aria-label={t(progress[q.n]?(progress[q.n].correct?'Respondida conforme o gabarito':'Para revisar'):'Não respondida')}>{progress[q.n]?.correct?<Check size={17}/>:<BookOpen size={17}/>}</span><button className="qb-row-main" title={`${q.tema} · ${q.banca}`} onClick={()=>study(filtered.map(v=>v.n),filtered.indexOf(q))}><span>{q.banca}<span> · {t('Nº')} {q.n}</span></span><strong>{q.tema}</strong><small>{t(areaOf(q))}<i/> {t(q.dificuldade)}{q.temImagem&&<><i/>{enhanced?'Original illustration':t('Imagem descrita')}</>}</small></button><button className={'qb-bookmark '+(bookmarks.includes(q.n)?'is-active':'')} aria-label={t(bookmarks.includes(q.n)?'Remover dos salvos':'Salvar questão')+' '+q.n} aria-pressed={bookmarks.includes(q.n)} onClick={()=>toggleBookmark(q.n)}><Bookmark size={18}/></button><button className="qb-open" aria-label={t('Abrir questão')+' '+q.n} onClick={()=>study(filtered.map(v=>v.n),filtered.indexOf(q))}><ArrowUpRight size={19}/></button></article>)}</div>
 {!filtered.length&&<div className="qb-empty"><Search size={28}/><h3>{t('Nenhuma questão por aqui.')}</h3><p>{t('Tente outro tema ou remova um filtro.')}</p><button className="qb-button" onClick={resetFilters}>{t('Ver todas as questões')}</button></div>}
 {filtered.length>0&&<div className="qb-pagination"><span>{page*pageSize+1}–{Math.min((page+1)*pageSize,filtered.length)} {t('de')} {filtered.length}</span><div><button aria-label={t('Página anterior')} disabled={page===0} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={18}/></button><span>{t('Página')} {page+1} {t('de')} {Math.ceil(filtered.length/pageSize)}</span><button aria-label={t('Próxima página')} disabled={(page+1)*pageSize>=filtered.length} onClick={()=>setPage(p=>p+1)}><ChevronRight size={18}/></button></div></div>}
 </section>
 </>:current?<section className="qb-study">
 <div className="qb-study-toolbar"><button onClick={()=>{setMode('library');setConfirmFinish(false);}}><ArrowLeft size={17}/>{t(mode==='exam'&&!session?.finished?'Pausar e voltar':'Voltar às questões')}</button><span>{t(mode==='exam'?'SIMULADO':'ESTUDO COMENTADO')} · {position+1} / {visibleIds.length}</span><button className={bookmarks.includes(current.n)?'is-active':''} aria-pressed={bookmarks.includes(current.n)} onClick={()=>toggleBookmark(current.n)}><Bookmark size={17}/>{t(bookmarks.includes(current.n)?'Salva':'Salvar')}</button></div>
 {outcome&&<div className="qb-result" role="status"><div><CheckCheck size={25}/><h2>{t('Simulado concluído.')}</h2><p>{t('Revise os comentários de cada questão abaixo.')}</p></div><div><strong>{outcome.correct}</strong><span>{t('Conforme o gabarito')}</span></div><div><strong>{outcome.review}</strong><span>{t('Para revisar')}</span></div><div><strong>{outcome.unanswered}</strong><span>{t('Não respondidas')}</span></div></div>}
 <div className={"qb-study-grid "+(mode==='exam'?'has-exam-nav':'')}><article className="qb-question-card"><div className="qb-question-reading"><div className="qb-question-meta"><span>{current.banca}</span><span>{t('QUESTÃO')} {current.n}</span></div><h2 ref={heading} tabIndex={-1}>{current.tema}</h2><div className="qb-question-tags"><span>{t(areaOf(current))}</span><span>{t(current.dificuldade)}</span></div>{current.temImagem&&!current.illustration&&<p className="qb-image-note">{t('Enunciado adaptado: a imagem da prova original está descrita no texto.')}</p>}<p className="qb-stem">{current.enunciado}</p>{current.illustration&&<><ChallengeIllustration image={current.illustration} locale="en"/><small>{current.provenance?.rights} · {current.provenance?.author}</small></>}{enhanced&&mode==='study'&&!revealed&&current.hint&&<><button className="qb-button" onClick={()=>updateLedger(track(ledgerRef.current,current,{hint:true,mode:'study'}))}>Show hint (records assistance)</button>{ledger.drafts[`study:${current.n}@${current.version}`]?.hinted&&<p role="status">{current.hint}</p>}</>}</div><div className="qb-answer-reading"><fieldset className="qb-alternatives"><legend>{t('Escolha uma alternativa')}</legend>{Object.entries(current.alternativas).map(([letter,text])=><label key={letter} className={(revealed?(letter===current.gabarito?'is-correct':letter===answer?'is-review':''):(mode==='exam'?answer:picked)===letter?'is-picked':'')}><input type="radio" name={'question-'+current.n} value={letter} checked={(mode==='exam'?answer:picked)===letter} disabled={revealed} onChange={()=>choose(letter)}/><span className="qb-letter">{letter}</span><span>{text}</span>{revealed&&letter===current.gabarito&&<Check size={19}/>}</label>)}</fieldset>

 {revealed&&<section className="qb-explanation" aria-live="polite"><span className="qb-eyebrow">{t('ENTENDA O RACIOCÍNIO')}</span><h3>{t(answer===current.gabarito?'Você conectou os pontos.':answer?'Vamos rever juntos.':'Vale revisar este tema.')}</h3><strong>{t('Gabarito: alternativa')} {current.gabarito}{answer&&answer!==current.gabarito?' · '+t('Sua resposta:')+' '+answer:''}</strong><p>{current.explicacao}</p>{current.rationales&&<ul>{Object.entries(current.rationales).map(([letter,text])=><li key={letter}><strong>{letter}</strong>: {text}</li>)}</ul>}{current.source&&<p><a href={current.source.url} target="_blank" rel="noreferrer">{current.source.title}</a> · verified {current.source.verified}</p>}{enhanced&&<p>First answer: {firstAttempts(ledger).find(a=>a.questionId===current.n)?.answer||'—'} · Hint: {firstAttempts(ledger).find(a=>a.questionId===current.n)?.hinted?'yes':'no'} · Active seconds: {Math.round((firstAttempts(ledger).find(a=>a.questionId===current.n)?.activeMs||0)/1000)}</p>}<small>{enhanced?'Original teaching draft — editorial review pending.':t('Comentário do acervo de estudo. Confira a prova e as referências atuais ao aprofundar o tema.')}</small>{mode==='study'&&<button className="qb-retry" onClick={()=>{renewAttempt();setPicked('');setConfirmed('');focusQuestion();}}>{t('Responder novamente')}</button>}</section>}
 </div><div className="qb-study-bottom"><button className="qb-button" disabled={position===0} onClick={()=>navigate(position-1)}><ChevronLeft size={16}/>{locale==='en'?'Previous':'Anterior'}</button><span>{mode==='study'&&!confirmed?<button className="qb-button qb-primary" aria-label={t('Confirmar resposta')} disabled={!picked} onClick={confirm}>{t('Confirmar')} <Check size={16}/></button>:<>{position+1} {t('de')} {visibleIds.length}</>}</span>{position<visibleIds.length-1?<button className="qb-button qb-primary" onClick={()=>navigate(position+1)}>{t('Próxima')} <ChevronRight size={16}/></button>:mode==='exam'&&!session?.finished?<button className="qb-button qb-primary" onClick={()=>setConfirmFinish(true)}>{t('Concluir simulado')} <Check size={16}/></button>:<button className="qb-button qb-primary" onClick={()=>setMode('library')}>{t('Voltar ao banco')}</button>}</div></article>
 <aside className="qb-study-aside" hidden={mode!=='exam'}><span className="qb-eyebrow">{t(mode==='exam'?'SUA SESSÃO':'APRENDER COM CADA RESPOSTA')}</span><BookOpen size={28}/><h3>{t(mode==='exam'?'Concentre-se no raciocínio.':'A resposta é só o começo.')}</h3><p>{t(mode==='exam'?'Você pode ir e voltar entre as questões. Os comentários aparecem ao concluir.':'Leia o caso, escolha uma alternativa e confira a explicação.')}</p>{mode==='exam'&&session&&<><div className="qb-exam-nav">{session.ids.map((id,i)=><button key={id} aria-label={t('Ir para questão')+' '+(i+1)} aria-current={i===position?'step':undefined} className={(session.answers[id]?'is-answered ':'')+(i===position?'is-current':'')} onClick={()=>navigate(i)}>{i+1}</button>)}</div>{!session.finished&&<button className="qb-button" onClick={()=>setConfirmFinish(true)}>{t('Concluir simulado')}</button>}</>}<div className="qb-local-note">{enhanced?(saveError?'Unsaved — download recovery before leaving.':'Saved locally in this browser.'):t('Progresso salvo neste navegador.')}{mode==='exam'&&!session?.finished?' '+t('Você pode pausar e continuar depois.'):''}</div></aside></div>
 {confirmFinish&&session&&<div className="qb-modal-backdrop"><section className="qb-modal" role="dialog" aria-modal="true" aria-labelledby="qb-finish-title" onKeyDown={e=>{if(e.key==='Escape')setConfirmFinish(false);if(e.key==='Tab'){const buttons=e.currentTarget.querySelectorAll('button');if(e.shiftKey&&document.activeElement===buttons[0]){e.preventDefault();buttons[buttons.length-1].focus();}else if(!e.shiftKey&&document.activeElement===buttons[buttons.length-1]){e.preventDefault();buttons[0].focus();}}}}><h2 id="qb-finish-title">{t('Concluir este simulado?')}</h2><p>{session.ids.length-Object.keys(session.answers).length} {t('questões sem resposta.')} {t('Depois de concluir, você poderá ler todos os comentários.')}</p><div><button autoFocus className="qb-button" onClick={()=>setConfirmFinish(false)}>{t('Continuar respondendo')}</button><button className="qb-button qb-primary" onClick={finish}>{t('Concluir e revisar')}</button></div></section></div>}
 </section>:null}
 <footer className="qb-footer"><div><GraduationCap size={17}/><span>{enhanced?'2Doctor':'WMed'} · {t('Banco de questões')}</span></div><p>{enhanced?(saveError?'Unsaved changes — download recovery.':'Saved only in this browser and scope.'):t('Salvo neste navegador. Use Salvar progresso e Importar para transferir.')}</p>{standalone&&<a href="/bancodequestoes/classico/">{t('Acessar versão anterior')} <ArrowUpRight size={13}/></a>}</footer>
 </Main></div>;
}

// Remount state on catalog/account changes even when a caller forgets React key.
function LockedQuestionBank(props:Parameters<typeof QuestionBankView>[0]){
 const [status,setStatus]=useState('pending'),[retry,setRetry]=useState(0);
 useEffect(()=>{const warn=e=>{if(hasPendingSnapshots()){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[]);
 useEffect(()=>{setStatus('pending');return holdWriter(navigator.locks,props.storageKey,setStatus);},[props.storageKey,retry]);
 if(status==='ready')return <QuestionBankView {...props}/>;
 return <section className="qb-root" style={{padding:24}}><h1>Question bank</h1><p role="alert">{status==='busy'?'This account and catalog are open in another tab. This tab cannot write. Close the other workspace, then retry.':status==='unsupported'?'This browser cannot safely coordinate tabs. This catalog is unavailable here; use a browser supporting Web Locks.':'Opening local workspace…'}</p>{status==='busy'&&<button className="qb-button" onClick={()=>setRetry(n=>n+1)}>Retry workspace access</button>}</section>;
}
export default function QuestionBank(props:Parameters<typeof QuestionBankView>[0]){const key=`${props.storageKey}:${props.catalogId||'legacy'}`;return props.catalog?<LockedQuestionBank key={key} {...props}/>:<QuestionBankView key={key} {...props}/>;}
