import {useState,useEffect,useRef} from 'react';
import {X,LockKeyhole,ArrowRight} from 'lucide-react';
export default function AuthDialog({api,onClose,onSuccess}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const root=useRef(null),controller=useRef(null);
 useEffect(()=>{const previous=document.activeElement;return()=>{controller.current?.abort();previous?.focus?.();};},[]);
 function keys(e){if(e.key==='Escape'&&!busy)onClose();if(e.key==='Tab'){const all=[...root.current.querySelectorAll('button,input,a')].filter(el=>!el.disabled);if(e.shiftKey&&document.activeElement===all[0]){e.preventDefault();all.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===all.at(-1)){e.preventDefault();all[0]?.focus();}}}
 async function submit(e){e.preventDefault();if(busy)return;setBusy(true);setError('');controller.current=new AbortController();try{const r=await fetch(`${api}/auth`,{method:'POST',headers:{'Content-Type':'application/json','X-WMed-Request':'1'},body:JSON.stringify({email:email.trim(),password}),signal:controller.current.signal});const data=await r.json();if(!r.ok||!data.authenticated)throw Error(data.error||'Não foi possível entrar.');setPassword('');onSuccess(data);}catch(e){if(e.name!=='AbortError')setError(e.message);}finally{setBusy(false);}}
 return <div className="modal-shade" onClick={()=>{if(!busy)onClose();}}><section ref={root} onKeyDown={keys} className="modal auth-modal" role="dialog" aria-modal="true" aria-labelledby="login-title" onClick={e=>e.stopPropagation()}><button className="icon-btn close" disabled={busy} aria-label="Fechar entrada" onClick={onClose}><X/></button><div className="auth-icon"><LockKeyhole size={22}/></div><span className="eyebrow blue">SUA CONTA VYTAL</span><h2 id="login-title">Entre para continuar.</h2><p>Use o mesmo e-mail e senha do Vytal Acadêmico. Seu acesso e os limites do assistente continuam os mesmos.</p><form onSubmit={submit}><label htmlFor="wmed-email">E-mail</label><input autoFocus id="wmed-email" name="username" type="email" autoComplete="username" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} disabled={busy}/><label htmlFor="wmed-password">Senha</label><input id="wmed-password" name="password" type="password" autoComplete="current-password" required maxLength={512} value={password} onChange={e=>setPassword(e.target.value)} disabled={busy}/>{error&&<p role="alert" className="error">{error}</p>}<button className="auth-submit" disabled={busy}>{busy?'Entrando…':'Entrar no WMed'}<ArrowRight size={17}/></button></form><a className="auth-help" href="https://app.vytalsaude.com.br/estudante" target="_blank" rel="noopener noreferrer">Criar conta ou recuperar acesso no Vytal ↗</a><p className="modal-note">A senha não fica salva no WMed. A sessão usa um cookie protegido. A pesquisa de artigos pode ser usada sem entrar.</p></section></div>;
}
