import React,{useEffect,useState,useId} from 'react';
import {ArrowLeft,ArrowRight,Check,Lock,HeartPulse} from 'lucide-react';
import {FASES,APROVACAO} from './ecg/course';
import {ecgY,normalizarModo,rotuloDoModo,faixasDoModo,explicacaoPorModo,DERIVACOES_FRONTAIS,vetorNoTempo,eixoDoModo} from './ecg/wave';
import './ecg/course.css';
import {useI18n} from './doctor/I18n';
// "Anterior" (parede) é igual em EN/ES; no catálogo global a mesma chave é "Anterior" = "Previous" (botão).
const wall=(t,s)=>s==='Anterior'?s:t(s);
function Trace({mode='sinusal',grid=false}){
 const {t}=useI18n(),id=useId(),[pos,setPos]=useState(.3),m=normalizarModo(mode),bands=faixasDoModo(m);
 const d=Array.from({length:901},(_,i)=>`${i?'L':'M'}${i/900*800},${140-ecgY(m,i/900)*72}`).join(' '),band=bands.find(b=>pos>=b.ini&&pos<=b.fim),label=t(rotuloDoModo(m)),explain=explicacaoPorModo(m);
 return <div className="ecg-visual"><strong>{label}</strong><svg viewBox="0 0 800 235" role="img" aria-label={`${t('Traçado didático:')} ${label}`}><defs><pattern id={id} width="20" height="20" patternUnits="userSpaceOnUse"><path d="M20 0H0V20" fill="none" stroke="#b7838340"/></pattern></defs><rect width="800" height="235" fill={`url(#${id})`}/><path d={d} fill="none" stroke="currentColor" strokeWidth="2.5"/><line x1={pos*800} x2={pos*800} y1="5" y2="215" stroke="#ad723f" strokeWidth="2"/>{bands.map((b,i)=><text key={i} x={(b.ini+b.fim)*400} y="225" textAnchor="middle" fill="currentColor" fontSize="15">{t(b.onda.replace(/^(Onda|Segmento|Complexo) /,''))}</text>)}</svg><label>{t('Percorrer o traçado')}<input aria-label={t('Posição no traçado')} type="range" min="0" max="1" step=".002" value={pos} onChange={e=>setPos(+e.target.value)}/></label><p>{band?t(band.texto):t('Observe a linha de base e a sequência das ondas.')}</p>{grid&&<div className="ecg-facts"><span>{t('25 mm/s: 1 mm = 0,04 s')}</span><span>{t('10 mm/mV: 1 mm = 0,1 mV')}</span><span>{t('5 mm = 0,20 s')}</span></div>}<small>{t('Traçado sintético, sem calibração física na tela.')} {explain&&t(explain)}</small></div>
}
function Axis({mode='sinusal'}){
 const {t}=useI18n(),[angle,setAngle]=useState(eixoDoModo(normalizarModo(mode))),rad=angle*Math.PI/180;
 return <div className="ecg-visual"><strong>{t('Eixo e projeção nas derivações')}</strong><div className="ecg-axis-layout"><svg viewBox="0 0 360 320" role="img" aria-label={t('Eixo elétrico em {n} graus').replace('{n}',angle)}><circle cx="180" cy="160" r="115" fill="none" stroke="currentColor" opacity=".15"/>{DERIVACOES_FRONTAIS.map(d=>{const a=d.ang*Math.PI/180;return <g key={d.nome}><line x1={180-105*Math.cos(a)} y1={160-105*Math.sin(a)} x2={180+115*Math.cos(a)} y2={160+115*Math.sin(a)} stroke="currentColor" opacity=".2"/><text x={180+138*Math.cos(a)} y={165+138*Math.sin(a)} textAnchor="middle" fill="currentColor" fontSize="12">{t(d.nome)}</text></g>})}<line x1="180" y1="160" x2={180+100*Math.cos(rad)} y2={160+100*Math.sin(rad)} stroke="#ba8143" strokeWidth="6"/><circle cx={180+100*Math.cos(rad)} cy={160+100*Math.sin(rad)} r="7" fill="#ba8143"/></svg><div>{DERIVACOES_FRONTAIS.map(d=><p key={d.nome}><b>{t(d.nome)}</b> {t(Math.cos((angle-d.ang)*Math.PI/180)>.1?'Predomínio positivo':Math.cos((angle-d.ang)*Math.PI/180)<-.1?'Predomínio negativo':'Quase isodifásico')}</p>)}</div></div><label>{t('Eixo:')} {angle}°<input aria-label={t('Ângulo do eixo elétrico')} type="range" min="-180" max="180" value={angle} onChange={e=>setAngle(+e.target.value)}/></label><p>{t('A projeção é positiva quando o vetor aponta para o polo positivo da derivação.')}</p></div>
}
function Leads({artery}){const {t}=useI18n();return <div className="ecg-visual"><strong>{t('Derivações e territórios')}</strong><div className="ecg-facts">{[['Inferior','DII, DIII, aVF','Coronária direita; varia com a dominância'],['Septal','V1, V2','Descendente anterior'],['Anterior','V3, V4','Descendente anterior'],['Lateral','DI, aVL, V5, V6','Circunflexa ou ramos diagonais']].map(([title,leads,a])=><article key={title}><h3>{wall(t,title)}</h3><p>{t(leads)}</p>{artery&&<small>{t(a)}</small>}</article>)}</div><p>{t('Os territórios são referências didáticas; a anatomia coronariana varia entre pessoas.')}</p></div>}
function Block({b}){const {t}=useI18n();if(b.tipo==='texto')return <article className="ecg-text"><h2>{b.titulo&&t(b.titulo)}</h2><p>{t(b.texto)}</p></article>;if(b.tipo==='passos')return <article className="ecg-text"><h2>{b.titulo&&t(b.titulo)}</h2><ol>{b.itens.map((x,i)=><li key={i}>{t(x)}</li>)}</ol></article>;return <><div>{b.tipo==='grid'?<Trace grid/>:b.tipo==='conducao'?<Trace mode={b.modo}/>:b.tipo==='derivacoes'?<Leads artery={b.arteria}/>:<Axis mode={b.modo}/>}</div>{b.nota&&<p className="ecg-block-note">{t(b.nota.replaceAll('3D','traçado').replace('coração acende','traçado avança'))}</p>}</>}
export default function EcgCourse({scope='guest'}){
 const {t}=useI18n();
 const key=`wmed:ecg-course:v1:${scope}`;
 const [done,setDone]=useState(()=>{try{const d=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(d)?d.filter(id=>FASES.some(f=>f.id===id)):[]}catch{return[]}}),[id,setId]=useState(null),[block,setBlock]=useState(0),[quiz,setQuiz]=useState(false),[answers,setAnswers]=useState({}),[graded,setGraded]=useState(false),[saveError,setSaveError]=useState(false);
 useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(done));setSaveError(false)}catch{setSaveError(true)}},[done,key]);
 const phase=FASES.find(f=>f.id===id),questions=phase?.quiz||[],correct=questions.filter((q,i)=>answers[i]===q.correta).length,passed=questions.length&&correct/questions.length>=APROVACAO;
 function open(f){setId(f.id);setBlock(0);setQuiz(false);setAnswers({});setGraded(false)}
 return <section className="module-page ecg-course"><header className="module-heading"><span className="eyebrow">{t('CURSO VYTAL ACADÊMICO')}</span><h1>{t('ECG em 10 passos')}</h1><p>{t('Entenda o impulso, leia o traçado e pratique.')} {t('{a} de {b} etapas concluídas.').replace('{a}',done.length).replace('{b}',FASES.length)}</p><progress max={FASES.length} value={done.length} aria-label={t('Etapas concluídas')}/></header>{saveError&&<p role="alert">{t('Não foi possível guardar o progresso neste navegador.')}</p>}{!phase?<div className="ecg-course-map">{FASES.map((f,i)=>{const unlocked=i===0||done.includes(FASES[i-1].id);return <button key={f.id} disabled={!unlocked} onClick={()=>open(f)}><span className="ecg-step-number">{done.includes(f.id)?<Check/>:unlocked?f.num:<Lock size={18}/>}</span><div><small>{t('PASSO')} {f.num}</small><h2>{t(f.titulo)}</h2><p>{t(f.resumo)}</p></div><ArrowRight size={19}/></button>})}</div>:<><div className="ecg-course-nav"><button onClick={()=>setId(null)}><ArrowLeft size={16}/>{t('Todas as etapas')}</button><span>{t('PASSO')} {phase.num} · {t(phase.titulo)}</span><button onClick={()=>{setQuiz(!quiz);setGraded(false)}}>{quiz?t('Voltar à lição'):t('Praticar')}</button></div>{quiz?<div className="ecg-quiz">{questions.map((q,i)=><fieldset key={i}><legend>{i+1}. {t(q.pergunta)}</legend>{q.opcoes.map((o,j)=><label key={j} className={graded&&j===q.correta?'correct':''}><input type="radio" name={`ecg-${i}`} checked={answers[i]===j} disabled={graded} onChange={()=>setAnswers(a=>({...a,[i]:j}))}/>{wall(t,o)}</label>)}{graded&&<p>{answers[i]===q.correta?t('✓ Correto.'):t('Reveja este ponto.')} {t(q.explica)}</p>}</fieldset>)}{graded?<div className="ecg-result" role="status"><strong>{t('{a} de {b} acertos').replace('{a}',correct).replace('{b}',questions.length)} · {passed?t('Etapa concluída'):t('Vamos revisar')}</strong><p>{t('São necessários pelo menos 80% de acertos.')}</p><button onClick={()=>{if(passed){const next=FASES[phase.num];next?open(next):setId(null)}else{setAnswers({});setGraded(false)}}}>{passed?(phase.num<10?t('Próxima etapa'):t('Voltar ao curso')):t('Tentar novamente')}</button></div>:<button className="module-primary" disabled={Object.keys(answers).length!==questions.length} onClick={()=>{setGraded(true);if(passed)setDone(d=>[...new Set([...d,phase.id])])}}>{t('Conferir respostas')}</button>}</div>:<div className="ecg-lesson"><Block key={phase.id+block} b={phase.licao[block]}/><footer><button disabled={block===0} onClick={()=>setBlock(i=>i-1)}><ArrowLeft size={17}/>{t('Anterior')}</button><span>{block+1} / {phase.licao.length}</span><button onClick={()=>block+1<phase.licao.length?setBlock(i=>i+1):setQuiz(true)}>{block+1<phase.licao.length?t('Continuar'):t('Praticar')}<ArrowRight size={17}/></button></footer></div>}</>}<p className="module-note">{t('Progresso salvo neste navegador, separado por conta. Conteúdo e questões do Vytal Acadêmico; diagramas adaptados para a web.')}</p></section>
}
