import React,{useEffect,useState,useId} from 'react';
import {ArrowLeft,ArrowRight,Check,Lock,HeartPulse} from 'lucide-react';
import {FASES,APROVACAO} from './ecg/course';
import {ecgY,normalizarModo,rotuloDoModo,faixasDoModo,explicacaoPorModo,DERIVACOES_FRONTAIS,vetorNoTempo,eixoDoModo} from './ecg/wave';
import './ecg/course.css';
function Trace({mode='sinusal',grid=false}){
 const id=useId(),[t,setT]=useState(.3),m=normalizarModo(mode),bands=faixasDoModo(m);
 const d=Array.from({length:901},(_,i)=>`${i?'L':'M'}${i/900*800},${140-ecgY(m,i/900)*72}`).join(' '),band=bands.find(b=>t>=b.ini&&t<=b.fim);
 return <div className="ecg-visual"><strong>{rotuloDoModo(m)}</strong><svg viewBox="0 0 800 235" role="img" aria-label={`Traçado didático: ${rotuloDoModo(m)}`}><defs><pattern id={id} width="20" height="20" patternUnits="userSpaceOnUse"><path d="M20 0H0V20" fill="none" stroke="#b7838340"/></pattern></defs><rect width="800" height="235" fill={`url(#${id})`}/><path d={d} fill="none" stroke="currentColor" strokeWidth="2.5"/><line x1={t*800} x2={t*800} y1="5" y2="215" stroke="#ad723f" strokeWidth="2"/>{bands.map((b,i)=><text key={i} x={(b.ini+b.fim)*400} y="225" textAnchor="middle" fill="currentColor" fontSize="15">{b.onda.replace(/^(Onda|Segmento|Complexo) /,'')}</text>)}</svg><label>Percorrer o traçado<input aria-label="Posição no traçado" type="range" min="0" max="1" step=".002" value={t} onChange={e=>setT(+e.target.value)}/></label><p>{band?.texto||'Observe a linha de base e a sequência das ondas.'}</p>{grid&&<div className="ecg-facts"><span>25 mm/s: 1 mm = 0,04 s</span><span>10 mm/mV: 1 mm = 0,1 mV</span><span>5 mm = 0,20 s</span></div>}<small>Traçado sintético, sem calibração física na tela. {explicacaoPorModo(m)}</small></div>
}
function Axis({mode='sinusal'}){
 const [angle,setAngle]=useState(eixoDoModo(normalizarModo(mode))),rad=angle*Math.PI/180;
 return <div className="ecg-visual"><strong>Eixo e projeção nas derivações</strong><div className="ecg-axis-layout"><svg viewBox="0 0 360 320" role="img" aria-label={`Eixo elétrico em ${angle} graus`}><circle cx="180" cy="160" r="115" fill="none" stroke="currentColor" opacity=".15"/>{DERIVACOES_FRONTAIS.map(d=>{const a=d.ang*Math.PI/180;return <g key={d.nome}><line x1={180-105*Math.cos(a)} y1={160-105*Math.sin(a)} x2={180+115*Math.cos(a)} y2={160+115*Math.sin(a)} stroke="currentColor" opacity=".2"/><text x={180+138*Math.cos(a)} y={165+138*Math.sin(a)} textAnchor="middle" fill="currentColor" fontSize="12">{d.nome}</text></g>})}<line x1="180" y1="160" x2={180+100*Math.cos(rad)} y2={160+100*Math.sin(rad)} stroke="#ba8143" strokeWidth="6"/><circle cx={180+100*Math.cos(rad)} cy={160+100*Math.sin(rad)} r="7" fill="#ba8143"/></svg><div>{DERIVACOES_FRONTAIS.map(d=><p key={d.nome}><b>{d.nome}</b> {Math.cos((angle-d.ang)*Math.PI/180)>.1?'Predomínio positivo':Math.cos((angle-d.ang)*Math.PI/180)<-.1?'Predomínio negativo':'Quase isodifásico'}</p>)}</div></div><label>Eixo: {angle}°<input aria-label="Ângulo do eixo elétrico" type="range" min="-180" max="180" value={angle} onChange={e=>setAngle(+e.target.value)}/></label><p>A projeção é positiva quando o vetor aponta para o polo positivo da derivação.</p></div>
}
function Leads({artery}){return <div className="ecg-visual"><strong>Derivações e territórios</strong><div className="ecg-facts">{[['Inferior','DII, DIII, aVF','Coronária direita; varia com a dominância'],['Septal','V1, V2','Descendente anterior'],['Anterior','V3, V4','Descendente anterior'],['Lateral','DI, aVL, V5, V6','Circunflexa ou ramos diagonais']].map(([title,leads,a])=><article key={title}><h3>{title}</h3><p>{leads}</p>{artery&&<small>{a}</small>}</article>)}</div><p>Os territórios são referências didáticas; a anatomia coronariana varia entre pessoas.</p></div>}
function Block({b}){if(b.tipo==='texto')return <article className="ecg-text"><h2>{b.titulo}</h2><p>{b.texto}</p></article>;if(b.tipo==='passos')return <article className="ecg-text"><h2>{b.titulo}</h2><ol>{b.itens.map((x,i)=><li key={i}>{x}</li>)}</ol></article>;return <><div>{b.tipo==='grid'?<Trace grid/>:b.tipo==='conducao'?<Trace mode={b.modo}/>:b.tipo==='derivacoes'?<Leads artery={b.arteria}/>:<Axis mode={b.modo}/>}</div>{b.nota&&<p className="ecg-block-note">{b.nota.replaceAll('3D','traçado').replace('coração acende','traçado avança')}</p>}</>}
export default function EcgCourse({scope='guest'}){
 const key=`wmed:ecg-course:v1:${scope}`;
 const [done,setDone]=useState(()=>{try{const d=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(d)?d.filter(id=>FASES.some(f=>f.id===id)):[]}catch{return[]}}),[id,setId]=useState(null),[block,setBlock]=useState(0),[quiz,setQuiz]=useState(false),[answers,setAnswers]=useState({}),[graded,setGraded]=useState(false),[saveError,setSaveError]=useState(false);
 useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(done));setSaveError(false)}catch{setSaveError(true)}},[done,key]);
 const phase=FASES.find(f=>f.id===id),questions=phase?.quiz||[],correct=questions.filter((q,i)=>answers[i]===q.correta).length,passed=questions.length&&correct/questions.length>=APROVACAO;
 function open(f){setId(f.id);setBlock(0);setQuiz(false);setAnswers({});setGraded(false)}
 return <section className="module-page ecg-course"><header className="module-heading"><span className="eyebrow">CURSO VYTAL ACADÊMICO</span><h1>ECG em 10 passos</h1><p>Entenda o impulso, leia o traçado e pratique. {done.length} de {FASES.length} etapas concluídas.</p><progress max={FASES.length} value={done.length} aria-label="Etapas concluídas"/></header>{saveError&&<p role="alert">Não foi possível guardar o progresso neste navegador.</p>}{!phase?<div className="ecg-course-map">{FASES.map((f,i)=>{const unlocked=i===0||done.includes(FASES[i-1].id);return <button key={f.id} disabled={!unlocked} onClick={()=>open(f)}><span className="ecg-step-number">{done.includes(f.id)?<Check/>:unlocked?f.num:<Lock size={18}/>}</span><div><small>PASSO {f.num}</small><h2>{f.titulo}</h2><p>{f.resumo}</p></div><ArrowRight size={19}/></button>})}</div>:<><div className="ecg-course-nav"><button onClick={()=>setId(null)}><ArrowLeft size={16}/>Todas as etapas</button><span>PASSO {phase.num} · {phase.titulo}</span><button onClick={()=>{setQuiz(!quiz);setGraded(false)}}>{quiz?'Voltar à lição':'Praticar'}</button></div>{quiz?<div className="ecg-quiz">{questions.map((q,i)=><fieldset key={i}><legend>{i+1}. {q.pergunta}</legend>{q.opcoes.map((o,j)=><label key={j} className={graded&&j===q.correta?'correct':''}><input type="radio" name={`ecg-${i}`} checked={answers[i]===j} disabled={graded} onChange={()=>setAnswers(a=>({...a,[i]:j}))}/>{o}</label>)}{graded&&<p>{answers[i]===q.correta?'✓ Correto.':'Reveja este ponto.'} {q.explica}</p>}</fieldset>)}{graded?<div className="ecg-result" role="status"><strong>{correct} de {questions.length} acertos · {passed?'Etapa concluída':'Vamos revisar'}</strong><p>São necessários pelo menos 80% de acertos.</p><button onClick={()=>{if(passed){const next=FASES[phase.num];next?open(next):setId(null)}else{setAnswers({});setGraded(false)}}}>{passed?(phase.num<10?'Próxima etapa':'Voltar ao curso'):'Tentar novamente'}</button></div>:<button className="module-primary" disabled={Object.keys(answers).length!==questions.length} onClick={()=>{setGraded(true);if(passed)setDone(d=>[...new Set([...d,phase.id])])}}>Conferir respostas</button>}</div>:<div className="ecg-lesson"><Block key={phase.id+block} b={phase.licao[block]}/><footer><button disabled={block===0} onClick={()=>setBlock(i=>i-1)}><ArrowLeft size={17}/>Anterior</button><span>{block+1} / {phase.licao.length}</span><button onClick={()=>block+1<phase.licao.length?setBlock(i=>i+1):setQuiz(true)}>{block+1<phase.licao.length?'Continuar':'Praticar'}<ArrowRight size={17}/></button></footer></div>}</>}<p className="module-note">Progresso salvo neste navegador, separado por conta. Conteúdo e questões do Vytal Acadêmico; diagramas adaptados para a web.</p></section>
}
