import React,{useState,useRef,useEffect} from 'react';
import ReactMarkdown from 'react-markdown';import remarkGfm from 'remark-gfm';
import {BookOpen,Layers3,Search,ArrowLeft,ArrowRight,Check,RotateCcw} from 'lucide-react';
import {REVISAO_AREAS as PT_AREAS,REVISAO_DECK as PT_DECKS,REVISAO_TOTAL_TEMAS as PT_TOPICS,REVISAO_TOTAL_CARDS as PT_CARDS} from './enamed/content';
import {montarFila,aplicarNota,estadoInicial,contarPendentes} from './enamed/srs';
import {progressKey,readProgress,gradeQueue,normalize} from './enamed/progress.mjs';
import {useWorkspaceHeight} from './academic/useWorkspaceHeight';
import './enamed/study.css';
import {useI18n} from './doctor/I18n';import {useBrasil} from './doctor/regiao';
const notes={errei:'Errei',chute:'Acertei por acaso',inseguro:'Acertei com dúvida',confiante:'Acertei com segurança'};
const md={a:({href,children})=><a href={href} target="_blank" rel="noreferrer">{children}</a>,img:()=>null};
export default function Enamed({initialMode='summaries',scope='guest'}){
 const {t,locale}=useI18n();
 // Fora do português, os flashcards usam o deck próprio em inglês (áreas com prefixo en-, progresso separado).
 // Fora do Brasil (IP) o conteúdo ENAMED não aparece: só o deck internacional de flashcards.
 const brasil=useBrasil(),[intl,setIntl]=useState(null),foreign=!locale.startsWith('pt')||brasil!==true;
 useEffect(()=>{if(foreign&&!intl)import('./enamed/flashcards-en.json').then(m=>setIntl(m.default)).catch(()=>{})},[foreign,intl]);
 const key=progressKey(scope),[saved,setSaved]=useState(()=>{try{return readProgress(localStorage,key)}catch{return {checks:{},cards:{}}}}),[storageError,setStorageError]=useState(false),[mode,setMode]=useState(initialMode),[areaId,setAreaId]=useState(''),[query,setQuery]=useState(''),[topic,setTopic]=useState(null),[filterTopic,setFilterTopic]=useState(''),[queue,setQueue]=useState(null),[index,setIndex]=useState(0),[answer,setAnswer]=useState(false),[notice,setNotice]=useState('');
 const en=foreign&&!!intl&&mode==='cards',areas=en?intl.areas:PT_AREAS,decks=en?intl.decks:PT_DECKS,totalTopics=en?intl.totalTopics:PT_TOPICS,totalCards=en?intl.totalCards:PT_CARDS;
 const host=useWorkspaceHeight(),reader=useRef(null),area=areas.find(a=>a.id===areaId),current=queue?.[index];
 useEffect(()=>{if(reader.current)reader.current.scrollTop=0},[areaId,topic,index]);
 function persist(next){setSaved(next);try{localStorage.setItem(key,JSON.stringify(next));setStorageError(false)}catch{setStorageError(true)}}
 function navigate(next){if(foreign){setAreaId('');setFilterTopic('')}setQuery('');setMode(next);setTopic(null);setQueue(null);setAnswer(false);setNotice('')}
 function openArea(id){setAreaId(id);setTopic(null);setQuery('');setFilterTopic('');setQueue(null);setNotice('')}
 function openSummary(id,ti){setAreaId(id);setTopic(ti);setMode('summaries');setQueue(null)}
 const deck=area?(decks[area.id]||[]).filter(c=>filterTopic===''||c.ti===Number(filterTopic)):[];
 function start(all=false){const list=all?deck.map(c=>({...c,cardKey:`${area.id}:${c.ti}:c${c.ci}`})):montarFila(deck,area.id,saved.cards);setQueue(list);setIndex(0);setAnswer(false);setNotice('')}
 function grade(note){if(!answer||!current)return;const {estado,requeue}=aplicarNota(saved.cards[current.cardKey]||estadoInicial(current.cardKey),note);persist({...saved,cards:{...saved.cards,[current.cardKey]:estado}});setQueue(q=>gradeQueue(q,index,requeue));setIndex(i=>i+1);setAnswer(false);setNotice(requeue!==null?t('Este cartão voltará nesta sessão.'):`${t('Próxima revisão em')} ${estado.intervalo} ${t(estado.intervalo===1?'dia':'dias')}.`)}
 const topics=areas.flatMap(a=>a.temas.map((t,ti)=>({...t,ti,area:a}))).filter(t=>(!areaId||t.area.id===areaId)&&normalize(t.t+' '+t.area.nome).includes(normalize(query)));
 const completed=Object.values(saved.checks).filter(v=>v===true).length;
 return <section className="enamed-study" ref={host}><header><div><span className="eyebrow">{import.meta.env.VITE_PRODUCT==='2doctor'?t('BIBLIOTECA 2DOCTOR'):t('BIBLIOTECA VYTAL ACADÊMICO')}</span><h1>{t(mode==='summaries'?'Resumos ENAMED':'Flashcards')}</h1><p>{totalTopics} {t('temas')} · {totalCards} {t('cartões')} · {areas.length} {t('áreas')}</p></div>{!en&&<div className="study-tabs"><button aria-pressed={mode==='summaries'} onClick={()=>navigate('summaries')}><BookOpen size={16}/>{t('Resumos')}</button><button aria-pressed={mode==='cards'} onClick={()=>navigate('cards')}><Layers3 size={16}/>{t('Flashcards')}</button></div>}</header>
 <div className="study-toolbar">{area&&<button className="study-back" onClick={()=>openArea('')}><ArrowLeft size={15}/>{t('Áreas')}</button>}<select aria-label={t('Área de estudo')} value={areaId} onChange={e=>openArea(e.target.value)}><option value="">{t('Todas as áreas')}</option>{areas.map(a=><option key={a.id} value={a.id}>{a.nome}</option>)}</select>{mode==='summaries'&&topic===null&&<label><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label={t('Buscar tema ENAMED')} placeholder={t('Buscar tema')}/></label>}{mode==='cards'&&area&&!queue&&<select aria-label={t('Tema dos flashcards')} value={filterTopic} onChange={e=>setFilterTopic(e.target.value)}><option value="">{t('Todos os temas desta área')}</option>{area.temas.map((t,i)=><option value={i} key={i}>{t.t}</option>)}</select>}</div>
 <div className="study-body" ref={reader}>
 {mode==='summaries'&&topic!==null&&area?<article className="study-summary"><div className="study-breadcrumb"><button onClick={()=>setTopic(null)}><ArrowLeft size={15}/>{t('Temas')}</button><span>{area.nome} · {topic+1}/{area.temas.length}</span></div><h2>{area.temas[topic].t}</h2><div className="study-markdown"><ReactMarkdown remarkPlugins={[remarkGfm]} components={md}>{area.temas[topic].r}</ReactMarkdown></div><footer><button aria-pressed={saved.checks[`${area.id}:${topic}`]===true} onClick={()=>persist({...saved,checks:{...saved.checks,[`${area.id}:${topic}`]:!saved.checks[`${area.id}:${topic}`]}})}><Check size={16}/>{t(saved.checks[`${area.id}:${topic}`]?'Revisado':'Marcar como revisado')}</button><button onClick={()=>{setFilterTopic(String(topic));navigate('cards')}}><Layers3 size={16}/>{t('Praticar este tema')}</button><button disabled={topic===0} onClick={()=>setTopic(i=>i-1)}>{locale==='en'?'Previous':'Anterior'}</button><button disabled={topic===area.temas.length-1} onClick={()=>setTopic(i=>i+1)}>{t('Próximo')}<ArrowRight size={15}/></button></footer></article>:
 mode==='cards'&&area?queue?<div className="study-session">{current?<><div className="study-session-top"><button onClick={()=>setQueue(null)}><ArrowLeft size={15}/>{t('Encerrar sessão')}</button><span>{queue.length-index} {t('cartões na fila')}</span></div><article className="study-flashcard"><span className="eyebrow">{area.temas[current.ti].t}</span><h2>{current.q}</h2>{answer?<div className="study-answer"><span className="eyebrow">{t('RESPOSTA')}</span><ReactMarkdown remarkPlugins={[remarkGfm]} components={md}>{current.a}</ReactMarkdown></div>:<button className="study-reveal" onClick={()=>setAnswer(true)}>{t('Mostrar resposta')}</button>}</article>{answer&&<div className="study-grades" aria-label={t('Como foi sua resposta?')}>{Object.entries(notes).map(([id,label])=><button key={id} onClick={()=>grade(id)}>{t(label)}</button>)}</div>}{!en&&<button className="study-read" onClick={()=>openSummary(area.id,current.ti)}>{t('Ler resumo deste tema')}<ArrowRight size={14}/></button>}</>:<div className="study-finished"><Check size={32}/><h2>{t(queue.length?'Sessão concluída':'Nenhum cartão pendente neste filtro')}</h2><p>{t('Você pode explorar todos os cartões ou escolher outro tema.')}</p><button onClick={()=>setQueue(null)}>{t('Voltar aos flashcards')}</button></div>}<p className="study-notice" role="status">{notice}</p></div>:<div className="study-start"><Layers3 size={34}/><h2>{filterTopic===''?area.nome:area.temas[Number(filterTopic)].t}</h2><p>{deck.length} {t('cartões')} · {contarPendentes(deck,area.id,saved.cards)} {t('disponíveis para a próxima sessão')}</p><div><button className="study-primary" onClick={()=>start(false)}>{t('Revisar pendentes')}<ArrowRight size={16}/></button><button onClick={()=>start(true)}>{t('Explorar todos')}</button></div><p>{t('Responda mentalmente, revele a resposta e avalie como foi. Os cartões que precisam de reforço voltam à fila.')}</p></div>:
 !areaId&&!query?<div className="study-area-grid">{areas.map((a,i)=><button key={a.id} onClick={()=>openArea(a.id)}><span className="study-area-number">{String(i+1).padStart(2,'0')}</span><div><h2>{a.nome}</h2><p>{a.temas.length} {t(en?'temas':'resumos')} · {decks[a.id].length} {t('cartões')}</p>{!en&&<small>{a.temas.filter((_,ti)=>saved.checks[`${a.id}:${ti}`]).length} {t('temas revisados')}</small>}</div><ArrowRight size={18}/></button>)}</div>:<div className="study-topic-list">{topics.map(t=><button key={`${t.area.id}:${t.ti}`} onClick={()=>openSummary(t.area.id,t.ti)}><span>{saved.checks[`${t.area.id}:${t.ti}`]?<Check size={17}/>:String(t.ti+1).padStart(2,'0')}</span><div><small>{t.area.nome}</small><h2>{t.t}</h2></div><ArrowRight size={17}/></button>)}{!topics.length&&<p>{t('Nenhum tema encontrado. Tente outro termo.')}</p>}</div>}
 </div><footer className="study-footer"><span>{en?`${totalCards} ${t('cartões')}`:`${completed} ${t('de')} ${totalTopics} ${t('temas revisados')}`}</span><span>{t(storageError?'Não foi possível salvar neste navegador. Seu progresso está apenas nesta sessão.':'Progresso salvo neste navegador, separado por conta. Ainda não sincroniza com o app.')}</span></footer></section>
}
