import React, { useState, useEffect, useRef, useCallback, lazy, Suspense } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUp, ArrowUpRight, Plus, Search, BookOpen, SlidersHorizontal, X, Square, Check, Copy, ChevronRight, Activity, Palette, History } from 'lucide-react';
import ReactMarkdown from 'react-markdown';import remarkGfm from 'remark-gfm';
import { loadProgress, saveProgress } from '../shared/progress.mjs';
import Modules, { moduleItems } from './Modules';import './modules.css';
import PrivacyReview from './PrivacyReview';
import ChatHistory, { useChatHistory } from './ChatHistory';
import { reviewPrivacy } from '../shared/privacy-review.mjs';
import { contextTools } from '../shared/context-tools.mjs';
const ClinicalCase = lazy(() => import('./ClinicalCase'));
import ChatAttachments from './ChatAttachments';
import { chatContent } from '../shared/chat-content.mjs';
import './chat-attachments.css';
import AuthDialog from './AuthDialog';import './styles.css';import './chat-design.css';import './theme-system.css';
import { productConfig } from '../shared/product.mjs';
import { Rail as DoctorRail, Header as DoctorHeader, Drawer as DoctorDrawer, Welcome as DoctorWelcome, QuickActions, MobileNavigation } from './doctor/Navigation';
import './doctor/doctor.css';
import { I18nProvider, useI18n, LibraryLanguageNotice } from './doctor/I18n';
const BASE = import.meta.env.BASE_URL;const PUBLIC = import.meta.env.VITE_PUBLIC_PREVIEW === 'true';const API = PUBLIC ? '/api/wmed' : '/api';
const PRODUCT = productConfig(import.meta.env.VITE_PRODUCT, BASE);
const prompts = ['Explique a insuficiência mitral', 'Compare asma e DPOC', 'Como interpretar o escore de Wells?'];
async function readEvents(body, handler) {const reader = body.getReader(),decoder = new TextDecoder();let buffer = '';while (true) {const { done, value } = await reader.read();if (done) break;buffer += decoder.decode(value, { stream: true });let end;while ((end = buffer.indexOf('\n\n')) >= 0) {const b = buffer.slice(0, end);buffer = buffer.slice(end + 2);const event = b.split('\n').find((s) => s.startsWith('event:'))?.slice(6).trim();const d = b.split('\n').filter((s) => s.startsWith('data:')).map((s) => s.slice(5)).join('\n');if (d) handler(event, JSON.parse(d));}}}
function CitationText({ text, sources, mode }) {const prepared = mode === 'chat' ? chatContent(text).text : text.replace(/\[(\d+)\](?!\()/g, (match, n) => sources[n - 1] ? `[${n}](${sources[n - 1].url})` : '[referência indisponível]');const urls = new Set(sources.map((s) => s.url));return <ReactMarkdown remarkPlugins={[remarkGfm]} components={{ a: ({ href, children }) => urls.has(href) || mode === 'chat' && /^https:\/\//.test(href || '') ? <a href={href} target="_blank" rel="noopener noreferrer">{children}</a> : <span>{children}</span>, img: () => null }}>{prepared}</ReactMarkdown>;}
function Source({ s, i }) {return <a className="source" href={s.url} target="_blank" rel="noopener noreferrer"><span className="source-index">{String(i + 1).padStart(2, '0')}</span><div><div className="source-meta">{s.year} <span>·</span> {s.journal || 'Europe PMC'}</div><h4>{s.title}</h4><span className="source-authors">{s.authors}</span></div><ArrowUpRight size={17} /></a>;}
const themes = [['white', 'Branco'], ['dark', 'Escuro'], ['blue', 'Azul'], ['green', 'Verde']];
function App() {
  const { locale, country, t } = useI18n();
  const [menuGroup, setMenuGroup] = useState(null);
  function openMenu(group) {setMenuGroup(typeof group === 'string' ? group : null);setMenu(true);}
  useEffect(() => {document.documentElement.dataset.product = PRODUCT.id;}, []);
  const [theme, setTheme] = useState(() => {try {const saved = localStorage.getItem(PRODUCT.themeKey);return themes.some(([id]) => id === saved) ? saved : 'white';} catch {return 'white';}});
  useEffect(() => {document.documentElement.dataset.theme = theme;try {localStorage.setItem(PRODUCT.themeKey, theme);} catch {}}, [theme]);
  const [module, setModule] = useState(() => {const id=location.hash.slice(1).split('?')[0];return moduleItems.some(m=>m.id===id)?id:'chat';}),[menu, setMenu] = useState(false),[progress, setProgress] = useState([]),[caseKey, setCaseKey] = useState(0);
  useEffect(() => {const change = () => {const [next, query] = location.hash.slice(1).split('?');setModule(moduleItems.some((m) => m.id === next) ? next : 'chat');const topic = new URLSearchParams(query).get('tema');if (topic) setQuestion(topic);setMenu(false);};addEventListener('hashchange', change);return () => removeEventListener('hashchange', change);}, []);
  function navigate(id) {location.hash = id;setModule(id);setMenu(false);if (id === 'chat') setView('chat');}
  useEffect(() => {if (!PRODUCT.doctor) return;const frame = requestAnimationFrame(() => window.scrollTo({top:0,left:0,behavior:'instant'}));return () => cancelAnimationFrame(frame);}, [module]);

  const [caseWork, setCaseWork] = useState({ module: false, dialog: false });
  const markModuleCase = useCallback((value) => setCaseWork((old) => old.module === value ? old : { ...old, module: value }), []);
  const markDialogCase = useCallback((value) => setCaseWork((old) => old.dialog === value ? old : { ...old, dialog: value }), []);
  const [privacy, setPrivacy] = useState(null),[caseOpen, setCaseOpen] = useState(false),[caseMounted, setCaseMounted] = useState(false),[caseDraft, setCaseDraft] = useState('');
  const [attachments, setAttachments] = useState([]),[attachmentLoading, setAttachmentLoading] = useState(false);
  const [question, setQuestion] = useState(''),[messages, setMessages] = useState([]),[busy, setBusy] = useState(false),[status, setStatus] = useState(null),[settings, setSettings] = useState(false),[view, setView] = useState('chat'),[copied, setCopied] = useState(''),[mode, setMode] = useState('chat'),[session, setSession] = useState(null),[login, setLogin] = useState(false),[pending, setPending] = useState(''),[accountError, setAccountError] = useState('');
  const historyStore = useChatHistory({ api: API, scope: session?.user?.progressScope, messages, setMessages, busy });
  useEffect(() => {try {setProgress(loadProgress(localStorage, session?.user?.progressScope));} catch {setProgress([]);}}, [session?.user?.progressScope]);
  function recordProgress(score) {setProgress((previous) => {const next = [...previous, { score, date: new Date().toISOString() }];try {saveProgress(localStorage, session?.user?.progressScope, next);} catch {}return next;});}
  const abort = useRef(null),scroll = useRef(null),input = useRef(null),busyRef = useRef(false),pinned = useRef(true);
  useEffect(() => {fetch(`${API}/auth`).then((r) => r.ok ? r.json() : Promise.reject()).then((d) => setSession(d.authenticated ? d : null)).catch(() => setSession(null));fetch(`${API}/status`).then((r) => r.ok ? r.json() : Promise.reject()).then(setStatus).catch(() => setStatus({ offline: true }));return () => abort.current?.abort();}, []);
  useEffect(() => {const track = () => {pinned.current = document.documentElement.scrollHeight - window.scrollY - window.innerHeight < 180;};addEventListener('scroll', track, { passive: true });return () => removeEventListener('scroll', track);}, []);
  useEffect(() => {if (pinned.current && messages.length) window.scrollTo({ top: document.documentElement.scrollHeight, behavior: 'instant' });}, [messages, busy]);
  function update(id, patch) {setMessages((ms) => ms.map((m) => m.id === id ? { ...m, ...(typeof patch === 'function' ? patch(m) : patch) } : m));}
  async function send(value = question, authenticated = false, reviewed = false) {const q = mode === 'chat' && attachments.length && value.trim().length < 3 ? 'Explique o conteúdo dos arquivos enviados. ' + value.trim() : value.trim();if (q.length < 3 || busyRef.current || historyStore.loading || attachmentLoading) return;if (!reviewed && reviewPrivacy(q).spans.length) {setPrivacy(q);return;}if (mode === 'chat' && !session?.authenticated && !authenticated) {setPending(q);setQuestion(q);setLogin(true);return;}busyRef.current = true;pinned.current = true;setBusy(true);setQuestion('');setView('chat');const id = crypto.randomUUID();const controller = new AbortController();abort.current = controller;
    const sentAttachments = mode === 'chat' ? attachments : [];
    const displayQuestion = q + (sentAttachments.length ? '\n\n[Arquivos enviados: ' + sentAttachments.map((a) => a.name).join(', ') + '. Arquivos não disponíveis no histórico; reenvie se precisar analisar novamente.]' : '');
    const history = messages.filter((m) => m.mode === 'chat' && !m.error && (m.role === 'user' || m.text && m.complete)).slice(-6).map((m) => ({ role: m.role, content: chatContent(m.text || '').text.slice(0, 6000) }));
    setMessages((ms) => [...ms, { id: id + 'u', role: 'user', text: displayQuestion, mode }, { id, role: 'assistant', text: '', mode, sources: [], progress: mode === 'chat' ? t("Conectando ao assistente\u2026") : 'Iniciando pesquisa…' }]);
    try {const res = await fetch(`${API}/${mode === 'chat' ? 'chat' : 'research'}`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-WMed-Request': '1' }, body: JSON.stringify({ question: q, history, ...(PRODUCT.doctor ? { locale, country } : {}), ...(sentAttachments.length ? { attachments: sentAttachments } : {}) }), signal: controller.signal });if (!res.ok) {const j = await res.json();if (res.status === 401) {setSession(null);setPending(q);setQuestion(q);setLogin(true);}throw new Error(j.error || t("Servi\xE7o indispon\xEDvel."));}
      let done = false;await readEvents(res.body, (event, data) => {if (event === 'progress') update(id, { progress: data.text });if (event === 'sources') update(id, { sources: data.sources, query: data.query, jev: data.jev, progress: t("Preparando resposta\u2026") });if (event === 'delta') update(id, (m) => ({ text: m.text + data.text, progress: '' }));if (event === 'notice') update(id, { notice: data.text, progress: '' });if (event === 'error') {update(id, { error: data.text, progress: '' });done = true;}if (event === 'done') {setAttachments([]);update(id, { progress: '', complete: true });done = true;}});if (!done) throw new Error(t("A conex\xE3o foi interrompida. Tente novamente."));
    } catch (e) {update(id, { error: e.name === 'AbortError' ? t("Resposta interrompida por voc\xEA.") : e.message, progress: '' });} finally {setBusy(false);busyRef.current = false;abort.current = null;}
  }
  async function logout() {setAccountError('');if (attachmentLoading) {setAccountError(t("Aguarde o preparo dos arquivos antes de sair."));return;}if (caseWork.module || caseWork.dialog) {setAccountError('Aguarde a análise e o salvamento do caso antes de sair. Se houve falha, abra o caso e tente salvar novamente.');return;}if (busyRef.current) {setAccountError(t("Interrompa a resposta antes de sair."));return;}if (!(await historyStore.flush())) {setAccountError(t("Salve a conversa antes de sair."));return;}try {const r = await fetch(`${API}/auth`, { method: 'DELETE', headers: { 'X-WMed-Request': '1' } });if (!r.ok) throw Error();setSession(null);setAttachments([]);setSettings(false);setProgress([]);setCaseKey((n) => n + 1);setCaseMounted(false);setCaseOpen(false);setMessages([]);setQuestion('');navigate('chat');setView('chat');} catch {setAccountError(t("Não foi possível sair. Tente novamente."));}}
  async function reset() {if (attachmentLoading || busyRef.current || !(await historyStore.fresh())) return;navigate('chat');setAttachments([]);setMessages([]);setQuestion('');setView('chat');window.scrollTo(0, 0);input.current?.focus();}
  function showHistory() {if (!session?.authenticated) {setLogin(true);return;}historyStore.setOpen(true);historyStore.refresh();}
  async function openHistory(id) {if (attachmentLoading) return;if (await historyStore.select(id)) {navigate('chat');setMode('chat');setAttachments([]);setView('chat');setQuestion('');window.scrollTo(0, 0);}}
  const allSources = [...new Map(messages.flatMap((m) => m.sources ?? []).map((s) => [s.id, s])).values()];
  return <div className={`app-shell ${PRODUCT.doctor ? 'doctor-app' : ''} ${messages.length === 0 && view === 'chat' ? 'doctor-empty' : ''} ${module === 'chat' ? 'is-chat' : 'is-module'}`}>{PRODUCT.doctor ? <DoctorRail module={module} navigate={(id) => {navigate(id);if (id === 'chat') setView('chat');}} onNew={reset} onHistory={showHistory} busy={busy} onAccount={() => session?.authenticated ? setSettings(true) : setLogin(true)} onMenu={openMenu} /> : <aside className="rail"><a href="#" aria-label="WMed início" onClick={(e) => {e.preventDefault();reset();}}><img src={`${BASE}brand/favicon.svg`} alt="WMed" /></a><button title={t("Nova conversa")} aria-label={t("Nova conversa")} onClick={reset}><Plus /></button><button title={t("Hist\xF3rico de conversas")} aria-label={t("Hist\xF3rico de conversas")} disabled={busy} onClick={showHistory}><History size={21} /></button><div className="rail-divider" /><button className={module === 'chat' && view === 'chat' ? 'active' : ''} title={t("Conversa")} aria-label={t("Conversa")} onClick={() => {navigate('chat');setView('chat');}}><Search size={21} /></button><button className={view === 'sources' ? 'active' : ''} title="Fontes desta sessão" aria-label="Fontes desta sessão" onClick={() => {navigate('chat');setView('sources');}}><BookOpen size={21} /></button><div className="rail-spacer" /><button title="Conexões" aria-label="Conexões" onClick={() => setSettings(true)}><SlidersHorizontal size={20} /></button><button className="profile" title={t("Conta Vytal")} aria-label={t("Conta Vytal")} onClick={() => session?.authenticated ? setSettings(true) : setLogin(true)}>{session?.user?.nome?.[0] || 'W'}</button></aside>}
 <div className="workspace">{PRODUCT.doctor ? <DoctorHeader module={module} onHome={() => {navigate('chat');setView('chat');}} onNew={reset} onHistory={showHistory} busy={busy} onAccount={() => session?.authenticated ? setSettings(true) : setLogin(true)} onMenu={openMenu} session={session} theme={theme} setTheme={setTheme} themes={themes} /> : <header className="topbar"><a className="wordmark" href="#chat" aria-label="WMed início"><img src={`${BASE}brand/favicon.svg`} alt="" /><strong>WMed</strong></a><span className="version">WMED</span><button className="modules-toggle" aria-label="Matérias e ferramentas" aria-expanded={menu} onClick={() => setMenu((v) => !v)}>☰ <span>Matérias e ferramentas</span></button><button className="mobile-new" aria-label={t("Nova conversa")} title={t("Nova conversa")} onClick={reset}><Plus size={20} /></button><button className="mobile-history" title={t("Hist\xF3rico de conversas")} aria-label={t("Hist\xF3rico de conversas")} disabled={busy} onClick={showHistory}><History size={20} /></button><div className="top-spacer" /><details className="theme-picker"><summary aria-label={t("Escolher apar\xEAncia")}><Palette size={19} /><span className="theme-label">Aparência</span></summary><div className="theme-options" role="group" aria-label={t("Tema de cores")}>{themes.map(([id, label]) => <button key={id} aria-pressed={theme === id} onClick={(e) => {setTheme(id);e.currentTarget.closest('details').open = false;}}><span className={`theme-dot ${id}`} />{label}{theme === id && <Check size={15} />}</button>)}</div></details><button className="account-button" onClick={() => session?.authenticated ? setSettings(true) : setLogin(true)}>{session?.authenticated ? session.user?.nome || t("Minha conta") : t("Entrar")}</button><button className="connection" onClick={() => setSettings(true)}><span className={'dot ' + (status?.offline ? 'warn' : '')} />{status?.offline ? 'API desconectada' : PUBLIC ? 'Prévia WMed' : 'Ambiente de desenvolvimento'}</button></header>}
 {PRODUCT.doctor ? menu && <DoctorDrawer theme={theme} setTheme={setTheme} themes={themes} initialGroup={menuGroup} module={module} onClose={() => setMenu(false)} onNavigate={navigate} onNew={reset} onHistory={showHistory} busy={busy} onAccount={() => session?.authenticated ? setSettings(true) : setLogin(true)} onSources={() => {navigate('chat');setView('sources');}} /> : menu && <nav className="modules-menu" aria-label="Matérias e ferramentas">{moduleItems.map((m) => <button key={m.id} className={module === m.id ? 'active' : ''} onClick={() => navigate(m.id)}><m.icon size={20} /><span>{m.label}<small>{m.description}</small></span></button>)}</nav>}<div className="module-breadcrumb"><span>{t(moduleItems.find((m) => m.id === module)?.label || 'Chat')}</span>{module !== 'chat' && <button onClick={() => navigate('chat')}>{t("Voltar ao chat \u2197")}</button>}</div><div hidden={module !== 'chat'} className="chat-container"><main className="content wide chat-first"><section className="research-panel"><div className="conversation" ref={scroll} onScroll={(e) => {const el = e.currentTarget;pinned.current = el.scrollHeight - el.scrollTop - el.clientHeight < 90;}}>
 {view === 'sources' ? <div className="library"><h1>{t("Sua pesquisa,")}<br />{t("com origem.")}</h1><p>{t("Publicações encontradas nesta sessão. Abrir a fonte permite conferir o contexto original.")}</p>{allSources.length ? allSources.map((s, i) => <Source key={s.id} s={s} i={i} />) : <div className="empty">{t("Faça sua primeira pergunta para reunir as referências aqui.")}</div>}</div> : messages.length === 0 ? PRODUCT.doctor ? <DoctorWelcome /> : <div className="welcome"><div className="welcome-icon"><Activity size={24} /></div><div className="eyebrow blue">DA EVIDÊNCIA À COMPREENSÃO</div><h1>Como posso ajudar?</h1><p>Pergunte, pesquise ou discuta um caso clínico.</p><div className="prompt-list">{prompts.map((p, i) => <button key={p} onClick={() => send(p)}><span className="prompt-num">0{i + 1}</span><span>{p}</span><ArrowUpRight size={17} /></button>)}</div><div className="welcome-foot"><span className="dot" />Para estudantes e profissionais de saúde.</div></div> : <div className="messages">{messages.map((m) => <article key={m.id} className={'message ' + m.role}>{m.role === 'user' ? <div className="user-bubble">{m.text}</div> : <><div className="assistant-label"><img src={PRODUCT.icon} alt="" />{PRODUCT.name} <span>{m.mode === 'chat' ? t("Assistente Vytal") : t("Pesquisa")}</span></div>{m.progress && <div className="progress"><span className="spinner" />{t(m.progress)}</div>}{m.text && <div className="markdown"><CitationText text={m.text} sources={m.sources} mode={m.mode} /></div>}{m.notice && <p className="notice">{m.notice}</p>}{m.error && <div role="alert" className="error">{t(m.error)}</div>}{m.sources?.length > 0 && <details open={!m.text}><summary>{m.sources.length} fontes encontradas <ChevronRight size={16} /></summary>{m.sources.map((s, i) => <Source key={s.id} s={s} i={i} />)}</details>}{m.query && <details className="query"><summary>{t("Ver termos pesquisados")}</summary><p>{m.query}</p><small>Ordenação: {m.jev === 'ranked' ? 'Jev · relevância textual' : 'Europe PMC · relevância da busca'}. Relevância não é qualidade clínica.</small></details>}{m.mode === 'chat' && m.complete && chatContent(m.text).topics.length > 0 && <div className="chat-topics"><small>{t("Continue estudando")}</small>{chatContent(m.text).topics.map((topic) => <button key={topic} disabled={busy || attachmentLoading} onClick={() => send(topic)}>{topic}</button>)}</div>}{m.complete && m.text && <div className="context-tools" aria-label="Recursos para aprofundar">{contextTools(m.text).map((t) => <button key={t.id} onClick={() => navigate(t.id)}>{t.label}<ArrowUpRight size={14} /></button>)}</div>}{m.text && <button className="copy" onClick={async () => {try {await navigator.clipboard.writeText(m.mode === 'chat' ? chatContent(m.text).text : m.text);setCopied(m.id);} catch {setCopied('');}}}>{copied === m.id ? <Check size={14} /> : <Copy size={14} />}{t("Copiar resposta")}</button>}</>}</article>)}</div>}
 </div><form className="composer" onSubmit={(e) => {e.preventDefault();send();}}><div>{mode === 'chat' && <ChatAttachments items={attachments} onChange={setAttachments} disabled={busy} onLoading={setAttachmentLoading} />}</div><label className="sr-only" htmlFor="question">{t("Sua pergunta m\xE9dica")}</label><textarea ref={input} id="question" placeholder={PRODUCT.doctor ? t("Pergunte ou descreva uma d\xFAvida cl\xEDnica\u2026") : "O que você quer entender em Medicina?"} value={question} maxLength={2000} rows={2} onChange={(e) => setQuestion(e.target.value)} onKeyDown={(e) => {if (e.key === 'Enter' && !e.shiftKey) {e.preventDefault();send();}}} /><div className="composer-bottom"><button type="button" className="case-shortcut" onClick={() => {setCaseDraft(question);setCaseMounted(true);setCaseOpen(true);}}>{t("Discutir caso \xB7 texto ou \xE1udio")}</button><span><Search size={14} />{mode === 'chat' ? PRODUCT.name : 'Pesquisa científica'}</span>{busy ? <button type="button" className="send" title={t("Interromper pesquisa")} aria-label={t("Interromper pesquisa")} onClick={() => abort.current?.abort()}><Square size={17} /></button> : <button className="send" disabled={attachmentLoading || question.trim().length < 3 && !attachments.length} title={t("Enviar pergunta")} aria-label={t("Enviar pergunta")}><ArrowUp size={20} /></button>}</div></form>{PRODUCT.doctor && messages.length === 0 && view === 'chat' && <QuickActions navigate={navigate} onCase={() => {setCaseDraft(question);setCaseMounted(true);setCaseOpen(true);}} onPrompt={(text) => {setQuestion(text);input.current?.focus();}} />}<div className="history-save-status" role="status">{historyStore.loading ? t("Carregando hist\xF3rico\u2026") : historyStore.error ? <><span>{historyStore.error}</span><button onClick={historyStore.flush}>{t("Tentar salvar")}</button></> : historyStore.saving ? t("Salvando conversa\u2026") : historyStore.saved ? t("Conversa salva na sua conta") : session?.authenticated ? t("O chat \xE9 salvo automaticamente.") : t("Entre para salvar suas conversas.")}</div><p className="disclaimer">{t("Prot\xF3tipo educacional. Confira as fontes. N\xE3o inclua dados que identifiquem pacientes.")}</p></section></main></div>{PRODUCT.doctor && !['chat', 'pesquisa', 'inovacoes', 'pais', 'desafio', 'evidencias'].includes(module) && <LibraryLanguageNotice />}<Modules active={module} session={session} onLogin={() => setLogin(true)} progress={progress} caseKey={caseKey} onProgress={recordProgress} onCasePending={markModuleCase} />
 </div>{PRODUCT.doctor && <MobileNavigation module={module} onNavigate={navigate} onMenu={openMenu}/>} {historyStore.open && <ChatHistory history={historyStore} onClose={() => historyStore.setOpen(false)} onNew={reset} onSelect={openHistory} />} {caseMounted && <div hidden={!caseOpen} className="case-conversation"><header><strong>{t('Discutir um caso')} · {PRODUCT.name}</strong><button aria-label="Voltar à conversa" onClick={() => setCaseOpen(false)}>Voltar à conversa ×</button></header>{PRODUCT.doctor && <LibraryLanguageNotice />}<Suspense fallback={<p>Preparando caso…</p>}><ClinicalCase key={caseKey} initialStory={caseDraft} active={caseOpen} onPendingChange={markDialogCase} session={session} onLogin={() => setLogin(true)} onProgress={recordProgress} /></Suspense></div>}{privacy !== null && <PrivacyReview text={privacy} actionLabel={t("Usar e enviar")} onCancel={() => setPrivacy(null)} onApply={(text) => {setPrivacy(null);setQuestion(text);send(text, false, true);}} />}{settings && <div className="modal-shade" onClick={() => setSettings(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="connections-title" onClick={(e) => e.stopPropagation()}><button autoFocus className="icon-btn close" aria-label={t("Fechar conex\xF5es")} onClick={() => setSettings(false)}><X /></button><span className="eyebrow blue">{PRODUCT.name} LAB</span><h2 id="connections-title">{t("Conex\xF5es da plataforma")}</h2><p>{t("Os servi\xE7os s\xE3o independentes. As chaves ficam exclusivamente no servidor.")}</p>{[[t("Literatura cient\xEDfica"), 'Europe PMC', status?.offline ? 'API local desconectada' : t("Conector de busca dispon\xEDvel")], [t("Ordena\xE7\xE3o inteligente"), 'Jev · TypeSafe', status?.jev === 'configured' ? 'Chave configurada · validação pendente' : t("Aguardando acesso \xE0 API")], [t("Chat m\xE9dico"), t("Assistente Vytal Acad\xEAmico"), status?.synthesis === 'vytal-assistant' ? t("API integrada \xB7 exige login") : t("Verificando conex\xE3o")], [t("Conta Vytal"), t("Mesmo e-mail e senha"), session?.authenticated ? t("Sess\xE3o ativa") : t("Entre para conversar")]].map(([t, v, s]) => <div className="connection-row" key={t}><div><strong>{t}</strong><span>{v}</span></div><small>{s}</small></div>)}<p className="modal-note">{t("As conversas do chat s\xE3o salvas na sua conta Vytal. Use o hist\xF3rico para retomar em outro aparelho.")} </p>{accountError && <p role="alert" className="error">{accountError}</p>}{session?.authenticated ? <button className="auth-submit" onClick={logout}>{t('Sair desta sessão')} {PRODUCT.name}</button> : <button className="auth-submit" onClick={() => {setSettings(false);setLogin(true);}}>{t("Entrar com conta Vytal")}</button>}</section></div>}{login && <AuthDialog product={PRODUCT} api={API} onClose={() => {setLogin(false);setPending('');}} onSuccess={(data) => {setSession(data);setLogin(false);const q = pending;setPending('');if (q) send(q, true);}} />}</div>;
}
createRoot(document.getElementById('root')).render(<I18nProvider enabled={PRODUCT.doctor}><App /></I18nProvider>);
