import React,{useState,useEffect,useRef,useCallback,lazy,Suspense} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUp,ArrowUpRight,Plus,Search,BookOpen,SlidersHorizontal,X,Square,Check,Copy,ChevronRight,Activity,Palette,History,Languages} from 'lucide-react';
import ReactMarkdown from 'react-markdown';import remarkGfm from 'remark-gfm';
import {loadProgress,saveProgress} from '../shared/progress.mjs';
import Modules,{moduleItems} from './Modules';import './modules.css';
import PrivacyReview from './PrivacyReview';
import ChatHistory,{useChatHistory} from './ChatHistory';
import {reviewPrivacy} from '../shared/privacy-review.mjs';
import {contextTools} from '../shared/context-tools.mjs';
const ClinicalCase=lazy(()=>import('./ClinicalCase'));
import ChatAttachments from './ChatAttachments';
import {chatContent} from '../shared/chat-content.mjs';
import './chat-attachments.css';
import AuthDialog from './AuthDialog';import {t,msg,lang,setLang,LANGS} from './i18n';import {favorites} from './favorites';import './styles.css';import './chat-design.css';import './theme-system.css';
const BASE=import.meta.env.BASE_URL;const PUBLIC=import.meta.env.VITE_PUBLIC_PREVIEW==='true';const API=PUBLIC?'/api/wmed':'/api';
const prompts=[msg('Explique a insuficiência mitral'),msg('Compare asma e DPOC'),msg('Como interpretar o escore de Wells?')];
async function readEvents(body,handler){const reader=body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let end;while((end=buffer.indexOf('\n\n'))>=0){const b=buffer.slice(0,end);buffer=buffer.slice(end+2);const event=b.split('\n').find(s=>s.startsWith('event:'))?.slice(6).trim();const d=b.split('\n').filter(s=>s.startsWith('data:')).map(s=>s.slice(5)).join('\n');if(d)handler(event,JSON.parse(d));}}}
function CitationText({text,sources,mode}){const prepared=mode==='chat'?chatContent(text).text:text.replace(/\[(\d+)\](?!\()/g,(match,n)=>sources[n-1]?`[${n}](${sources[n-1].url})`:t('[referência indisponível]'));const urls=new Set(sources.map(s=>s.url));return <ReactMarkdown remarkPlugins={[remarkGfm]} components={{a:({href,children})=>(urls.has(href)||(mode==='chat'&&/^https:\/\//.test(href||'')))?<a href={href} target="_blank" rel="noopener noreferrer">{children}</a>:<span>{children}</span>,img:()=>null}}>{prepared}</ReactMarkdown>;}
function Source({s,i}){return <a className="source" href={s.url} target="_blank" rel="noopener noreferrer"><span className="source-index">{String(i+1).padStart(2,'0')}</span><div><div className="source-meta">{s.year} <span>·</span> {s.journal||'Europe PMC'}</div><h4>{s.title}</h4><span className="source-authors">{s.authors}</span></div><ArrowUpRight size={17}/></a>;}
const themes=[['white',msg('Branco')],['dark',msg('Escuro')],['blue',msg('Azul')],['green',msg('Verde')]];
function App(){
 const [theme,setTheme]=useState(()=>{try{const saved=localStorage.getItem('wmed-theme');return themes.some(([id])=>id===saved)?saved:'white';}catch{return 'white';}});
 useEffect(()=>{document.documentElement.dataset.theme=theme;try{localStorage.setItem('wmed-theme',theme);}catch{}},[theme]);
 const [module,setModule]=useState(location.hash.slice(1).split('?')[0]||'chat'),[menu,setMenu]=useState(false),[route,setRoute]=useState(location.hash),[progress,setProgress]=useState([]),[caseKey,setCaseKey]=useState(0);
 useEffect(()=>{const change=()=>{setRoute(location.hash);const [next,query]=location.hash.slice(1).split('?');setModule(moduleItems.some(m=>m.id===next)?next:'chat');const topic=new URLSearchParams(query).get('tema');if(topic)setQuestion(topic);setMenu(false);};addEventListener('hashchange',change);return()=>removeEventListener('hashchange',change);},[]);
 function navigate(id){location.hash=id;setModule(id);setMenu(false);}

 const [caseWork,setCaseWork]=useState({module:false,dialog:false});
 const markModuleCase=useCallback(value=>setCaseWork(old=>old.module===value?old:{...old,module:value}),[]);
 const markDialogCase=useCallback(value=>setCaseWork(old=>old.dialog===value?old:{...old,dialog:value}),[]);
 const [privacy,setPrivacy]=useState(null),[caseOpen,setCaseOpen]=useState(false),[caseMounted,setCaseMounted]=useState(false),[caseDraft,setCaseDraft]=useState('');
 const [attachments,setAttachments]=useState([]),[attachmentLoading,setAttachmentLoading]=useState(false);
 const [question,setQuestion]=useState(''),[messages,setMessages]=useState([]),[busy,setBusy]=useState(false),[status,setStatus]=useState(null),[settings,setSettings]=useState(false),[view,setView]=useState('chat'),[copied,setCopied]=useState(''),[mode,setMode]=useState('chat'),[session,setSession]=useState(null),[login,setLogin]=useState(false),[pending,setPending]=useState(''),[accountError,setAccountError]=useState('');
 const historyStore=useChatHistory({api:API,scope:session?.user?.progressScope,messages,setMessages,busy});
 useEffect(()=>{try{setProgress(loadProgress(localStorage,session?.user?.progressScope));}catch{setProgress([]);}},[session?.user?.progressScope]);
 useEffect(()=>{favorites.setSession(!!session?.authenticated,()=>setLogin(true));},[session?.authenticated,session?.user?.progressScope]);
 function recordProgress(score){setProgress(previous=>{const next=[...previous,{score,date:new Date().toISOString()}];try{saveProgress(localStorage,session?.user?.progressScope,next);}catch{}return next;});}
 const abort=useRef(null),scroll=useRef(null),input=useRef(null),busyRef=useRef(false),pinned=useRef(true);
 useEffect(()=>{fetch(`${API}/auth`).then(r=>r.ok?r.json():Promise.reject()).then(d=>setSession(d.authenticated?d:null)).catch(()=>setSession(null));fetch(`${API}/status`).then(r=>r.ok?r.json():Promise.reject()).then(setStatus).catch(()=>setStatus({offline:true}));return()=>abort.current?.abort();},[]);
 useEffect(()=>{const track=()=>{pinned.current=document.documentElement.scrollHeight-window.scrollY-window.innerHeight<180;};addEventListener('scroll',track,{passive:true});return()=>removeEventListener('scroll',track);},[]);
 useEffect(()=>{if(pinned.current&&messages.length)window.scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'});},[messages,busy]);
 function update(id,patch){setMessages(ms=>ms.map(m=>m.id===id?{...m,...(typeof patch==='function'?patch(m):patch)}:m));}
 async function send(value=question,authenticated=false,reviewed=false){const q=mode==='chat'&&attachments.length&&value.trim().length<3?t('Explique o conteúdo dos arquivos enviados. ')+value.trim():value.trim();if(q.length<3||busyRef.current||historyStore.loading||attachmentLoading)return;if(!reviewed&&reviewPrivacy(q).spans.length){setPrivacy(q);return;}if(mode==='chat'&&!session?.authenticated&&!authenticated){setPending(q);setQuestion(q);setLogin(true);return;}busyRef.current=true;pinned.current=true;setBusy(true);setQuestion('');setView('chat');const id=crypto.randomUUID();const controller=new AbortController();abort.current=controller;
 const sentAttachments=mode==='chat'?attachments:[];
 const displayQuestion=q+(sentAttachments.length?'\n\n'+t('[Arquivos enviados: {nomes}. Arquivos não disponíveis no histórico; reenvie se precisar analisar novamente.]',{nomes:sentAttachments.map(a=>a.name).join(', ')}):'');
 const history=messages.filter(m=>m.mode==='chat'&&!m.error&&(m.role==='user'||(m.text&&m.complete))).slice(-6).map(m=>({role:m.role,content:chatContent(m.text||'').text.slice(0,6000)}));
 setMessages(ms=>[...ms,{id:id+'u',role:'user',text:displayQuestion,mode},{id,role:'assistant',text:'',mode,sources:[],progress:mode==='chat'?t('Conectando ao assistente…'):t('Iniciando pesquisa…')}]);
 try{const res=await fetch(`${API}/${mode==='chat'?'chat':'research'}`,{method:'POST',headers:{'Content-Type':'application/json','X-WMed-Request':'1','X-WMed-Lang':lang},body:JSON.stringify({question:q,history,lang,...(sentAttachments.length?{attachments:sentAttachments}:{})}),signal:controller.signal});if(!res.ok){const j=await res.json();if(res.status===401){setSession(null);setPending(q);setQuestion(q);setLogin(true);}throw new Error(t(j.error||'Serviço indisponível.'));}
 let done=false;await readEvents(res.body,(event,data)=>{if(event==='progress')update(id,{progress:t(data.text)});if(event==='sources')update(id,{sources:data.sources,query:data.query,jev:data.jev,progress:t('Preparando resposta…')});if(event==='delta')update(id,m=>({text:m.text+data.text,progress:''}));if(event==='notice')update(id,{notice:t(data.text),progress:''});if(event==='error'){update(id,{error:t(data.text),progress:''});done=true;}if(event==='done'){setAttachments([]);update(id,{progress:'',complete:true});done=true;}});if(!done)throw new Error(t('A conexão foi interrompida. Tente novamente.'));
 }catch(e){update(id,{error:e.name==='AbortError'?t('Resposta interrompida por você.'):t(e.message),progress:''});}finally{setBusy(false);busyRef.current=false;abort.current=null;}
 }
 async function logout(){setAccountError('');if(attachmentLoading){setAccountError(t('Aguarde o preparo dos arquivos antes de sair.'));return;}if(caseWork.module||caseWork.dialog){setAccountError(t('Aguarde a análise e o salvamento do caso antes de sair. Se houve falha, abra o caso e tente salvar novamente.'));return;}if(busyRef.current){setAccountError(t('Interrompa a resposta antes de sair.'));return;}if(!await historyStore.flush()){setAccountError(t('Salve a conversa antes de sair.'));return;}try{const r=await fetch(`${API}/auth`,{method:'DELETE',headers:{'X-WMed-Request':'1','X-WMed-Lang':lang}});if(!r.ok)throw Error();setSession(null);setAttachments([]);setSettings(false);setProgress([]);setCaseKey(n=>n+1);setCaseMounted(false);setCaseOpen(false);setMessages([]);setQuestion('');navigate('chat');setView('chat');}catch{setAccountError(t('Não foi possível sair. Tente novamente.'));}}
 async function reset(){if(attachmentLoading||busyRef.current||!await historyStore.fresh())return;navigate('chat');setAttachments([]);setMessages([]);setQuestion('');setView('chat');window.scrollTo(0,0);input.current?.focus();}
 function showHistory(){if(!session?.authenticated){setLogin(true);return;}historyStore.setOpen(true);historyStore.refresh();}
 async function openHistory(id){if(attachmentLoading)return;if(await historyStore.select(id)){navigate('chat');setMode('chat');setAttachments([]);setView('chat');setQuestion('');window.scrollTo(0,0);}}
 const allSources=[...new Map(messages.flatMap(m=>m.sources??[]).map(s=>[s.id,s])).values()];
 return <div className={`app-shell ${module==='chat'?'is-chat':'is-module'}`}><aside className="rail"><a href="#" aria-label={t("WMed início")} onClick={e=>{e.preventDefault();reset();}}><img src={`${BASE}brand/favicon.svg`} alt="WMed"/></a><button title={t("Nova conversa")} aria-label={t("Nova conversa")} onClick={reset}><Plus/></button><button title={t("Histórico de conversas")} aria-label={t("Histórico de conversas")} disabled={busy} onClick={showHistory}><History size={21}/></button><div className="rail-divider"/><button className={module==='chat'&&view==='chat'?'active':''} title={t("Conversa")} aria-label={t("Conversa")} onClick={()=>{navigate('chat');setView('chat');}}><Search size={21}/></button><button className={view==='sources'?'active':''} title={t("Fontes desta sessão")} aria-label={t("Fontes desta sessão")} onClick={()=>{navigate('chat');setView('sources');}}><BookOpen size={21}/></button><div className="rail-spacer"/><button title={t("Conexões")} aria-label={t("Conexões")} onClick={()=>setSettings(true)}><SlidersHorizontal size={20}/></button><button className="profile" title={t("Conta WMed")} aria-label={t("Conta WMed")} onClick={()=>session?.authenticated?setSettings(true):setLogin(true)}>{session?.user?.nome?.[0]||'W'}</button></aside>
 <div className="workspace"><header className="topbar"><a className="wordmark" href="#chat" aria-label={t("WMed início")}><img src={`${BASE}brand/favicon.svg`} alt=""/><strong>WMed</strong></a><span className="version">WMED</span><button className="modules-toggle" aria-label={t("Matérias e ferramentas")} aria-expanded={menu} onClick={()=>setMenu(v=>!v)}>☰ <span>{t("Matérias e ferramentas")}</span></button><button className="mobile-new" aria-label={t("Nova conversa")} title={t("Nova conversa")} onClick={reset}><Plus size={20}/></button><button className="mobile-history" title={t("Histórico de conversas")} aria-label={t("Histórico de conversas")} disabled={busy} onClick={showHistory}><History size={20}/></button><div className="top-spacer"/><details className="theme-picker"><summary aria-label={t("Escolher aparência")}><Palette size={19}/><span className="theme-label">{t("Aparência")}</span></summary><div className="theme-options" role="group" aria-label={t("Tema de cores")}>{themes.map(([id,label])=><button key={id} aria-pressed={theme===id} onClick={e=>{setTheme(id);e.currentTarget.closest('details').open=false;}}><span className={`theme-dot ${id}`}/>{t(label)}{theme===id&&<Check size={15}/>}</button>)}</div></details><details className="theme-picker lang-picker"><summary aria-label={t("Idioma")}><Languages size={19}/><span className="theme-label">{lang.toUpperCase()}</span></summary><div className="theme-options" role="group" aria-label={t("Idioma")}>{LANGS.map(([id,label])=><button key={id} lang={id} aria-pressed={lang===id} onClick={()=>setLang(id)}>{label}{lang===id&&<Check size={15}/>}</button>)}</div></details><button className="account-button" onClick={()=>session?.authenticated?setSettings(true):setLogin(true)}>{session?.authenticated?(session.user?.nome||t('Minha conta')):t('Entrar')}</button><button className="connection" onClick={()=>setSettings(true)}><span className={'dot '+(status?.offline?'warn':'')}/>{status?.offline?t('API desconectada'):(PUBLIC?t('Prévia WMed'):t('Ambiente de desenvolvimento'))}</button></header>
 {menu&&<nav className="modules-menu" aria-label={t("Matérias e ferramentas")}>{moduleItems.map(m=><button key={m.id} className={module===m.id?'active':''} onClick={()=>navigate(m.id)}><m.icon size={20}/><span>{t(m.label)}<small>{t(m.description)}</small></span></button>)}</nav>}<div className="module-breadcrumb"><span>{t(moduleItems.find(m=>m.id===module)?.label||msg('Chat com IA'))}</span>{module!=='chat'&&<button onClick={()=>navigate('chat')}>{t('Voltar ao chat ↗')}</button>}</div><div hidden={module!=='chat'} className="chat-container"><main className="content wide chat-first"><section className="research-panel"><div className="conversation" ref={scroll} onScroll={e=>{const el=e.currentTarget;pinned.current=el.scrollHeight-el.scrollTop-el.clientHeight<90;}}>
 {view==='sources'?<div className="library"><h1>{t("Sua pesquisa,")}<br/>{t("com origem.")}</h1><p>{t("Publicações encontradas nesta sessão. Abrir a fonte permite conferir o contexto original.")}</p>{allSources.length?allSources.map((s,i)=><Source key={s.id} s={s} i={i}/>):<div className="empty">{t("Faça sua primeira pergunta para reunir as referências aqui.")}</div>}</div>:messages.length===0?<div className="welcome"><div className="welcome-icon"><Activity size={24}/></div><div className="eyebrow blue">{t("DA EVIDÊNCIA À COMPREENSÃO")}</div><h1>{t("Como posso ajudar?")}</h1><p>{t("Pergunte, pesquise ou discuta um caso clínico.")}</p><div className="prompt-list">{prompts.map(p=>t(p)).map((p,i)=><button key={p} onClick={()=>send(p)}><span className="prompt-num">0{i+1}</span><span>{p}</span><ArrowUpRight size={17}/></button>)}</div><div className="welcome-foot"><span className="dot"/>{t("Para estudantes e profissionais de saúde.")}</div></div>:<div className="messages">{messages.map(m=><article key={m.id} className={'message '+m.role}>{m.role==='user'?<div className="user-bubble">{m.text}</div>:<><div className="assistant-label"><img src={`${BASE}brand/favicon.svg`} alt=""/>WMed <span>{m.mode==='chat'?t('Assistente WMed'):t('Pesquisa')}</span></div>{m.progress&&<div className="progress"><span className="spinner"/>{m.progress}</div>}{m.text&&<div className="markdown"><CitationText text={m.text} sources={m.sources} mode={m.mode}/></div>}{m.notice&&<p className="notice">{m.notice}</p>}{m.error&&<div role="alert" className="error">{m.error}</div>}{m.sources?.length>0&&<details open={!m.text}><summary>{t("{n} fontes encontradas",{n:m.sources.length})} <ChevronRight size={16}/></summary>{m.sources.map((s,i)=><Source key={s.id} s={s} i={i}/>)}</details>}{m.query&&<details className="query"><summary>{t('Ver termos pesquisados')}</summary><p>{m.query}</p><small>{t('Ordenação:')} {m.jev==='ranked'?t('Jev · relevância textual'):t('Europe PMC · relevância da busca')}. {t('Relevância não é qualidade clínica.')}</small></details>}{m.mode==='chat'&&m.complete&&chatContent(m.text).topics.length>0&&<div className="chat-topics"><small>{t("Continue estudando")}</small>{chatContent(m.text).topics.map(topic=><button key={topic} disabled={busy||attachmentLoading} onClick={()=>send(topic)}>{topic}</button>)}</div>}{m.complete&&m.text&&<div className="context-tools" aria-label={t("Recursos para aprofundar")}>{contextTools(m.text).map(tool=><button key={tool.id} onClick={()=>navigate(tool.id)}>{t(tool.label)}<ArrowUpRight size={14}/></button>)}</div>}{m.text&&<button className="copy" onClick={async()=>{try{await navigator.clipboard.writeText(m.mode==='chat'?chatContent(m.text).text:m.text);setCopied(m.id);}catch{setCopied('');}}}>{copied===m.id?<Check size={14}/>:<Copy size={14}/>}{t("Copiar resposta")}</button>}</>}</article>)}</div>}
 </div><form className="composer" onSubmit={e=>{e.preventDefault();send();}}><div>{mode==='chat'&&<ChatAttachments items={attachments} onChange={setAttachments} disabled={busy} onLoading={setAttachmentLoading}/>}</div><label className="sr-only" htmlFor="question">{t("Sua pergunta médica")}</label><textarea ref={input} id="question" placeholder={t("O que você quer entender em Medicina?")} value={question} maxLength={2000} rows={2} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}}}/><div className="composer-bottom"><button type="button" className="case-shortcut" onClick={()=>{setCaseDraft(question);setCaseMounted(true);setCaseOpen(true)}}>{t("Discutir caso · texto ou áudio")}</button><span><Search size={14}/>{mode==='chat'?t('WMed · conversa'):t('Pesquisa científica')}</span>{busy?<button type="button" className="send" title={t("Interromper pesquisa")} aria-label={t("Interromper pesquisa")} onClick={()=>abort.current?.abort()}><Square size={17}/></button>:<button className="send" disabled={attachmentLoading||(question.trim().length<3&&!attachments.length)} title={t("Enviar pergunta")} aria-label={t("Enviar pergunta")}><ArrowUp size={20}/></button>}</div></form><div className="history-save-status" role="status">{historyStore.loading?t('Carregando histórico…'):historyStore.error?<><span>{t(historyStore.error)}</span><button onClick={historyStore.flush}>{t('Tentar salvar')}</button></>:historyStore.saving?t('Salvando conversa…'):historyStore.saved?t('Conversa salva na sua conta'):session?.authenticated?t('O chat é salvo automaticamente.'):t('Entre para salvar suas conversas.')}</div><p className="disclaimer">{t("Protótipo educacional. Confira as fontes. Não inclua dados que identifiquem pacientes.")}</p></section></main></div><Modules active={module} route={route} session={session} onLogin={()=>setLogin(true)} progress={progress} caseKey={caseKey} onProgress={recordProgress} onCasePending={markModuleCase}/>
 </div>{historyStore.open&&<ChatHistory history={historyStore} onClose={()=>historyStore.setOpen(false)} onNew={reset} onSelect={openHistory}/>} {caseMounted&&<div hidden={!caseOpen} className="case-conversation"><header><strong>{t("Discutir caso com WMed")}</strong><button aria-label={t("Voltar à conversa")} onClick={()=>setCaseOpen(false)}>{t("Voltar à conversa ×")}</button></header><Suspense fallback={<p>{t("Preparando caso…")}</p>}><ClinicalCase key={caseKey} initialStory={caseDraft} active={caseOpen} onPendingChange={markDialogCase} session={session} onLogin={()=>setLogin(true)} onProgress={recordProgress}/></Suspense></div>}{privacy!==null&&<PrivacyReview text={privacy} actionLabel={t("Usar e enviar")} onCancel={()=>setPrivacy(null)} onApply={text=>{setPrivacy(null);setQuestion(text);send(text,false,true)}}/>}{settings&&<div className="modal-shade" onClick={()=>setSettings(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="connections-title" onClick={e=>e.stopPropagation()}><button autoFocus className="icon-btn close" aria-label={t("Fechar conexões")} onClick={()=>setSettings(false)}><X/></button><span className="eyebrow blue">WMED LAB</span><h2 id="connections-title">{t("Conexões da plataforma")}</h2><p>{t("Os serviços são independentes. As chaves ficam exclusivamente no servidor.")}</p>{[[msg('Literatura científica'),'Europe PMC',status?.offline?msg('API local desconectada'):msg('Conector de busca disponível')],[msg('Ordenação inteligente'),'Jev · TypeSafe',status?.jev==='configured'?msg('Chave configurada · validação pendente'):msg('Aguardando acesso à API')],[msg('Chat médico'),'Claude · Anthropic',status?.synthesis==='claude'?msg('Conectado · exige conta WMed'):msg('Aguardando configuração')],[msg('Conta WMed'),session?.authenticated?session.user?.email||'':msg('E-mail e senha'),session?.authenticated?(session.user?.plan==='pro'?msg('Plano Pro · perguntas ilimitadas'):msg('Plano gratuito · perguntas diárias limitadas')):msg('Entre para conversar')]].map(([name,v,s])=><div className="connection-row" key={name}><div><strong>{t(name)}</strong><span>{t(v)}</span></div><small>{t(s)}</small></div>)}<p className="modal-note">{t("As conversas do chat são salvas na sua conta WMed. Use o histórico para retomar em outro aparelho.")}</p>{accountError&&<p role="alert" className="error">{accountError}</p>}{session?.authenticated?<button className="auth-submit" onClick={logout}>{t("Sair desta sessão WMed")}</button>:<button className="auth-submit" onClick={()=>{setSettings(false);setLogin(true);}}>{t("Entrar ou criar conta WMed")}</button>}</section></div>}{login&&<AuthDialog api={API} onClose={()=>{setLogin(false);setPending('');}} onSuccess={data=>{setSession(data);setLogin(false);const q=pending;setPending('');if(q)send(q,true);}}/>}</div>;
}
createRoot(document.getElementById('root')).render(<App/>);
// Offline: em wmed.ai o app fica na raiz (sw.js reescrito para /wmed/sw.js); no site Vytal, em /wmed/.
if(import.meta.env.PROD&&'serviceWorker' in navigator)addEventListener('load',()=>navigator.serviceWorker.register(location.pathname.startsWith(BASE)?`${BASE}sw.js`:'/sw.js').catch(()=>{}));
