import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUp,ArrowUpRight,Plus,Search,Box,BookOpen,SlidersHorizontal,X,PanelRightClose,PanelRightOpen,Square,Check,Copy,ChevronRight,Activity} from 'lucide-react';
import ReactMarkdown from 'react-markdown';import remarkGfm from 'remark-gfm';
import AuthDialog from './AuthDialog';import Viewer from './Viewer';import './styles.css';
const BASE=import.meta.env.BASE_URL;const PUBLIC=import.meta.env.VITE_PUBLIC_PREVIEW==='true';const API=PUBLIC?'/api/wmed':'/api';
const prompts=['Como ocorre a contração dos cardiomiócitos?','Como os cílios protegem as vias aéreas?','Como os neurônios transmitem sinais?'];
async function readEvents(body,handler){const reader=body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let end;while((end=buffer.indexOf('\n\n'))>=0){const b=buffer.slice(0,end);buffer=buffer.slice(end+2);const event=b.split('\n').find(s=>s.startsWith('event:'))?.slice(6).trim();const d=b.split('\n').filter(s=>s.startsWith('data:')).map(s=>s.slice(5)).join('\n');if(d)handler(event,JSON.parse(d));}}}
function CitationText({text,sources,mode}){const prepared=mode==='chat'?text:text.replace(/\[(\d+)\](?!\()/g,(match,n)=>sources[n-1]?`[${n}](${sources[n-1].url})`:'[referência indisponível]');const urls=new Set(sources.map(s=>s.url));return <ReactMarkdown remarkPlugins={[remarkGfm]} components={{a:({href,children})=>(urls.has(href)||(mode==='chat'&&/^https:\/\//.test(href||'')))?<a href={href} target="_blank" rel="noopener noreferrer">{children}</a>:<span>{children}</span>,img:()=>null}}>{prepared}</ReactMarkdown>;}
function Source({s,i}){return <a className="source" href={s.url} target="_blank" rel="noopener noreferrer"><span className="source-index">{String(i+1).padStart(2,'0')}</span><div><div className="source-meta">{s.year} <span>·</span> {s.journal||'Europe PMC'}</div><h4>{s.title}</h4><span className="source-authors">{s.authors}</span></div><ArrowUpRight size={17}/></a>;}
function App(){
 const [question,setQuestion]=useState(''),[messages,setMessages]=useState([]),[busy,setBusy]=useState(false),[status,setStatus]=useState(null),[settings,setSettings]=useState(false),[model,setModel]=useState('cardiomiocito'),[show3d,setShow3d]=useState(true),[view,setView]=useState('chat'),[copied,setCopied]=useState(''),[mode,setMode]=useState('chat'),[session,setSession]=useState(null),[login,setLogin]=useState(false),[pending,setPending]=useState(''),[accountError,setAccountError]=useState('');
 const abort=useRef(null),scroll=useRef(null),input=useRef(null),busyRef=useRef(false),pinned=useRef(true);
 useEffect(()=>{fetch(`${API}/auth`).then(r=>r.ok?r.json():Promise.reject()).then(d=>setSession(d.authenticated?d:null)).catch(()=>setSession(null));fetch(`${API}/status`).then(r=>r.ok?r.json():Promise.reject()).then(setStatus).catch(()=>setStatus({offline:true}));return()=>abort.current?.abort();},[]);
 useEffect(()=>{const el=scroll.current;if(el&&pinned.current)el.scrollTop=el.scrollHeight;},[messages,busy]);
 function update(id,patch){setMessages(ms=>ms.map(m=>m.id===id?{...m,...(typeof patch==='function'?patch(m):patch)}:m));}
 async function send(value=question,authenticated=false){const q=value.trim();if(q.length<3||busyRef.current)return;if(mode==='chat'&&!session?.authenticated&&!authenticated){setPending(q);setQuestion(q);setLogin(true);return;}busyRef.current=true;pinned.current=true;setBusy(true);setQuestion('');setView('chat');const id=crypto.randomUUID();const controller=new AbortController();abort.current=controller;
 if(/cíli|ciliad|vias aéreas/i.test(q))setModel('ciliada');else if(/neuron|neurôn/i.test(q))setModel('neuronio');else if(/cardio|cardí/i.test(q))setModel('cardiomiocito');
 const history=messages.filter(m=>m.mode==='chat'&&!m.error&&(m.role==='user'||(m.text&&m.complete))).slice(-6).map(m=>({role:m.role,content:(m.text||'').slice(0,6000)}));
 setMessages(ms=>[...ms,{id:id+'u',role:'user',text:q,mode},{id,role:'assistant',text:'',mode,sources:[],progress:mode==='chat'?'Conectando ao assistente…':'Iniciando pesquisa…'}]);
 try{const res=await fetch(`${API}/${mode==='chat'?'chat':'research'}`,{method:'POST',headers:{'Content-Type':'application/json','X-WMed-Request':'1'},body:JSON.stringify({question:q,history}),signal:controller.signal});if(!res.ok){const j=await res.json();if(res.status===401){setSession(null);setPending(q);setQuestion(q);setLogin(true);}throw new Error(j.error||'Serviço indisponível.');}
 let done=false;await readEvents(res.body,(event,data)=>{if(event==='progress')update(id,{progress:data.text});if(event==='sources')update(id,{sources:data.sources,query:data.query,jev:data.jev,progress:'Preparando resposta…'});if(event==='delta')update(id,m=>({text:m.text+data.text,progress:''}));if(event==='notice')update(id,{notice:data.text,progress:''});if(event==='error'){update(id,{error:data.text,progress:''});done=true;}if(event==='done'){update(id,{progress:'',complete:true});done=true;}});if(!done)throw new Error('A conexão foi interrompida. Tente novamente.');
 }catch(e){update(id,{error:e.name==='AbortError'?'Resposta interrompida por você.':e.message,progress:''});}finally{setBusy(false);busyRef.current=false;abort.current=null;}
 }
 async function logout(){setAccountError('');abort.current?.abort();try{const r=await fetch(`${API}/auth`,{method:'DELETE',headers:{'X-WMed-Request':'1'}});if(!r.ok)throw Error();setSession(null);setSettings(false);reset();}catch{setAccountError('Não foi possível sair. Tente novamente.');}}
 function reset(){abort.current?.abort();setMessages([]);setQuestion('');setView('chat');input.current?.focus();}
 const allSources=[...new Map(messages.flatMap(m=>m.sources??[]).map(s=>[s.id,s])).values()];
 return <div className="app-shell"><aside className="rail"><a href="#" aria-label="WMed início" onClick={e=>{e.preventDefault();reset();}}><img src={`${BASE}brand/favicon.svg`} alt="WMed"/></a><button title="Nova conversa" aria-label="Nova conversa" onClick={reset}><Plus/></button><div className="rail-divider"/><button className={view==='chat'?'active':''} title="Conversa" aria-label="Conversa" onClick={()=>setView('chat')}><Search size={21}/></button><button title="Explorar em 3D" aria-label="Explorar em 3D" className={show3d?'active-sub':''} onClick={()=>setShow3d(v=>!v)}><Box size={21}/></button><button className={view==='sources'?'active':''} title="Fontes desta sessão" aria-label="Fontes desta sessão" onClick={()=>setView('sources')}><BookOpen size={21}/></button><div className="rail-spacer"/><button title="Conexões" aria-label="Conexões" onClick={()=>setSettings(true)}><SlidersHorizontal size={20}/></button><button className="profile" title="Conta Vytal" aria-label="Conta Vytal" onClick={()=>session?.authenticated?setSettings(true):setLogin(true)}>{session?.user?.nome?.[0]||'W'}</button></aside>
 <div className="workspace"><header className="topbar"><img src={`${BASE}brand/logo.svg`} alt="WMed"/><span className="version">LAB / 01</span><div className="top-spacer"/><button className="account-button" onClick={()=>session?.authenticated?setSettings(true):setLogin(true)}>{session?.authenticated?(session.user?.nome||'Minha conta'):'Entrar'}</button><button className="connection" onClick={()=>setSettings(true)}><span className={'dot '+(status?.offline?'warn':'')}/>{status?.offline?'API desconectada':(PUBLIC?'Prévia WMed':'Ambiente de desenvolvimento')}</button><button className="icon-btn" aria-label={show3d?'Recolher 3D':'Mostrar 3D'} onClick={()=>setShow3d(v=>!v)}>{show3d?<PanelRightClose size={20}/>:<PanelRightOpen size={20}/>}</button></header>
 <main className={'content '+(!show3d?'wide':'')}><section className="research-panel"><div className="research-heading"><span className="eyebrow">INTELIGÊNCIA MÉDICA</span><div className="mode-tabs"><button disabled={busy} aria-pressed={mode==='chat'} onClick={()=>{setMode('chat');setView('chat');}}>Chat com IA</button><button disabled={busy} aria-pressed={mode==='research'} onClick={()=>{setMode('research');setView('chat');}}>Artigos</button></div></div><div className="conversation" ref={scroll} onScroll={e=>{const el=e.currentTarget;pinned.current=el.scrollHeight-el.scrollTop-el.clientHeight<90;}}>
 {view==='sources'?<div className="library"><h1>Sua pesquisa,<br/>com origem.</h1><p>Publicações encontradas nesta sessão. Abrir a fonte permite conferir o contexto original.</p>{allSources.length?allSources.map((s,i)=><Source key={s.id} s={s} i={i}/>):<div className="empty">Faça sua primeira pergunta para reunir as referências aqui.</div>}</div>:messages.length===0?<div className="welcome"><div className="welcome-icon"><Activity size={24}/></div><div className="eyebrow blue">DA EVIDÊNCIA À COMPREENSÃO</div><h1>Uma pergunta.<br/><span>Novas perspectivas.</span></h1><p>Converse com o assistente médico.<br/>Pesquise artigos e explore em 3D.</p><div className="prompt-list">{prompts.map((p,i)=><button key={p} onClick={()=>send(p)}><span className="prompt-num">0{i+1}</span><span>{p}</span><ArrowUpRight size={17}/></button>)}</div><div className="welcome-foot"><span className="dot"/>Artigos reais. Modelos 3D interativos.</div></div>:<div className="messages">{messages.map(m=><article key={m.id} className={'message '+m.role}>{m.role==='user'?<div className="user-bubble">{m.text}</div>:<><div className="assistant-label"><img src={`${BASE}brand/favicon.svg`} alt=""/>WMed <span>{m.mode==='chat'?'Assistente Vytal':'Pesquisa'}</span></div>{m.progress&&<div className="progress"><span className="spinner"/>{m.progress}</div>}{m.text&&<div className="markdown"><CitationText text={m.text} sources={m.sources} mode={m.mode}/></div>}{m.notice&&<p className="notice">{m.notice}</p>}{m.error&&<div role="alert" className="error">{m.error}</div>}{m.sources?.length>0&&<details open={!m.text}><summary>{m.sources.length} fontes encontradas <ChevronRight size={16}/></summary>{m.sources.map((s,i)=><Source key={s.id} s={s} i={i}/>)}</details>}{m.query&&<details className="query"><summary>Ver termos pesquisados</summary><p>{m.query}</p><small>Ordenação: {m.jev==='ranked'?'Jev · relevância textual':'Europe PMC · relevância da busca'}. Relevância não é qualidade clínica.</small></details>}{m.text&&<button className="copy" onClick={async()=>{try{await navigator.clipboard.writeText(m.text);setCopied(m.id);}catch{setCopied('');}}}>{copied===m.id?<Check size={14}/>:<Copy size={14}/>}Copiar resposta</button>}</>}</article>)}</div>}
 </div><form className="composer" onSubmit={e=>{e.preventDefault();send();}}><label className="sr-only" htmlFor="question">Sua pergunta médica</label><textarea ref={input} id="question" placeholder="O que você quer entender em Medicina?" value={question} maxLength={2000} rows={2} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}}}/><div className="composer-bottom"><span><Search size={14}/>{mode==='chat'?'Assistente Vytal Acadêmico':'Pesquisa científica'}</span>{busy?<button type="button" className="send" title="Interromper pesquisa" aria-label="Interromper pesquisa" onClick={()=>abort.current?.abort()}><Square size={17}/></button>:<button className="send" disabled={question.trim().length<3} title="Enviar pergunta" aria-label="Enviar pergunta"><ArrowUp size={20}/></button>}</div></form><p className="disclaimer">Protótipo educacional. Confira as fontes. Não insira dados de pacientes.</p></section>{show3d&&<Viewer model={model} setModel={setModel}/>}</main>
 </div>{settings&&<div className="modal-shade" onClick={()=>setSettings(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="connections-title" onClick={e=>e.stopPropagation()}><button autoFocus className="icon-btn close" aria-label="Fechar conexões" onClick={()=>setSettings(false)}><X/></button><span className="eyebrow blue">WMED LAB</span><h2 id="connections-title">Conexões da plataforma</h2><p>Os serviços são independentes. As chaves ficam exclusivamente no servidor.</p>{[['Literatura científica','Europe PMC',status?.offline?'API local desconectada':'Conector de busca disponível'],['Ordenação inteligente','Jev · TypeSafe',status?.jev==='configured'?'Chave configurada · validação pendente':'Aguardando acesso à API'],['Chat médico','Assistente Vytal Acadêmico',status?.synthesis==='vytal-assistant'?'API integrada · exige login':'Verificando conexão'],['Conta Vytal','Mesmo e-mail e senha',session?.authenticated?'Sessão ativa':'Entre para conversar']].map(([t,v,s])=><div className="connection-row" key={t}><div><strong>{t}</strong><span>{v}</span></div><small>{s}</small></div>)}<p className="modal-note">O histórico desta conversa é enviado ao assistente Vytal e fica nesta aba. Recarregar a página apaga o histórico local.</p>{accountError&&<p role="alert" className="error">{accountError}</p>}{session?.authenticated?<button className="auth-submit" onClick={logout}>Sair desta sessão WMed</button>:<button className="auth-submit" onClick={()=>{setSettings(false);setLogin(true);}}>Entrar com conta Vytal</button>}</section></div>}{login&&<AuthDialog api={API} onClose={()=>{setLogin(false);setPending('');}} onSuccess={data=>{setSession(data);setLogin(false);const q=pending;setPending('');if(q)send(q,true);}}/>}</div>;
}
createRoot(document.getElementById('root')).render(<App/>);
