import React,{useMemo,useState,useEffect,useRef} from 'react';
import {reviewPrivacy} from '../shared/privacy-review.mjs';
import {t} from './i18n';
export default function PrivacyReview({text,onCancel,onApply,actionLabel=t("Usar texto revisado")}){
 const [remote,setRemote]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const dialog=useRef(null),controller=useRef(null);
 useEffect(()=>{const previous=document.activeElement;dialog.current?.querySelector('textarea')?.focus();return()=>{controller.current?.abort();previous?.focus?.()}},[]);
 const api=import.meta.env.VITE_PUBLIC_PREVIEW==='true'?'/api/wmed':'/api';
 useEffect(()=>{let live=true;fetch(api+'/privacy').then(r=>r.ok?r.json():null).then(d=>{if(live)setRemote(d?.enabled===true)}).catch(()=>{});return()=>{live=false}},[]);
 async function advanced(){controller.current=new AbortController();setBusy(true);setNotice('');try{const r=await fetch(api+'/privacy',{method:'POST',signal:controller.current.signal,headers:{'Content-Type':'application/json','X-WMed-Request':'1'},body:JSON.stringify({text:draft})});const d=await r.json();if(!r.ok)throw Error(t(d.error||'Análise indisponível.'));let out=draft;const spans=d.findings.sort((a,b)=>a.start-b.start),merged=[];for(const f of spans){const last=merged.at(-1);if(last&&f.start<last.end)last.end=Math.max(last.end,f.end);else merged.push({...f})}for(const f of merged.reverse())out=out.slice(0,f.start)+t('[dado removido]')+out.slice(f.end);setDraft(out);setConfirmed(false);setNotice(t('OpenMed analisou o texto no servidor WMed. Revise as sugestões antes de continuar.'));}catch(e){setNotice(t(e.message))}finally{setBusy(false)}}
 const review=useMemo(()=>reviewPrivacy(text),[text]);const [draft,setDraft]=useState(review.text),[confirmed,setConfirmed]=useState(false);
 return <div className="modal-shade"><section ref={dialog} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();onCancel()}if(e.key==='Tab'){const nodes=[...dialog.current.querySelectorAll('button:not(:disabled),textarea:not(:disabled),input:not(:disabled)')];const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}} className="modal privacy-review" role="dialog" aria-modal="true" aria-labelledby="privacy-title"><h2 id="privacy-title">{t("Revise antes de enviar")}</h2><p>{t("Esta verificação acontece no navegador. A análise local não envia o texto.")}</p><p>{review.spans.length?t("{n} possível(is) dado(s) pessoal(is) marcado(s) para remoção.",{n:review.spans.length}):t("Nenhum identificador foi encontrado pelas regras locais.")} {t("A verificação pode deixar dados passar. Confira nomes, contatos e endereços.")}</p><p role="status">{notice}</p>{remote&&<button disabled={busy} onClick={advanced}>{busy?t("Analisando…"):t("Analisar no servidor WMed com OpenMed")}</button>}<label htmlFor="privacy-draft">{t("Texto que será utilizado")}</label><textarea disabled={busy} id="privacy-draft" rows={9} value={draft} onChange={e=>{setDraft(e.target.value);setConfirmed(false)}}/><label className="confirm-row"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{t("Revisei os dados pessoais e preservei as informações clínicas.")}</label><div className="privacy-actions"><button onClick={onCancel}>{t("Voltar")}</button><button className="auth-submit" disabled={busy||!confirmed||!draft.trim()} onClick={()=>onApply(draft)}>{actionLabel}</button></div><small>{t("Verificação local por regras. Não é garantia de anonimização.")}</small></section></div>
}
