import React,{useEffect,useRef,useState} from 'react';
import {RotateCcw,ScanLine,ArrowRight} from 'lucide-react';
import {bestProjection,ncc,tone} from './imaging.mjs';
export default function RegistrationPractice({data}){
 const BASE=data.baseUrl;
 const [images,setImages]=useState(null),[error,setError]=useState(false),[retry,setRetry]=useState(0),[target,setTarget]=useState(3),[candidate,setCandidate]=useState(0),[mode,setMode]=useState('fusion'),[reveal,setReveal]=useState(false),[search,setSearch]=useState(null);
 const canvas=useRef(null),refcanvas=useRef(null);
 useEffect(()=>{let stop=false;setImages(null);setError(false);Promise.all(data.views.map(v=>new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>{const c=document.createElement('canvas');c.width=c.height=data.size;const ctx=c.getContext('2d');ctx.drawImage(image,0,0);const rgba=ctx.getImageData(0,0,c.width,c.height).data;resolve(Uint8Array.from({length:data.size**2},(_,i)=>rgba[i*4]))};image.onerror=reject;image.src=BASE+v.image}))).then(x=>{if(!stop)setImages(x)}).catch(()=>{if(!stop)setError(true)});return()=>{stop=true}},[data,retry]);
 useEffect(()=>{if(!images)return;for(const [c,isReference]of[[canvas.current,false],[refcanvas.current,true]]){c.width=c.height=data.size;const ctx=c.getContext('2d'),out=ctx.createImageData(data.size,data.size),a=images[target],b=images[candidate];for(let i=0;i<a.length;i++){const x=tone(a[i]),y=tone(b[i]),o=i*4;if(isReference){out.data[o]=out.data[o+1]=out.data[o+2]=x}else if(mode==='fusion'){out.data[o]=x;out.data[o+1]=out.data[o+2]=y}else{out.data[o]=out.data[o+1]=out.data[o+2]=Math.min(255,Math.abs(x-y)*2)}out.data[o+3]=255}ctx.putImageData(out,0,0)}},[images,target,candidate,mode]);
 const score=images?ncc(images[target],images[candidate]):null;
 function next(){setTarget(t=>(t+2)%data.views.length);setCandidate(0);setReveal(false);setSearch(null)}
 return <div className="xr-registration"><div className="xr-registration-intro"><div><strong>Encontre a incidência da referência</strong><p>Mude o ângulo até os contornos coincidirem. Vermelho e ciano se unem em cinza no encaixe.</p></div><button onClick={next}><RotateCcw size={15}/>Novo desafio</button></div>{!images?<div role="status">{error?<><p>Não foi possível carregar as projeções.</p><button onClick={()=>setRetry(r=>r+1)}>Tentar novamente</button></>:'Preparando as sete projeções…'}</div>:<><div className="xr-registration-images"><article><header>REFERÊNCIA · INCIDÊNCIA {reveal?`${data.views[target].angle}°`:'OCULTA'}</header><canvas ref={refcanvas} aria-label="Projeção de referência para alinhar"/></article><article><header>{mode==='fusion'?'SOBREPOSIÇÃO · VERMELHO / CIANO':'DIFERENÇA · PRETO = COINCIDÊNCIA'}</header><canvas ref={canvas} aria-label="Comparação entre referência e incidência escolhida"/></article></div><div className="xr-registration-controls"><label>Seu ajuste <b>{data.views[candidate].angle}°</b><input type="range" min="0" max={data.views.length-1} value={candidate} onChange={e=>{setCandidate(+e.target.value);setSearch(null)}} aria-label="Incidência para alinhar" aria-valuetext={`${data.views[candidate].angle} graus`}/></label><div className="xr-presets"><button aria-pressed={mode==='fusion'} onClick={()=>setMode('fusion')}>Sobreposição</button><button aria-pressed={mode==='difference'} onClick={()=>setMode('difference')}>Diferença</button></div><button onClick={()=>setReveal(true)}>Conferir<ArrowRight size={15}/></button><button onClick={()=>{const found=bestProjection(images[target],images);setCandidate(found.index);setSearch(found);setReveal(true)}}><ScanLine size={15}/>Buscar entre 7 incidências</button></div><div className="xr-registration-result" aria-live="polite"><strong>Similaridade NCC: {score?.toFixed(3).replace('.',',')}</strong><span>{reveal?(candidate===target?'Incidência correta.':`Diferença angular: ${Math.abs(data.views[target].angle-data.views[candidate].angle)}°.`):'Aproxime de 1 para encontrar a correspondência.'}</span>{search&&<p>Comparação calculada das sete projeções: {search.scores.map((s,i)=>`${data.views[i].angle}°: ${s.toFixed(2).replace('.',',')}`).join(' · ')}</p>}</div></>}<p className="xr-method-note">Treino com projeções simuladas da mesma TC. A busca compara sete ângulos por correlação normalizada (NCC); não usa a rede neural XVR nem estima posição 3D de um exame real. Não é medida de precisão clínica.</p></div>
}
