import { useCallback, useContext, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { AppContext } from '../App';
import { api, errorText } from '../api';
import type { DayGrid } from '../models';
import { Button, Dialog, Field, Icon, Notice, Segmented, Surface } from '../ui';
import { calendario, dppPorIdade, hoje, idadeGestacional, proximos, type Compromisso, type Gestacao, type Registro } from './model';
const url = (phone:string) => `/care2/pessoas/${encodeURIComponent(phone)}/gestacao`;
const dateText = (s:string) => new Date(s+'T12:00:00').toLocaleDateString('pt-BR');
export function GestacaoHub() {
  const app = useContext(AppContext)!;
  return <div className="page narrow"><Link to="/">← Início</Link><div className="gestacao-hero"><span className="eyebrow">PROGRAMA VYTAL CARE</span><h1>Gestação</h1><p>Seus cuidados de hoje. Seus próximos passos.</p></div><Surface><h2>Para quem é o programa?</h2><p className="muted">Escolha uma pessoa para organizar a gestação, os compromissos e as dúvidas do pré-natal.</p>{app.loading ? <p>Carregando pessoas…</p> : app.patients.map(p=><Link className="action" key={p.phone} to={`/p/${p.phone}/gestacao`}><Icon name="heart"/><span className="grow">{p.name}</span><Icon name="chev"/></Link>)}<Notice>{app.error}</Notice><Button icon="plus" onClick={app.openNewPatient}>Cadastrar pessoa</Button></Surface><p className="muted small">Incluído na sua experiência do Care. Não cria outra assinatura. Informações disponíveis para quem tem acesso a esta conta.</p></div>;
}
export function GestacaoResumo({phone}:{phone:string}) {
  const [g,setG]=useState<Gestacao|null>(null);
  useEffect(()=>{let alive=true;api<Registro>(url(phone)).then(r=>{if(alive)setG(r.data);}).catch(()=>{});return()=>{alive=false;};},[phone]);
  if(!g||g.status!=='ativa')return null;
  const age=idadeGestacional(g.dpp),next=proximos(g.compromissos)[0];
  return <div className="stack" style={{gap:5}}><span className="chip ok">Gestação{age?` · ${age.semanas} semanas`:''}</span>{next&&<span className="muted small">{next.titulo} · {dateText(next.data)} às {next.hora}</span>}</div>;
}
export function GestacaoEntry({phone}:{phone:string}) {
  return <Link className="surface gestacao-entry" to={`/p/${phone}/gestacao`}><Icon name="heart" size={28}/><div className="grow"><b>Minha gestação</b><p className="muted small">Semana gestacional, agenda e dúvidas para o pré-natal.</p></div><Icon name="chev"/></Link>;
}
export default function GestacaoPage() {
  const {phone=''}=useParams(); const app=useContext(AppContext)!;
  const pessoa=app.patients.find(p=>p.phone===phone);
  const [agenda,setAgenda]=useState<DayGrid|null>(null),[agendaError,setAgendaError]=useState(''),[selected,setSelected]=useState<Compromisso|null>(null);
  const [r,setR]=useState<Registro|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[editing,setEditing]=useState(false),[adding,setAdding]=useState(false),[question,setQuestion]=useState(''),[status,setStatus]=useState(''),[conflict,setConflict]=useState(false);
  const load=useCallback(async()=>{setError(null);try{setR(await api<Registro>(url(phone)));setConflict(false);}catch(e){setError(errorText(e));}},[phone]);
  useEffect(()=>{setR(null);void load();},[load]);
  useEffect(()=>{let active=true;setAgenda(null);setAgendaError('');api<DayGrid>(`/patients/${phone}/hoje`).then(d=>{if(active)setAgenda(d);}).catch(e=>{if(active)setAgendaError(errorText(e));});return()=>{active=false;};},[phone]);
  async function save(data:Gestacao) {if(!r||busy)return false;setBusy(true);setError(null);setStatus('');try{setR(await api<Registro>(url(phone),{method:'PUT',body:{version:r.version,data}}));setStatus('Salvo na sua conta.');return true;}catch(e){setError(errorText(e));if((e as {status?:number}).status===409)setConflict(true);return false;}finally{setBusy(false);}}
  const g=r?.data; const age=g?idadeGestacional(g.dpp):null; const upcoming=proximos(g?.compromissos??[]); const soon=upcoming.filter(c=>Date.parse(c.data+'T12:00:00Z')-Date.parse(hoje()+'T12:00:00Z')<=86400000);
  function download(c:Compromisso){const link=document.createElement('a'),href=URL.createObjectURL(new Blob([calendario(c)],{type:'text/calendar;charset=utf-8'}));link.href=href;link.download='compromisso-care.ics';link.click();setTimeout(()=>URL.revokeObjectURL(href),1000);}
  if(!pessoa)return <div className="page narrow"><Link to="/gestacao">← Gestação</Link><p>{app.loading?'Carregando…':'Pessoa não encontrada nesta conta.'}</p></div>;
  return <div className="page narrow gestacao-page"><Link to={`/p/${phone}`}>← {pessoa.name}</Link>
    <header className="gestacao-hero"><span className="eyebrow">VYTAL CARE GESTAÇÃO</span><h1>{g?g.status==='encerrada'?'Seu registro da gestação':age?`${age.semanas} semanas${age.dias?` e ${age.dias} ${age.dias===1?'dia':'dias'}`:''}`:'Sua gestação':'O cuidado acompanha você.'}</h1><p>{g?`Data provável do parto: ${dateText(g.dpp)}`:'Organize os cuidados combinados no pré-natal, um dia de cada vez.'}</p>{g&&<small>Estimativa a partir da data informada. A equipe do pré-natal confirma a idade gestacional.</small>}</header>
    <Notice>{error}</Notice>{conflict&&<Button className="plain" onClick={load}>Recarregar versão salva</Button>}<Notice tone="ok">{status}</Notice>
    {!r&&!error&&<p>Carregando seu programa…</p>}{!r&&error&&<Button onClick={load}>Tentar novamente</Button>}
    {r&&!g&&<Surface><h2>Vamos começar?</h2><p>Use a data provável do parto ou a idade gestacional que a equipe informou. Você poderá ajustar depois.</p><Button icon="heart" onClick={()=>setEditing(true)}>Ativar programa Gestação</Button><p className="muted small">O programa não altera medicamentos ou envia novas mensagens ao ser ativado.</p></Surface>}
    {g&&<>
      <div className="row between wrap no-print"><Button className="plain" icon="edit" disabled={busy} onClick={()=>setEditing(true)}>Dados da gestação</Button><Button className="plain" icon="upload" onClick={()=>window.print()}>Resumo para a consulta</Button></div>
      {g.status==='encerrada'&&<Notice tone="info">Programa encerrado. Histórico preservado. Os lembretes dos medicamentos continuam independentes; confira-os na ficha.</Notice>}
      {g.status==='ativa'&&soon.length>0&&<Notice tone="info">{soon.map(c=>`${c.data===hoje()?'Hoje':'Amanhã'} às ${c.hora}: ${c.titulo}`).join('\n')}</Notice>}
      <Surface><div className="row between"><h2>Cuidados de hoje</h2><Icon name="pill"/></div><p>Seus medicamentos e suplementos prescritos continuam na ficha, com os mesmos horários e confirmações pelo WhatsApp.</p><Notice>{agendaError}</Notice>{agenda&&<div>{agenda.horarios.flatMap(h=>h.itens.filter(i=>i.mine).map((i,n)=><div className="dose" key={h.time+n}><span className="time">{h.time}</span><div className="grow"><b>{i.medicationName}</b><p className="muted small">{i.dose}</p></div><span className="chip">{{tomou:'Confirmado',nao_tomou:'Ainda não tomou',sem_resposta:'Sem confirmação',futuro:'Mais tarde',efeito_colateral:'Relato registrado'}[i.status??'']??'Confira na ficha'}</span></div>))}{!agenda.horarios.some(h=>h.itens.some(i=>i.mine))&&<p className="muted">Nenhum medicamento previsto para hoje.</p>}</div>}<Link className="btn" to={`/p/${phone}`}>Ver ficha e ajustar horários</Link><p className="muted small">O programa não indica doses nem interpreta sintomas. Medições e metas na gestação precisam ser combinadas com a equipe de pré-natal.</p></Surface>
      <Surface><div className="row between wrap"><h2>Agenda do pré-natal</h2>{g.status==='ativa'&&<Button icon="plus" disabled={busy} onClick={()=>{setSelected(null);setAdding(true);}}>Compromisso</Button>}</div><p className="muted small">Horários de Brasília. Avisos de hoje e amanhã aparecem aqui. Para receber notificações fora do Care, adicione o compromisso ao calendário e permita os alertas nele.</p>
        {!g.compromissos.length&&<div className="gestacao-empty"><Icon name="calendar" size={30}/><p>Sua próxima consulta pode ser o primeiro compromisso.</p></div>}
        {[...g.compromissos].sort((a,b)=>(a.data+a.hora).localeCompare(b.data+b.hora)).map(c=><article className="gestacao-event" key={c.id}><div className="row between wrap"><b>{c.titulo}</b><span className={`chip ${c.concluido?'ok':'info'}`}>{c.concluido?'Concluído':c.data<hoje()?'Data passada':'Agendado'}</span></div><p>{dateText(c.data)} · {c.hora}{c.local?` · ${c.local}`:''}</p><div className="row wrap no-print"><button className="link" disabled={busy} onClick={()=>{setSelected(c);setAdding(true);}}>Editar</button>{!c.concluido&&g.status==='ativa'&&<button className="link" onClick={()=>download(c)}>Adicionar ao calendário</button>}<button className="link" disabled={busy} onClick={()=>save({...g,compromissos:g.compromissos.map(x=>x.id===c.id?{...x,concluido:!x.concluido}:x)})}>{c.concluido?'Reabrir':'Marcar concluído'}</button><button className="link danger" disabled={busy} onClick={()=>{if(window.confirm('Excluir este compromisso? Se já exportou, remova também do calendário do celular.'))void save({...g,compromissos:g.compromissos.filter(x=>x.id!==c.id)});}}>Excluir</button></div></article>)}
      </Surface>
      <Surface><h2>Dúvidas para a consulta</h2><p className="muted small">Anote o que quer conversar. Este espaço não envia mensagens à equipe e não é monitorado.</p>{g.duvidas.map(q=><div className="gestacao-question" key={q.id}><label className="row"><input type="checkbox" checked={q.respondida} disabled={busy} onChange={()=>save({...g,duvidas:g.duvidas.map(x=>x.id===q.id?{...x,respondida:!x.respondida}:x)})}/><span>{q.texto}<small className="muted">{q.respondida?'Conversado na consulta':'Para conversar'}</small></span></label><button className="link danger no-print" disabled={busy} onClick={()=>{if(window.confirm('Excluir esta anotação?'))void save({...g,duvidas:g.duvidas.filter(x=>x.id!==q.id)});}}>Excluir</button></div>)}<form className="stack no-print" onSubmit={async e=>{e.preventDefault();if(question.trim()&&await save({...g,duvidas:[...g.duvidas,{id:crypto.randomUUID(),texto:question.trim(),respondida:false}]}))setQuestion('');}}><Field label="O que você quer perguntar?" value={question} maxLength={500} onChange={e=>setQuestion(e.target.value)}/><Button type="submit" disabled={!question.trim()||busy||g.duvidas.length>=100}>Guardar dúvida</Button></form></Surface>
      <Surface><h2>Antes de sair para a consulta</h2><p>Separe sua caderneta da gestante, os exames disponíveis e as receitas em uso. Abra suas dúvidas para conversar com a equipe.</p><a href="https://www.gov.br/pt-br/servicos/solicitar-a-caderneta-da-gestante" target="_blank" rel="noreferrer">Conhecer a Caderneta da Gestante ↗</a></Surface>
      <p className="muted small">O Care apoia a organização e não substitui o pré-natal. Se precisar de atendimento, procure a equipe de saúde; não aguarde resposta pelo aplicativo. Dados disponíveis nesta conta, sem convite automático a outras pessoas.</p>
    </>}
    {editing&&r&&<Setup initial={g??undefined} busy={busy} error={error} onClose={()=>setEditing(false)} onSave={async d=>{if(await save(d))setEditing(false);}}/>}
    {adding&&g&&<Appointment initial={selected??undefined} busy={busy} error={error} onClose={()=>setAdding(false)} onSave={async c=>{if(await save({...g,compromissos:selected?g.compromissos.map(x=>x.id===selected.id?c:x):[...g.compromissos,c]}))setAdding(false);}}/>}
  </div>;
}
function Setup({initial,busy,error,onClose,onSave}:{initial?:Gestacao;busy:boolean;error:string|null;onClose:()=>void;onSave:(g:Gestacao)=>Promise<void>}) {
  const [mode,setMode]=useState('dpp'),[dpp,setDpp]=useState(initial?.dpp??''),[weeks,setWeeks]=useState(''),[days,setDays]=useState('0'),[reference,setReference]=useState(hoje()),[consent,setConsent]=useState(initial?.consentimento??false),[localError,setLocalError]=useState(''),[ended,setEnded]=useState(initial?.status==='encerrada');
  async function submit(){try{const value=mode==='dpp'?dpp:dppPorIdade(Number(weeks),Number(days),reference);if(!value||!consent||(!initial&&!idadeGestacional(value)))throw new Error('Confira a data e a autorização. Use a informação confirmada no pré-natal.');await onSave({status:ended?'encerrada':'ativa',dpp:value,consentimento:consent,compromissos:initial?.compromissos??[],duvidas:initial?.duvidas??[]});}catch(e){setLocalError(errorText(e));}}
  return <Dialog title={initial?'Dados da gestação':'Ativar Minha gestação'} onClose={onClose} locked={busy}><p className="muted">Informe o que foi confirmado pela equipe do pré-natal.</p><Segmented label="Informação disponível" value={mode} onChange={setMode} options={[{value:'dpp',label:'Data do parto'},{value:'idade',label:'Semanas e dias'}]}/>{mode==='dpp'?<Field label="Data provável do parto" type="date" value={dpp} onChange={e=>setDpp(e.target.value)}/>:<><div className="row"><Field label="Semanas" type="number" min={0} max={42} value={weeks} onChange={e=>setWeeks(e.target.value)}/><Field label="Dias" type="number" min={0} max={6} value={days} onChange={e=>setDays(e.target.value)}/></div><Field label="Data em que essa idade foi confirmada" type="date" max={hoje()} value={reference} onChange={e=>setReference(e.target.value)}/></>}
  <label className="row"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Sou a gestante ou tenho autorização dela para registrar estas informações nesta conta.</span></label>{initial&&<label className="row"><input type="checkbox" checked={ended} onChange={e=>setEnded(e.target.checked)}/><span>Encerrar o programa e preservar o histórico</span></label>}<Notice>{localError||error}</Notice><Button busy={busy} disabled={!consent||(mode==='dpp'?!dpp:!weeks||!reference)} onClick={submit}>Salvar programa</Button></Dialog>;
}
function Appointment({initial,busy,error,onClose,onSave}:{initial?:Compromisso;busy:boolean;error:string|null;onClose:()=>void;onSave:(c:Compromisso)=>Promise<void>}){
 const [title,setTitle]=useState(initial?.titulo??''),[date,setDate]=useState(initial?.data??''),[time,setTime]=useState(initial?.hora??''),[place,setPlace]=useState(initial?.local??''),[type,setType]=useState<Compromisso['tipo']>(initial?.tipo??'consulta');
 return <Dialog title={initial?"Editar compromisso":"Novo compromisso"} onClose={onClose} locked={busy}><Segmented label="Tipo de compromisso" value={type} onChange={setType} options={[{value:'consulta',label:'Consulta'},{value:'exame',label:'Exame'},{value:'outro',label:'Outro'}]}/><Field label="Nome do compromisso" value={title} maxLength={100} onChange={e=>setTitle(e.target.value)}/><div className="row"><Field label="Data" type="date" value={date} onChange={e=>setDate(e.target.value)}/><Field label="Horário de Brasília" type="time" value={time} onChange={e=>setTime(e.target.value)}/></div><Field label="Local (opcional)" value={place} maxLength={200} onChange={e=>setPlace(e.target.value)}/><Notice>{error}</Notice><Button busy={busy} disabled={!title.trim()||!date||!time} onClick={()=>onSave({id:initial?.id??crypto.randomUUID(),tipo:type,titulo:title.trim(),data:date,hora:time,local:place.trim(),concluido:initial?.concluido??false})}>Salvar compromisso</Button></Dialog>;
}
