const molecule=(id,name,subtitle,summary,focus,clinical)=>({id,name,subtitle,summary,focus,clinical,group:'moleculas',format:'sdf',source:`https://www.rcsb.org/ligand/${id}`,kind:'Coordenadas idealizadas · componente químico',file:`${id}.sdf`});
const protein=(id,name,subtitle,summary,focus,clinical,enzyme=false)=>({id,name,subtitle,summary,focus,clinical,group:enzyme?'enzimas':'proteinas',format:'pdb',source:`https://www.rcsb.org/structure/${id}`,kind:'Estrutura experimental · cristalografia',file:`${id}.pdb`});
export const catalog=[
 molecule('ATP','ATP','Transferência de energia','Nucleotídeo que acopla reações e participa da transferência de grupos fosfato.','Compare os três fosfatos com os dois do ADP.','A hidrólise do ATP pode ser acoplada ao transporte ativo e à contração muscular.'),
 molecule('ADP','ADP','Metabolismo energético','Adenosina difosfato: participa do ciclo de regeneração do ATP.','Encontre os dois grupos fosfato, com fósforo em laranja.','O ADP também participa da sinalização que ativa plaquetas.'),
 molecule('GLC','Glicose','α-D-glicopiranose','Monossacarídeo utilizado como substrato energético. Esta entrada mostra a forma cíclica alfa.','Observe o anel com um oxigênio e a disposição dos grupos ligados a ele.','Glicólise, armazenamento de glicogênio e controle glicêmico dependem do metabolismo da glicose.'),
 molecule('NAD','NAD⁺','Coenzima de oxirredução','A forma oxidada do NAD participa de reações que transferem elétrons.','Localize os dois nucleotídeos unidos pelos grupos fosfato.','O par NAD⁺/NADH conecta diversas etapas do metabolismo energético.'),
 molecule('NAP','NADP⁺','Coenzima de oxirredução','NADP na forma oxidada. O par NADP⁺/NADPH participa do metabolismo redutor.','Compare com NAD⁺ e identifique o fosfato adicional.','NADPH participa da síntese de lipídios e da defesa antioxidante; a estrutura mostrada é NADP⁺.'),
 molecule('HEM','Heme','Porfirina com ferro','Grupo prostético que contém ferro no centro de um anel porfirínico.','Selecione o ferro central e observe os nitrogênios ao redor.','Está presente em proteínas como hemoglobina e mioglobina. Sua função depende da proteína à qual se liga.'),
 molecule('CLR','Colesterol','Lipídio de membrana','Esterol integrante das membranas e precursor de moléculas sinalizadoras.','Identifique os quatro anéis fundidos e a pequena região com oxigênio.','É precursor de hormônios esteroides, ácidos biliares e vitamina D.'),
 molecule('GSH','Glutationa','Defesa antioxidante','Tripeptídeo formado por glutamato, cisteína e glicina.','Encontre o enxofre da cisteína, destacado em amarelo.','O par glutationa reduzida/oxidada participa da proteção celular contra espécies oxidantes.'),
 protein('1HHO','Hemoglobina','Humana · oxigenada','Proteína de transporte de oxigênio. O depósito 1HHO contém cadeias alfa e beta com grupos heme.','Alterne fitas e átomos. Observe o heme alojado em cada cadeia.','As interações entre subunidades são relevantes para a cooperatividade da hemoglobina. O arquivo mostra a unidade depositada, não necessariamente todo o tetrâmero.'),
 protein('1MSO','Insulina','Humana · forma cristalina T6','Hormônio peptídico com cadeias A e B, estabilizadas por pontes dissulfeto.','Compare as cadeias e procure os átomos de enxofre na vista atômica.','Participa da regulação do metabolismo de glicose, lipídios e proteínas. A organização cristalina não representa a forma circulante isoladamente.'),
 protein('1AO6','Albumina','Humana · proteína plasmática','Proteína plasmática que transporta diversas moléculas e contribui para a pressão oncótica.','Observe a organização em domínios, rica em hélices.','Sua interação com fármacos é relevante para compreender a fração livre no plasma.'),
 protein('1MBN','Mioglobina','Cachalote · estrutura de referência','Proteína muscular que se liga ao oxigênio por um grupo heme. Este modelo é de cachalote, não humano.','Observe a cadeia única organizada em torno do heme.','Permite estudar o armazenamento de oxigênio no músculo e comparar estrutura com hemoglobina.'),
 protein('1CA2','Anidrase carbônica II','Humana · enzima com zinco','Catalisa a interconversão entre dióxido de carbono e bicarbonato.','Selecione o zinco no modelo atômico e observe sua localização.','Participa do equilíbrio ácido-base. É um alvo de inibidores como a acetazolamida.',true),
 protein('1LYZ','Lisozima','Galinha · clara de ovo','Enzima que rompe ligações do peptidoglicano de paredes bacterianas. Modelo clássico de lisozima de galinha.','Observe a fenda entre os domínios; não há substrato bacteriano completo nesta cena.','Ajuda a compreender a defesa antimicrobiana e a relação entre estrutura e catálise.',true),
];
export const groups={todos:'Todos',moleculas:'Moléculas',proteinas:'Proteínas',enzimas:'Enzimas'};
export function filterCatalog(query='',group='todos') {const norm=s=>s.normalize('NFD').replace(/\p{Diacritic}/gu,'').toLowerCase();return catalog.filter(c=>(group==='todos'||c.group===group)&&norm(`${c.name} ${c.id} ${c.subtitle}`).includes(norm(query)));}
