const molecule=(id,name,subtitle,summary,focus,clinical)=>({id,name,subtitle,summary,focus,clinical,group:'moleculas',format:'sdf',source:`https://www.rcsb.org/ligand/${id}`,kind:'Coordenadas idealizadas · componente químico',file:`${id}.sdf`});
const protein=(id,name,subtitle,summary,focus,clinical,enzyme=false)=>({id,name,subtitle,summary,focus,clinical,group:enzyme?'enzimas':'proteinas',format:'pdb',source:`https://www.rcsb.org/structure/${id}`,kind:'Estrutura experimental · cristalografia',file:`${id}.pdb`});
export const catalog=[
 molecule('ATP','ATP','Transferência de energia','Nucleotídeo que acopla reações e participa da transferência de grupos fosfato.','Compare os três fosfatos com os dois do ADP.','A hidrólise do ATP pode ser acoplada ao transporte ativo e à contração muscular.'),
 molecule('ADP','ADP','Metabolismo energético','Adenosina difosfato: participa do ciclo de regeneração do ATP.','Encontre os dois grupos fosfato, com fósforo em laranja.','O ADP também participa da sinalização que ativa plaquetas.'),
 molecule('GLC','Glicose','α-D-glicopiranose','Monossacarídeo utilizado como substrato energético. Esta entrada mostra a forma cíclica alfa.','Observe o anel com um oxigênio e a disposição dos grupos ligados a ele.','Glicólise, armazenamento de glicogênio e controle glicêmico dependem do metabolismo da glicose.'),
 molecule('NAD','NAD⁺','Coenzima de oxirredução','A forma oxidada do NAD participa de reações que transferem elétrons.','Localize os dois nucleotídeos unidos pelos grupos fosfato.','O par NAD⁺/NADH conecta diversas etapas do metabolismo energético.'),
 molecule('NAP','NADP⁺','Coenzima de oxirredução','NADP na forma oxidada. O par NADP⁺/NADPH participa do metabolismo redutor.','Compare com NAD⁺ e identifique o fosfato adicional.','NADPH participa da síntese de lipídios e da defesa antioxidante; a estrutura mostrada é NADP⁺.'),
 molecule('HEM','Heme','Porfirina com ferro','Grupo prostético que contém ferro no centro de um anel porfirínico.','Selecione o ferro central e observe os nitrogênios ao redor.','Está presente em proteínas como hemoglobina e mioglobina. Sua função depende da proteína à qual se liga.'),
 molecule('CLR','Colesterol','Lipídio de membrana','Esterol integrante das membranas e precursor de moléculas sinalizadoras.','Identifique os quatro anéis fundidos e a pequena região com oxigênio.','É precursor de hormônios esteroides, ácidos biliares e vitamina D.'),
 molecule('GSH','Glutationa','Defesa antioxidante','Tripeptídeo formado por glutamato, cisteína e glicina.','Encontre o enxofre da cisteína, destacado em amarelo.','O par glutationa reduzida/oxidada participa da proteção celular contra espécies oxidantes.'),
 molecule("AMP","AMP","Sinal energético","Adenosina monofosfato, nucleotídeo com um grupo fosfato.","Compare AMP, ADP e ATP.","A relação entre nucleotídeos ajuda a compreender o estado energético celular."),
 molecule("FAD","FAD","Coenzima de oxirredução","Flavina adenina dinucleotídeo, cofator de diversas oxidorredutases.","Observe o sistema de anéis da flavina.","O par FAD/FADH₂ participa de reações do metabolismo energético."),
 molecule("FMN","FMN","Flavina mononucleotídeo","Cofator derivado da riboflavina.","Compare a flavina com o modelo de FAD.","Participa da transferência de elétrons em flavoproteínas."),
 molecule("SAM","S-adenosilmetionina","Doador de grupos metila","Molécula que participa de numerosas reações de metilação.","Localize o enxofre ligado à porção adenosila.","Conecta o metabolismo da metionina a processos de metilação."),
 molecule("URE","Ureia","Excreção de nitrogênio","Produto nitrogenado sintetizado principalmente no fígado.","Identifique a carbonila ligada a dois grupos nitrogenados.","Sua concentração depende de produção, hidratação e excreção renal."),
 molecule("LAC","Ácido lático","Forma molecular do lactato","Componente químico depositado como ácido lático; no pH fisiológico predomina o lactato.","Compare o grupo hidroxila com a carbonila do piruvato.","Lactato pode aumentar por diferentes mecanismos; elevação não significa obrigatoriamente hipóxia."),
 molecule("PYR","Ácido pirúvico","Forma molecular do piruvato","No pH fisiológico predomina o piruvato, importante intermediário metabólico.","Compare sua estrutura com o ácido lático.","Conecta glicólise, formação de acetil-CoA e outras vias."),
 molecule("GLU","Ácido glutâmico","Aminoácido · glutamato","Forma depositada do aminoácido; a ionização varia com o pH.","Observe os dois grupos carboxila.","Glutamato participa do metabolismo do nitrogênio e da neurotransmissão excitatória."),
 molecule("GLY","Glicina","Aminoácido pequeno","Aminoácido cuja cadeia lateral é um hidrogênio.","Observe a ausência de centro quiral no carbono alfa.","É abundante no colágeno e participa de neurotransmissão inibitória."),
 molecule("TRP","Triptofano","Aminoácido aromático","Aminoácido essencial com grupo indol na cadeia lateral.","Localize os dois anéis fundidos.","É precursor de serotonina e de outros metabólitos."),
 molecule("TYR","Tirosina","Aminoácido aromático","Aminoácido com grupo fenólico na cadeia lateral.","Compare o grupo hidroxila com outros aminoácidos aromáticos.","Participa da síntese de catecolaminas e hormônios tireoidianos."),
 molecule("ADN","Adenosina","Nucleosídeo","Adenina ligada à ribose, sem grupo fosfato.","Compare sua estrutura com AMP.","Atua na sinalização celular e tem ação farmacológica no nó atrioventricular."),
 protein('1HHO','Hemoglobina','Humana · oxigenada','Proteína de transporte de oxigênio. O depósito 1HHO contém cadeias alfa e beta com grupos heme.','Alterne fitas e átomos. Observe o heme alojado em cada cadeia.','As interações entre subunidades são relevantes para a cooperatividade da hemoglobina. O arquivo mostra a unidade depositada, não necessariamente todo o tetrâmero.'),
 protein('1MSO','Insulina','Humana · forma cristalina T6','Hormônio peptídico com cadeias A e B, estabilizadas por pontes dissulfeto.','Compare as cadeias e procure os átomos de enxofre na vista atômica.','Participa da regulação do metabolismo de glicose, lipídios e proteínas. A organização cristalina não representa a forma circulante isoladamente.'),
 protein('1AO6','Albumina','Humana · proteína plasmática','Proteína plasmática que transporta diversas moléculas e contribui para a pressão oncótica.','Observe a organização em domínios, rica em hélices.','Sua interação com fármacos é relevante para compreender a fração livre no plasma.'),
 protein('1MBN','Mioglobina','Cachalote · estrutura de referência','Proteína muscular que se liga ao oxigênio por um grupo heme. Este modelo é de cachalote, não humano.','Observe a cadeia única organizada em torno do heme.','Permite estudar o armazenamento de oxigênio no músculo e comparar estrutura com hemoglobina.'),
 protein('1CA2','Anidrase carbônica II','Humana · enzima com zinco','Catalisa a interconversão entre dióxido de carbono e bicarbonato.','Selecione o zinco no modelo atômico e observe sua localização.','Participa do equilíbrio ácido-base. É um alvo de inibidores como a acetazolamida.',true),
 protein('1LYZ','Lisozima','Galinha · clara de ovo','Enzima que rompe ligações do peptidoglicano de paredes bacterianas. Modelo clássico de lisozima de galinha.','Observe a fenda entre os domínios; não há substrato bacteriano completo nesta cena.','Ajuda a compreender a defesa antimicrobiana e a relação entre estrutura e catálise.',true),
];
export const groups={todos:'Todos',moleculas:'Moléculas',proteinas:'Proteínas',enzimas:'Enzimas'};
export function filterCatalog(query='',group='todos') {const norm=s=>s.normalize('NFD').replace(/\p{Diacritic}/gu,'').toLowerCase();return catalog.filter(c=>(group==='todos'||c.group===group)&&norm(`${c.name} ${c.id} ${c.subtitle}`).includes(norm(query)));}
