// Educational overview, not a species-only prescription. No dose recommendations.
export const reviewed='23/09/2026';
const amr='https://www.idsociety.org/practice-guideline/amr-guidance/';
const cdc=(path)=>`https://www.cdc.gov/${path}`;
const item=(context,drugs,note)=>({context,drugs,note});
const record=(items,sources,targets=[])=>({items,sources,targets});
export const therapies={
'e-coli':record([item('Cistite não complicada, quando sensível','Nitrofurantoína ou sulfametoxazol + trimetoprima','Nitrofurantoína não é opção para pielonefrite. Em infecção invasiva ou ESBL, o esquema muda conforme gravidade e antibiograma.'),item('Diarreia por E. coli produtora de toxina Shiga','Evitar antibióticos','Não extrapolar o tratamento urinário para STEC; há risco de síndrome hemolítico-urêmica.')],[amr,cdc('ecoli/treatment/index.html')],['beta','quinolona','amino','folato']),
staphylococcus:record([item('Infecção invasiva por S. aureus sensível à meticilina (MSSA)','Oxacilina ou cefazolina','Escolha depende do foco. Drenagem e controle do foco podem ser essenciais.'),item('MRSA, conforme o foco','Vancomicina; linezolida em situações selecionadas','As opções não são intercambiáveis entre bacteremia e pneumonia. Rever sensibilidade e função renal.')],['https://www.idsociety.org/practice-guideline/mrsa/'],['beta','glico','oxaz']),
streptococcus:record([item('Faringite confirmada por S. pyogenes','Penicilina ou amoxicilina','Na doença invasiva grave, podem ser necessários tratamento combinado e controle cirúrgico do foco. Macrolídeos têm resistência variável.')],[cdc('group-a-strep/hcp/clinical-guidance/strep-throat.html')],['beta','macro']),
vibrio:record([item('Cólera grave ou situação com indicação de antibiótico','Doxiciclina ou azitromicina, conforme sensibilidade','A reposição rápida de água e eletrólitos é a base do tratamento. Resistência local e características do paciente orientam a escolha.')],[cdc('yellow-book/hcp/travel-associated-infections-diseases/cholera.html')],['tetra','macro']),
pneumococcus:record([item('Infecção pneumocócica sensível, conforme foco','Amoxicilina ou penicilina; ceftriaxona em cenários selecionados','Meningite exige esquema específico, inicialmente mais amplo. A sensibilidade para meningite tem critérios próprios.')],[cdc('pneumococcal/hcp/clinical-guidance/index.html')],['beta']),
pseudomonas:record([item('Infecção por isolado sensível','Cefepima, ceftazidima ou piperacilina/tazobactam','São exemplos de betalactâmicos antipseudomonas; escolher pelo foco e antibiograma.'),item('Resistência de difícil tratamento','Novos betalactâmicos, como ceftolozana/tazobactam, se ativos','Exige avaliação especializada. Não presumir atividade de qualquer carbapenêmico ou fluoroquinolona.')],[amr],['beta','quinolona','amino']),
coronavirus:record([item('COVID-19 com risco de evolução grave e indicação de tratamento precoce','Nirmatrelvir/ritonavir ou remdesivir','Janela de início, função renal/hepática e interações medicamentosas são determinantes. Não são necessários para toda infecção.')],[cdc('covid/hcp/clinical-care/outpatient-treatment.html')]),
influenza:record([item('Influenza com indicação de antiviral','Oseltamivir','Especialmente relevante em hospitalizados, quadros graves e grupos de risco; início precoce é preferível. Há outras opções conforme idade, contexto e disponibilidade.')],[cdc('flu/hcp/antivirals/summary-clinicians.html')]),
hiv:record([item('Tratamento antirretroviral combinado','Tenofovir + lamivudina + dolutegravir','Exemplo de esquema inicial do PCDT brasileiro. Não usar monoterapia; comorbidades, coinfecções e resistência podem mudar a escolha.')],['https://www.gov.br/aids/pt-br/central-de-conteudo/pcdts']),
adenovirus:record([item('Infecção habitual por adenovírus','Cuidados de suporte','Não há antiviral específico de uso rotineiro. Doença grave em imunossuprimidos exige infectologista; não apresentar cidofovir como tratamento universal.')],[cdc('adenovirus/hcp/clinical-overview/index.html')]),
herpes:record([item('Herpes simplex com indicação de antiviral','Aciclovir, valaciclovir ou fanciclovir','Esquema depende de primeiro episódio, recorrência ou supressão. Encefalite e doença disseminada exigem abordagem hospitalar específica.')],[cdc('std/treatment-guidelines/herpes.htm')]),
'hepatite-b':record([item('Hepatite B crônica com indicação de tratamento','Tenofovir ou entecavir','A indicação depende de atividade viral, inflamação/fibrose e contexto clínico. Nem toda infecção aguda necessita antiviral.')],['https://www.who.int/publications/i/item/9789240090903']),
candida:record([item('Candidemia / candidíase invasiva','Equinocandina, como micafungina','Fluconazol pode ser opção em pacientes e isolados selecionados. A espécie e a sensibilidade importam.'),item('Candidíase de mucosa','Azóis em situações apropriadas','Não aplicar automaticamente o esquema de candidemia à doença localizada.')],['https://www.idsociety.org/practice-guideline/candidiasis/']),
cryptococcus:record([item('Meningite criptocócica','Anfotericina B + flucitosina na indução','Esquema e duração variam com recursos e contexto. Fluconazol participa da consolidação/manutenção; controle da pressão intracraniana é fundamental.')],['https://clinicalinfo.hiv.gov/en/guidelines/hiv-clinical-guidelines-adult-and-adolescent-opportunistic-infections/cryptococcosis']),
aspergillus:record([item('Aspergilose invasiva','Voriconazol; isavuconazol como alternativa em cenários apropriados','Distinguir infecção invasiva, doença alérgica e colonização. Interações e monitorização influenciam a escolha.')],['https://www.idsociety.org/practice-guideline/aspergillosis/']),
rhizopus:record([item('Mucormicose','Anfotericina B lipossomal','Avaliação cirúrgica precoce e correção de fatores predisponentes são essenciais. Isavuconazol ou posaconazol podem compor alternativas/resgate; voriconazol não cobre Mucorales.')],['https://www.ecmm.info/guidelines/']),
histoplasma:record([item('Histoplasmose com indicação de antifúngico','Itraconazol; anfotericina B lipossomal nos quadros graves','A forma clínica e a imunidade determinam a abordagem. Doença leve pode não precisar de antifúngico.')],['https://clinicalinfo.hiv.gov/en/guidelines/hiv-clinical-guidelines-adult-and-adolescent-opportunistic-infections/histoplasmosis']),
paracoccidioides:record([item('Paracoccidioidomicose','Itraconazol; sulfametoxazol + trimetoprima como alternativa','Quadros graves podem exigir anfotericina B. Comprometimento do SNC e interações mudam a escolha.')],['https://www.scielo.br/j/rsbmt/a/Ynd6SxcPqLjtqkFyVp678zj/']),
giardia:record([item('Giardíase sintomática','Tinidazol, metronidazol ou nitazoxanida','Falha aparente requer avaliar reinfecção, adesão e persistência confirmada do parasita.')],[cdc('giardia/hcp/clinical-care/index.html')]),
toxoplasma:record([item('Toxoplasmose com indicação de tratamento','Pirimetamina + sulfadiazina + ácido folínico','Ácido folínico reduz toxicidade hematológica. Gestação, doença ocular e encefalite exigem protocolos próprios; casos leves em imunocompetentes podem não precisar de tratamento.')],[cdc('toxoplasmosis/hcp/clinical-care/index.html')]),
trypanosoma:record([item('Doença de Chagas com indicação de tratamento etiológico','Benznidazol ou nifurtimox','Indicação depende de fase da doença, idade e contexto. Não equivale ao tratamento das complicações cardíacas ou digestivas.')],[cdc('chagas/hcp/clinical-care/index.html')]),
entamoeba:record([item('Amebíase invasiva','Metronidazol ou tinidazol, seguido de agente luminal','O agente luminal, como paromomicina, trata a colonização intestinal residual. A sequência importa; disponibilidade varia por país.')],[cdc('yellow-book/hcp/post-travel-evaluation/post-travel-diarrhea.html')]),
leishmania:record([item('Leishmaniose visceral','Anfotericina B lipossomal em contextos indicados','Tratamento depende da espécie, região, forma clínica, idade e imunidade. Não extrapolar para todas as formas cutâneas; antimoniais e outras opções têm indicações específicas.')],[cdc('leishmaniasis/hcp/clinical-care/index.html')]),
trichomonas:record([item('Tricomoníase','Metronidazol; tinidazol como alternativa','O esquema depende do paciente. Tratar parcerias sexuais e avaliar reinfecção é parte do cuidado; gel vaginal de metronidazol não é substituto adequado.')],[cdc('std/treatment-guidelines/trichomoniasis.htm')]),
};
export const targets={
 beta:{name:'Betalactâmicos',part:'parede',target:'PBPs · síntese da parede',text:'Penicilinas, cefalosporinas e carbapenêmicos ligam-se a PBPs e prejudicam a ligação cruzada do peptidoglicano. O destaque indica a parede, não uma PBP em escala molecular.'},
 glico:{name:'Glicopeptídeos',part:'parede',target:'Precursores do peptidoglicano',text:'Vancomicina liga-se à extremidade D-Ala-D-Ala de precursores da parede. O mecanismo difere do bloqueio das PBPs.'},
 amino:{name:'Aminoglicosídeos',part:'ribossomos',target:'Subunidade 30S',text:'Gentamicina e amicacina interferem na leitura do RNA mensageiro e na síntese proteica. Atividade e uso dependem de sensibilidade, foco e toxicidade.'},
 tetra:{name:'Tetraciclinas',part:'ribossomos',target:'Subunidade 30S',text:'Doxiciclina dificulta a entrada do aminoacil-tRNA no ribossomo, reduzindo a síntese de proteínas.'},
 macro:{name:'Macrolídeos',part:'ribossomos',target:'Subunidade 50S',text:'Azitromicina interfere na elongação da cadeia proteica. O modelo mostra o ribossomo inteiro; as subunidades não estão separadas.'},
 oxaz:{name:'Oxazolidinonas',part:'ribossomos',target:'Subunidade 50S · iniciação',text:'Linezolida dificulta a formação do complexo de iniciação da síntese de proteínas.'},
 quinolona:{name:'Fluoroquinolonas',part:'nucleoide',target:'DNA girase / topoisomerase IV',text:'Ciprofloxacino interfere nas enzimas que controlam o enrolamento e a replicação do DNA. O destaque localiza o DNA, não uma ligação direta do fármaco ao cromossomo.'},
 folato:{name:'Sulfametoxazol + trimetoprima',part:'citoplasma',target:'Via de síntese de folato',text:'Bloqueio sequencial de duas enzimas da via do folato. O citoplasma é destacado apenas como localização da via metabólica.'},
};
export const mechanismSource='https://www.msdmanuals.com/professional/infectious-diseases/bacteria-and-antibacterial-medications/overview-of-antibacterial-medications';
