import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {api,errorText} from '../api';
import {Button,Dialog,Field,Notice,Surface,TextArea} from '../ui';
import {Schedule,timesOf,type Medication} from '../models';
import type {ResumoPessoa} from '../familia/Pessoa';
import {hoje} from '../gestacao/model';
import {diasDesde,limparValores,ordenarRegistros,personalizacao,serieMedicoes,serieRegistros,vazio,type Acompanhamento as Dados,type Campo,type RegistroCuidado,type Valor} from './personalizacao';
const dateText=(s:string)=>new Date(s+'T12:00:00').toLocaleDateString('pt-BR');
const medKey=(m:Medication)=>`id:${m.id} ${m.medicationName} ${m.dose??''}`;
const display=(v:Valor,c:Campo)=>c.type==='date'?dateText(String(v)):c.type==='medication'?String(v).replace(/^id:\d+ /,''):typeof v==='number'?`${v.toLocaleString('pt-BR')}${c.unit?' '+c.unit:''}`:v;
export default function Acompanhamento({phone,id,data,locked,busy,error,onSave}:{phone:string;id:string;data?:Dados;locked:boolean;busy:boolean;error:string;onSave:(d:Dados)=>Promise<boolean>}){
 const spec=personalizacao[id],a=data??vazio();
 const [summary,setSummary]=useState<ResumoPessoa|null>(null),[readError,setReadError]=useState(''),[reload,setReload]=useState(0),[profile,setProfile]=useState(false),[entry,setEntry]=useState<RegistroCuidado|null|undefined>(undefined),[localError,setLocalError]=useState('');
 const [filter,setFilter]=useState(''),[limit,setLimit]=useState(10);
 const needsSummary=Boolean(spec.measurement||spec.workflow==='medications');
 useEffect(()=>{let alive=true;if(!needsSummary)return;setReadError('');api<ResumoPessoa>(`/familia/pessoas/${encodeURIComponent(phone)}/resumo`).then(r=>{if(alive)setSummary(r);}).catch(e=>{if(alive)setReadError(errorText(e));});return()=>{alive=false;};},[phone,needsSummary,reload]);
 const records=ordenarRegistros(a.registros),metric=spec.fields.find(f=>f.id===spec.metric),series=metric?serieRegistros(records,metric.id):[],latest=records[0];
 const elapsed=typeof a.perfil.cirurgia_data==='string'?diasDesde(a.perfil.cirurgia_data,hoje()):null;
 const filtered=records.filter(r=>!filter||JSON.stringify(r.valores).toLocaleLowerCase('pt-BR').includes(filter.toLocaleLowerCase('pt-BR')));
 const meds=summary?.medicacoes??[];
 const filteredFields=spec.profileFields.filter(f=>a.perfil[f.id]!==undefined&&a.perfil[f.id]!=='');
 async function save(next:Dados){setLocalError('');return onSave(next);}
 return <div className={`care-specific theme-${spec.accent}`}>
 <Surface className="specific-heading"><div className="row between wrap"><div><span className="eyebrow">SEU ACOMPANHAMENTO</span><h2>{spec.title}</h2></div><Button disabled={locked||records.length>=365} onClick={()=>setEntry(null)}>{spec.action}</Button></div><p>{spec.subtitle}</p>
 <div className="specific-stats"><div><b>{records.length}</b><span>{id==='dialise'?(records.length===1?'registro de sessão':'registros de sessões'):(records.length===1?'registro pessoal':'registros pessoais')}</span></div><div><b>{latest?dateText(latest.data):'Ainda não'}</b><span>último registro pessoal</span></div>{spec.workflow==='surgery'&&elapsed!==null&&<div><b>{elapsed<0?`Em ${-elapsed} dias`:elapsed===0?'Hoje':`${elapsed} dias`}</b><span>{elapsed<0?'até a cirurgia':'desde a cirurgia'}</span></div>}{metric&&series.length>0&&<div><b>{series[series.length-1].values[0].toLocaleString('pt-BR')} <small>{metric.unit}</small></b><span>último valor registrado</span></div>}</div>
 <div className="specific-profile"><div className="row between wrap"><h3>{spec.workflow==='surgery'?'Minha cirurgia e a alta':spec.workflow==='medications'?'Quem organiza e revisa':'Meu cuidado combinado'}</h3><button className="link no-print" disabled={locked} onClick={()=>setProfile(true)}>{filteredFields.length?'Editar informações':'Preencher informações'}</button></div>{filteredFields.length?<dl>{filteredFields.map(f=><div key={f.id}><dt>{f.label}</dt><dd>{display(a.perfil[f.id],f)}</dd></div>)}</dl>:<p className="muted small">{spec.profileFields.slice(0,3).map(f=>f.label).join(' · ')}. Preencha com as informações do seu atendimento.</p>}</div></Surface>
 {needsSummary&&<Notice>{readError}</Notice>}{readError&&<Button className="plain" onClick={()=>setReload(x=>x+1)}>Atualizar dados da ficha</Button>}
 {spec.measurement&&<Surface><div className="row between wrap"><h3>{spec.measurement==='glicemia'?'Glicemia registrada no Care':'Pressão registrada no Care'}</h3><button className="link no-print" onClick={()=>setReload(x=>x+1)}>Atualizar</button></div><p className="muted small">Medições já recebidas na ficha nos últimos 30 dias. O diário pessoal abaixo registra o contexto e não cria outra medição.</p>{summary?<><Trend points={serieMedicoes(summary.medicoes,spec.measurement)} labels={spec.measurement==='pressao'?['Máxima','Mínima']:['Glicemia']} unit={spec.measurement==='glicemia'?'mg/dL':'mmHg'}/>{summary.faixaCombinada&&<p className="specific-target">Faixa cadastrada como combinada com a equipe: {spec.measurement==='glicemia'?`${summary.faixa.glicemiaBaixa} a ${summary.faixa.glicemiaAlta} mg/dL`:`${summary.faixa.pressaoSistolica}/${summary.faixa.pressaoDiastolica} mmHg (limites de acompanhamento)`}.</p>}</>:!readError&&<p>Carregando medições…</p>}<Link className="no-print" to={`/p/${phone}`}>Ver medições e pedidos na ficha →</Link></Surface>}
 {spec.workflow==='medications'&&<Surface><h3>Conferência dos remédios da ficha</h3><p className="muted small">Marque o que conferiu e o que precisa conversar com a equipe. A conferência não muda a receita nem verifica interações entre medicamentos.</p>{!summary&&!readError&&<p>Carregando a lista…</p>}{summary&&!meds.length&&<p>Nenhum medicamento ativo na ficha. Cadastre ou confira a receita para começar.</p>}{meds.map(m=>{const review=records.find(r=>r.valores.medicamento===medKey(m));return <article className="specific-med" key={m.id}><div><b>{m.medicationName}</b><p>{m.dose} · {timesOf(m).join(' · ')}</p>{m.instructions&&<p className="muted small">{m.instructions}</p>}<span className="chip">{review?`Conferido em ${dateText(review.data)}`:'Ainda não conferido'}</span>{review&&<p className="small">{review.valores.dificuldade}</p>}</div><Button className="plain no-print" disabled={locked||records.length>=365} onClick={()=>setEntry({id:crypto.randomUUID(),data:hoje(),hora:'',valores:{medicamento:medKey(m)}})}>Conferir</Button></article>;})}<Link to={`/p/${phone}`} className="no-print">Abrir receita e horários →</Link></Surface>}
 {metric&&series.length>0&&<Surface><h3>{metric.id==='peso'?'Como meu peso foi registrado':'Minha percepção da dor ao longo dos registros'}</h3><Trend points={series} labels={[metric.label.split(':')[0]]} unit={metric.unit??''} domain={metric.id==='dor'?[0,10]:undefined}/><p className="muted small">Valores informados por você. O gráfico não interpreta melhora, piora ou risco.</p></Surface>}
 <Surface><div className="row between wrap"><h3>{spec.workflow==='surgery'?'Diário da recuperação':spec.workflow==='medications'?'Histórico das conferências':id==='dialise'?'Histórico das sessões':'Meus registros de acompanhamento'}</h3><span className="chip">{records.length} / 365</span></div><p className="muted small">Registros pessoais, sem envio automático à equipe. Horários de Brasília. Para atendimento, use o contato do seu serviço.</p><Notice>{localError}</Notice>{records.length>5&&<Field label="Buscar no histórico" type="search" value={filter} onChange={e=>{setFilter(e.target.value);setLimit(10);}} className="no-print"/>}{!records.length&&<div className="specific-empty"><p>Comece com o que você tem para registrar hoje.</p><p className="muted small">{spec.fields.filter(f=>f.id!=='observacao').map(f=>f.label).join(' · ')}</p></div>}
 {filtered.slice(0,limit).map(r=><article className="specific-record" key={r.id}><div className="row between wrap"><b>{dateText(r.data)} · {r.hora}</b><div className="row no-print"><button className="link" disabled={locked} onClick={()=>setEntry(r)}>Editar</button><button className="link danger" disabled={locked} onClick={()=>{if(window.confirm('Excluir este registro pessoal?'))void save({...a,registros:a.registros.filter(x=>x.id!==r.id)});}}>Excluir</button></div></div><dl>{spec.fields.filter(f=>r.valores[f.id]!==undefined).map(f=><div key={f.id}><dt>{f.label}</dt><dd>{display(r.valores[f.id],f)}</dd></div>)}</dl></article>)}{filtered.length>limit&&<Button className="plain no-print" onClick={()=>setLimit(x=>x+10)}>Ver mais registros ({filtered.length-limit})</Button>}{filter&&!filtered.length&&<p>Nenhum registro encontrado.</p>}<p className="muted small no-print">A impressão inclui os registros atualmente exibidos. Use “Ver mais” para incluir os anteriores.</p></Surface>
 {profile&&<Dialog title={spec.workflow==='surgery'?'Minha cirurgia e a alta':'Meu cuidado combinado'} onClose={()=>setProfile(false)} locked={busy}><ProfileForm fields={spec.profileFields} initial={a.perfil} busy={busy} locked={locked} error={error} onSave={async perfil=>{if(await save({...a,perfil}))setProfile(false);}}/></Dialog>}
 {entry!==undefined&&<Dialog title={spec.action} onClose={()=>setEntry(undefined)} locked={busy}><EntryForm fields={spec.fields} initial={entry??undefined} meds={meds} busy={busy} locked={locked} error={error} medicationRequired={spec.workflow==='medications'} onSave={async r=>{if(await save({...a,registros:a.registros.some(x=>x.id===r.id)?a.registros.map(x=>x.id===r.id?r:x):[...a.registros,r]}))setEntry(undefined);}}/></Dialog>}
 </div>;
}
function FormFields({fields,values,set,meds=[]}:{fields:Campo[];values:Record<string,Valor>;set:(id:string,v:Valor)=>void;meds?:Medication[]}){
 return <>{fields.map(f=>f.type==='select'||f.type==='medication'?<label className="field" key={f.id}><span>{f.label}</span><select value={String(values[f.id]??'')} onChange={e=>set(f.id,e.target.value)}><option value="">Escolha, se souber</option>{f.type==='medication'?<>{!!values[f.id]&&!meds.some(m=>medKey(m)===values[f.id])&&<option value={values[f.id]}>{String(values[f.id]).replace(/^id:\d+ /,'')} (registro anterior)</option>}{meds.map(m=><option key={m.id} value={medKey(m)}>{m.medicationName} · {m.dose}</option>)}</>:(f.options??[]).map(o=><option key={o}>{o}</option>)}</select></label>:f.type==='text'?<TextArea key={f.id} rows={2} label={f.label} maxLength={2000} value={values[f.id]??''} onChange={e=>set(f.id,e.target.value)}/>:<Field key={f.id} label={`${f.label}${f.unit?' ('+f.unit+')':''}`} type={f.type==='number'?'number':'date'} step={f.type==='number'?'any':undefined} min={f.type==='number'?f.min:'1900-01-01'} max={f.type==='number'?f.max:undefined} value={values[f.id]??''} onChange={e=>set(f.id,f.type==='number'&&e.target.value!==''?Number(e.target.value):e.target.value)}/>)}</>;
}
function ProfileForm({fields,initial,busy,locked,error,onSave}:{fields:Campo[];initial:Record<string,Valor>;busy:boolean;locked:boolean;error:string;onSave:(v:Record<string,Valor>)=>Promise<void>}){
 const [values,setValues]=useState(initial);return <form className="stack" onSubmit={async e=>{e.preventDefault();await onSave(limparValores(values));}}><p className="muted small">Preencha apenas o que souber, conforme informado no atendimento. Estes campos não mudam a receita ou os lembretes.</p><FormFields fields={fields} values={values} set={(id,v)=>setValues(x=>({...x,[id]:v}))}/><Notice>{error}</Notice><Button type="submit" busy={busy} disabled={locked}>Salvar informações</Button></form>;
}
function EntryForm({fields,initial,meds,busy,locked,error,medicationRequired,onSave}:{fields:Campo[];initial?:RegistroCuidado;meds:Medication[];busy:boolean;locked:boolean;error:string;medicationRequired:boolean;onSave:(r:RegistroCuidado)=>Promise<void>}){
 const [values,setValues]=useState(initial?.valores??{}),[date,setDate]=useState(initial?.data??hoje()),[time,setTime]=useState(initial?.hora||new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date()));
 return <form className="stack" onSubmit={async e=>{e.preventDefault();await onSave({id:initial?.id??crypto.randomUUID(),data:date,hora:time,valores:limparValores(values)});}}><p className="muted small">Preencha apenas o que souber. Use exatamente as unidades indicadas nos campos.</p><div className="row"><Field label="Data do registro" type="date" min="1900-01-01" max={hoje()} value={date} onChange={e=>setDate(e.target.value)}/><Field label="Horário do registro" type="time" value={time} onChange={e=>setTime(e.target.value)}/></div><FormFields fields={fields} values={values} meds={meds} set={(id,v)=>setValues(x=>({...x,[id]:v}))}/><Notice>{error}</Notice><Button type="submit" busy={busy} disabled={locked||!date||!time||!Object.keys(limparValores(values)).length||(medicationRequired&&!values.medicamento)}>Salvar registro</Button></form>;
}
function Trend({points,labels,unit,domain}:{points:{date:string;values:number[]}[];labels:string[];unit:string;domain?:[number,number]}){
 if(!points.length)return <p className="specific-empty">Nenhum valor disponível para mostrar. Os registros aparecerão aqui quando estiverem na ficha.</p>;
 const all=points.flatMap(p=>p.values),min=domain?.[0]??Math.floor(Math.min(...all)*.9),max=domain?.[1]??(Math.ceil(Math.max(...all)*1.1)||1),range=max-min||1;
 const minTime=Date.parse(points[0].date),maxTime=Date.parse(points[points.length-1].date);const x=(p:typeof points[number])=>points.length===1?180:35+((Date.parse(p.date)-minTime)/(maxTime-minTime||1))*305;const y=(v:number)=>145-((v-min)/range)*115;
 return <div className="specific-trend"><p className="muted small">Até 12 últimos registros · {unit}. Escala de {min} a {max}. Pontos posicionados pela data e horário.</p><svg viewBox="0 0 380 180" role="img" aria-label={`Histórico de ${labels.join(' e ')}. Valores detalhados na tabela abaixo.`}><line x1="35" x2="340" y1="145" y2="145" stroke="#b9c9c4"/><text x="0" y="35">{max}</text><text x="0" y="148">{min}</text>{labels.map((label,i)=><g key={label} fill={i?'#aa5369':'#237665'} stroke={i?'#aa5369':'#237665'}><polyline points={points.map(p=>`${x(p)},${y(p.values[i])}`).join(' ')} fill="none" strokeWidth="2.5"/>{points.map((p,j)=><circle key={j} cx={x(p)} cy={y(p.values[i])} r="4"><title>{Schedule.dateTime(p.date)}: {p.values[i]} {unit}</title></circle>)}</g>)}<text x="35" y="173">{Schedule.dateTime(points[0].date).split(' ')[0]}</text><text x="340" y="173" textAnchor="end">{Schedule.dateTime(points[points.length-1].date).split(' ')[0]}</text></svg><div className="row wrap">{labels.map((l,i)=><span className="small" key={l} style={{color:i?'#aa5369':'#237665'}}>● {l}</span>)}</div><div className="specific-table"><table className="tabela"><thead><tr><th>Quando</th>{labels.map(l=><th key={l}>{l} ({unit})</th>)}</tr></thead><tbody>{[...points].reverse().map((p,j)=><tr key={j}><td>{Schedule.dateTime(p.date)}</td>{p.values.map((v,i)=><td key={i}>{v.toLocaleString('pt-BR')}</td>)}</tr>)}</tbody></table></div></div>;
}
