import {useContext,useEffect,useState} from 'react';
import {Link,useNavigate,useSearchParams} from 'react-router-dom';
import {AppContext} from '../App';
import {api,errorText} from '../api';
import {Button,Field,Notice,Surface} from '../ui';
import {programas} from './model';
export type DailyConfig={conditions:string[];time:string;enabled:boolean;consent:boolean};
type RecordDay={id:number;slot:string;status:string;snapshot:{conditions:string[];question:string}[];answers:string[]|null};
export type DailyState={data:DailyConfig|null;version:number;available:boolean;history:RecordDay[]};
const empty:DailyConfig={conditions:[],time:'20:00',enabled:false,consent:false};
const labels:Record<string,string>={sim:'Sim',nao:'Não',nao_se_aplica:'Não se aplica',nao_sei:'Não sei'};
export default function Checkin({phone}:{phone:string}){
 const app=useContext(AppContext)!,person=app.patients.find(p=>p.phone===phone),navigate=useNavigate(),[params]=useSearchParams();
 const [state,setState]=useState<DailyState|null>(null),[draft,setDraft]=useState<DailyConfig>(empty),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0),[conflict,setConflict]=useState(false),[query,setQuery]=useState(''),[showAll,setShowAll]=useState(false);
 const url=`/care2/pessoas/${encodeURIComponent(phone)}/checkin`;
 useEffect(()=>{let alive=true;setState(null);setError('');api<DailyState>(url).then(r=>{if(alive){setState(r);setDraft(r.data??empty);setConflict(false);}}).catch(e=>{if(alive)setError(errorText(e));});return()=>{alive=false;};},[url,retry]);
 async function save(){if(!state||busy||conflict)return;setBusy(true);setError('');setMessage('');try{const r=await api<DailyState>(url,{method:'PUT',body:{version:state.version,data:draft}});setState({...state,...r});setDraft(r.data!);setMessage(r.available&&r.data?.enabled?'Salvo. Você receberá um check-in por dia.':'Salvo. Os lembretes de remédios continuam.');if(params.get('inicio')==='1')navigate(`/p/${phone}`);}catch(e){setError(errorText(e));if((e as {status?:number}).status===409)setConflict(true);}finally{setBusy(false);}}
 if(!person)return <p>{app.loading?'Carregando…':'Escolha uma pessoa.'}</p>;
 const common=['diabetes','hipertensao','insuficiencia-cardiaca','renal','asma','polifarmacia','idoso','gestacao'];
 const list=programas.filter(p=>(showAll||query.trim()||common.includes(p.id)||draft.conditions.includes(p.id))).filter(p=>`${p.title} ${p.keywords}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')));
 return <div className="stack"><header><span className="eyebrow">CUIDADO DE {person.name.split(' ')[0]}</span><h1>Quais condições essa pessoa tem?</h1><p>Marque as que já conhece. Pode escolher mais de uma.</p></header><Notice>{error}</Notice><Notice tone="ok">{message}</Notice>{(!state||conflict)&&<Button disabled={busy} onClick={()=>setRetry(n=>n+1)}>Atualizar</Button>}{state&&<>
 <Surface><Field label="Buscar condição" placeholder="Ex.: diabetes, pressão alta…" type="search" value={query} onChange={e=>setQuery(e.target.value)}/><div className="grid2">{list.map(p=><label key={p.id} className="row" style={{padding:'12px 0',alignItems:'flex-start'}}><input type="checkbox" disabled={busy||conflict} checked={draft.conditions.includes(p.id)} onChange={e=>{const conditions=e.target.checked?[...draft.conditions,p.id]:draft.conditions.filter(id=>id!==p.id);setDraft({...draft,conditions,enabled:conditions.length>0});}}/><span>{p.title}</span></label>)}</div>{!list.length&&<p>Nenhuma condição encontrada.</p>}{!query&&<p><button type="button" className="link" onClick={()=>setShowAll(!showAll)}>{showAll?'Mostrar menos':'Ver outras condições'}</button></p>}<button type="button" className="link" disabled={busy||conflict} onClick={()=>setDraft({...draft,conditions:[],enabled:false})}>Nenhuma ou não sei informar</button></Surface>
 <Surface><h2>Uma conversa no fim do dia</h2><p>Um único formulário no WhatsApp, com perguntas sobre os cuidados selecionados.</p>{draft.conditions.length>0&&<><label className="row"><input type="checkbox" checked={draft.enabled} disabled={busy||conflict} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/>Receber o check-in diário</label><Field label="Horário de Brasília" type="time" value={draft.time} disabled={busy||conflict} onChange={e=>setDraft({...draft,time:e.target.value})}/>{draft.enabled&&<label className="row" style={{alignItems:'flex-start'}}><input type="checkbox" checked={draft.consent} disabled={busy||conflict} onChange={e=>setDraft({...draft,consent:e.target.checked})}/><span>A pessoa concorda em receber e registrar suas respostas.</span></label>}</>}{!state.available&&<Notice tone="info">O check-in diário ainda aguarda liberação no WhatsApp.</Notice>}<p className="muted small">Os remédios continuam nos horários da receita.</p><Button className="big" busy={busy} disabled={conflict||(draft.enabled&&!draft.consent)} onClick={save}>{params.get('inicio')==='1'?'Continuar para os remédios':'Salvar'}</Button></Surface>
 <Link className="btn" to={`/p/${phone}`}>Ver remédios</Link>
 <details><summary>Respostas dos últimos dias</summary><Surface>{state.history.length?state.history.map(day=><article key={day.id} className="gestacao-event"><b>{day.slot.split('-').reverse().join('/')}</b>{day.answers?day.snapshot.map((item,i)=><p key={i}>{item.question}<br/><strong>{labels[day.answers![i]]??'Registrado'}</strong></p>):<p>{day.status==='sent'?'Enviado · ainda sem resposta':day.status==='failed'?'Não foi enviado':day.status==='unknown'?'Envio não confirmado':'Envio em andamento'}</p>}</article>):<p>Nenhuma resposta ainda.</p>}<p className="muted small">Sem atendimento em tempo real.</p></Surface></details>
 </>}</div>;
}
