import Whatsapp from './Whatsapp';
import Acompanhamento from "./Acompanhamento";
import {personalizacao} from "./personalizacao";
import { useContext, useEffect, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { AppContext } from '../App';
import { api, errorText } from '../api';
import { Button, Field, Icon, Notice, Surface, TextArea } from '../ui';
import type { DayGrid } from '../models';
import { Appointment } from '../gestacao/Gestacao';
import { calendario, hoje, proximos, type Compromisso } from '../gestacao/model';
import { programas, programaUrl, type Programa, type RegistroPrograma } from './model';
const formatDate=(s:string)=>new Date(s+'T12:00:00').toLocaleDateString('pt-BR');
export default function ProgramaRoute(){const {phone='',programa=''}=useParams();return <ProgramaPage key={phone+'/'+programa} phone={phone} id={programa}/>;}
function ProgramaPage({phone,id}:{phone:string;id:string}){
 const app=useContext(AppContext)!,person=app.patients.find(p=>p.phone===phone),catalog=programas.find(p=>p.id===id&&id!=='gestacao');
 const [r,setR]=useState<RegistroPrograma|null>(null),[error,setError]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[conflict,setConflict]=useState(false),[retry,setRetry]=useState(0);
 const [tab,setTab]=useState('hoje'),[day,setDay]=useState<DayGrid|null>(null),[dayError,setDayError]=useState('');
 const [task,setTask]=useState(''),[note,setNote]=useState(''),[noteDate,setNoteDate]=useState(hoje()),[question,setQuestion]=useState('');
 const [goal,setGoal]=useState(''),[instructions,setInstructions]=useState(''),[appointment,setAppointment]=useState<Compromisso|null|undefined>(undefined);
 const saving=useRef(false);
 useEffect(()=>{let alive=true;if(!catalog)return;api<RegistroPrograma>(programaUrl(phone,id)).then(v=>{if(alive){setR(v);setConflict(false);setError('');setGoal(v.data?.objetivo??'');setInstructions(v.data?.orientacoes??'');}}).catch(e=>{if(alive)setError(errorText(e));});return()=>{alive=false;};},[phone,id,retry]);
 useEffect(()=>{let alive=true;api<DayGrid>(`/patients/${encodeURIComponent(phone)}/hoje`).then(d=>{if(alive)setDay(d);}).catch(e=>{if(alive)setDayError(errorText(e));});return()=>{alive=false;};},[phone]);
 async function save(data:Programa){if(!r||saving.current||conflict)return false;saving.current=true;setBusy(true);setError('');setStatus('');try{const next=await api<RegistroPrograma>(programaUrl(phone,id),{method:'PUT',body:{version:r.version,data}});setR(next);setStatus('Salvo na sua conta.');return true;}catch(e){setError(errorText(e));if((e as {status?:number}).status===409)setConflict(true);return false;}finally{saving.current=false;setBusy(false);}}
 const g=r?.data,locked=busy||conflict||g?.status==='arquivado';
 const pending=proximos(g?.compromissos??[]),soon=pending.filter(c=>Date.parse(c.data+'T12:00:00Z')-Date.parse(hoje()+'T12:00:00Z')<=86400000);
 const doses=(day?.horarios??[]).flatMap(h=>h.itens.filter(i=>i.mine).map((i,n)=>({...i,time:h.time,key:h.time+n})));
 function download(c:Compromisso){const href=URL.createObjectURL(new Blob([calendario(c)],{type:'text/calendar;charset=utf-8'})),a=document.createElement('a');a.href=href;a.download='compromisso-care.ics';a.click();setTimeout(()=>URL.revokeObjectURL(href),1000);}
 if(!catalog||!person)return <div className="page narrow"><Link to="/programas">← Programas</Link><p>{app.loading?'Carregando…':!catalog?'Programa não encontrado.':'Pessoa não encontrada nesta conta.'}</p><Notice>{app.error}</Notice></div>;
 return <div className="page narrow programa-page gestacao-page"><Link to={`/programas/${phone}`}>← Programas de {person.name}</Link>
 <header className="programas-hero"><div className="row"><span className="programa-icon"><Icon name={catalog.icon} size={28}/></span><span className="eyebrow">PROGRAMA VYTAL CARE</span></div><p>{person.name}</p><h1>{catalog.title}</h1>{!g&&<p>{catalog.description}</p>}{g?.objetivo&&<b>{g.objetivo}</b>}</header>
 <Notice>{error}</Notice>{conflict&&<div className="no-print"><p className="muted small">Copie qualquer texto ainda não salvo antes de recarregar.</p><Button onClick={()=>{if(window.confirm('Recarregar os dados salvos? Copie antes qualquer texto que queira preservar.')){setAppointment(undefined);setRetry(n=>n+1);}}}>Recarregar versão salva</Button></div>}<Notice tone="ok">{status}</Notice>
 {!r&&!error&&<p role="status">Carregando seu programa…</p>}{!r&&error&&<Button onClick={()=>setRetry(n=>n+1)}>Tentar novamente</Button>}
 {r&&!g&&<Surface><h2>Seu programa já vem pronto.</h2><p>O Care ajuda a lembrar dos cuidados pelo WhatsApp. Você só confere os horários.</p><ul className="programa-benefits"><li>Lembretes dos remédios já cadastrados.</li>{(id==='diabetes'||id==='hipertensao')&&<li>Lembretes para medir {id==='diabetes'?'a glicemia':'a pressão'}, nos horários que sua equipe orientou.</li>}<li>Acompanhamento da rotina, sem montar perguntas.</li><li>Respostas guardadas para você consultar.</li></ul><p className="muted small">Ao ativar, confirmo que sou esta pessoa ou tenho autorização dela para receber o programa pelo WhatsApp e guardar as respostas nesta conta.</p><Button busy={busy} disabled={conflict} onClick={async()=>{if(saving.current)return;saving.current=true;setBusy(true);setError('');try{await api(`/care2/pessoas/${encodeURIComponent(phone)}/whatsapp/${id}/ativar`,{method:'POST',body:{consent:true}});setRetry(n=>n+1);}catch(e){setError(errorText(e));}finally{saving.current=false;setBusy(false);}}}>Quero o programa de {catalog.title}</Button><p className="muted small">Não cria outra assinatura nem muda seus remédios. As novas mensagens de acompanhamento aguardam liberação; os lembretes existentes continuam.</p></Surface>}
 {g&&<>
 {g.status==='arquivado'&&<Notice tone="info">Programa arquivado. O histórico está preservado. Os medicamentos e seus lembretes continuam na ficha.</Notice>}
 <div className="programa-tabs no-print" role="tablist" aria-label="Partes do programa">{[['hoje','WhatsApp'],['agenda','Agenda'],['anotacoes','Anotações'],['plano','Meu plano']].map(([v,label])=><button type="button" role="tab" key={v} id={`tab-${v}`} aria-selected={tab===v} aria-controls={`panel-${v}`} onClick={()=>setTab(v)}>{label}</button>)}</div>
 <section id="panel-hoje" role="tabpanel" aria-labelledby="tab-hoje" className={`programa-panel ${tab!=='hoje'?'inactive':''}`}>
 {g.status==='ativo'&&soon.length>0&&<Notice tone="info">{soon.map(c=>`${c.data===hoje()?'Hoje':'Amanhã'}, ${c.hora}: ${c.titulo}`).join('\n')}</Notice>}
 <Whatsapp phone={phone} id={id} active={g.status==='ativo'}/><details className="specific-routine"><summary>Ver detalhes e registrar pelo site (opcional)</summary><Acompanhamento key={id+retry} phone={phone} id={id} data={g.acompanhamento} locked={locked} busy={busy} error={error} onSave={async acompanhamento=>save({...g,acompanhamento})}/></details><details className="specific-routine"><summary>Minha lista de cuidados diários</summary><Surface><div className="row between wrap"><h2>Meus cuidados de hoje</h2><span className="chip">{g.cuidados.filter(c=>c.feitoEm===hoje()).length} de {g.cuidados.length}</span></div><p className="muted small">Cadastre o que foi combinado para sua rotina diária. As marcações valem para hoje e ficam salvas no programa.</p>{!g.cuidados.length&&<p className="muted">Nenhum cuidado diário cadastrado.</p>}{g.cuidados.map(c=><div className="gestacao-question" key={c.id}><label className="row"><input type="checkbox" checked={c.feitoEm===hoje()} disabled={locked} onChange={()=>save({...g,cuidados:g.cuidados.map(x=>x.id===c.id?{...x,feitoEm:x.feitoEm===hoje()?'':hoje()}:x)})}/><span>{c.texto}<small>{c.feitoEm===hoje()?'Feito hoje':c.feitoEm?`Última marcação: ${formatDate(c.feitoEm)}`:'Para fazer'}</small></span></label><button className="link no-print" disabled={locked} onClick={()=>{if(window.confirm('Remover este cuidado da lista?'))void save({...g,cuidados:g.cuidados.filter(x=>x.id!==c.id)});}}>Remover</button></div>)}<form className="stack no-print" onSubmit={async e=>{e.preventDefault();if(task.trim()&&await save({...g,cuidados:[...g.cuidados,{id:crypto.randomUUID(),texto:task.trim(),feitoEm:''}]}))setTask('');}}><Field label="Adicionar um cuidado diário" placeholder="Ex.: separar os documentos para o atendimento" maxLength={200} value={task} onChange={e=>setTask(e.target.value)} disabled={locked}/><Button type="submit" disabled={locked||!task.trim()||g.cuidados.length>=30}>Adicionar cuidado</Button></form></Surface></details>
 <Surface><h2>Medicamentos de hoje</h2><p className="muted small">A mesma lista da ficha de {person.name.split(' ')[0]}, compartilhada entre todos os programas. Ativar um programa não duplica os lembretes.</p><Notice>{dayError}</Notice>{!day&&!dayError&&<p>Carregando medicamentos…</p>}{day&&!doses.length&&<p>Nenhum medicamento previsto para hoje.</p>}{doses.map(i=><div className="dose" key={i.key}><span className="time">{i.time}</span><div className="grow"><b>{i.medicationName}</b><p className="muted small">{i.dose}</p></div><span className="chip">{{tomou:'Confirmado',nao_tomou:'Ainda não tomou',sem_resposta:'Sem confirmação',futuro:'Mais tarde',efeito_colateral:'Relato registrado'}[i.status??'']??'Confira na ficha'}</span></div>)}<Link className="btn no-print" to={`/p/${phone}`}>Abrir ficha: remédios e medições</Link></Surface></section>
 <section id="panel-agenda" role="tabpanel" aria-labelledby="tab-agenda" className={`programa-panel ${tab!=='agenda'?'inactive':''}`}><Surface><div className="row between wrap"><h2>{personalizacao[id].agenda}</h2><Button icon="plus" disabled={locked||g.compromissos.length>=100} onClick={()=>setAppointment(null)}>Compromisso</Button></div><p className="muted small">Consultas, exames, sessões ou retornos. Horários de Brasília. Para receber alertas fora do Care, importe cada compromisso no calendário do celular e permita as notificações.</p>{!g.compromissos.length&&<p className="gestacao-empty">Adicione seu próximo atendimento.</p>}{[...g.compromissos].sort((a,b)=>(a.data+a.hora).localeCompare(b.data+b.hora)).map(c=><article className="gestacao-event" key={c.id}><div className="row between wrap"><b>{c.titulo}</b><span className={`chip ${c.concluido?'ok':''}`}>{c.concluido?'Concluído':c.data<hoje()?'Data passada':'Agendado'}</span></div><p>{formatDate(c.data)} · {c.hora}{c.local?` · ${c.local}`:''}</p><div className="row wrap no-print"><button className="link" disabled={locked} onClick={()=>setAppointment(c)}>Editar</button><button className="link" disabled={locked} onClick={()=>save({...g,compromissos:g.compromissos.map(x=>x.id===c.id?{...x,concluido:!x.concluido}:x)})}>{c.concluido?'Reabrir':'Concluir'}</button>{!c.concluido&&<button className="link" onClick={()=>download(c)}>Adicionar ao calendário</button>}<button className="link danger" disabled={locked} onClick={()=>{if(window.confirm('Excluir o compromisso? Se exportou, remova também do calendário do celular.'))void save({...g,compromissos:g.compromissos.filter(x=>x.id!==c.id)});}}>Excluir</button></div></article>)}</Surface></section>
 <section id="panel-anotacoes" role="tabpanel" aria-labelledby="tab-anotacoes" className={`programa-panel ${tab!=='anotacoes'?'inactive':''}`}><Surface><h2>Anotações do dia a dia</h2><p>{catalog.prompt}</p><p className="muted small">Este espaço é um caderno pessoal. Não envia mensagens à equipe e não é monitorado.</p><form className="stack no-print" onSubmit={async e=>{e.preventDefault();if(note.trim()&&noteDate&&await save({...g,anotacoes:[...g.anotacoes,{id:crypto.randomUUID(),texto:note.trim(),data:noteDate}]}))setNote('');}}><Field label="Data da anotação" type="date" min="2020-01-01" max={hoje()} value={noteDate} disabled={locked} onChange={e=>setNoteDate(e.target.value)}/><TextArea label="O que gostaria de registrar?" maxLength={2000} value={note} disabled={locked} onChange={e=>setNote(e.target.value)}/><Button type="submit" disabled={locked||!note.trim()||!noteDate||g.anotacoes.length>=100}>Salvar anotação</Button></form>{[...g.anotacoes].sort((a,b)=>b.data.localeCompare(a.data)).map(n=><article className="gestacao-event" key={n.id}><b>{formatDate(n.data)}</b><p className="programa-text">{n.texto}</p><button className="link danger no-print" disabled={locked} onClick={()=>{if(window.confirm('Excluir esta anotação?'))void save({...g,anotacoes:g.anotacoes.filter(x=>x.id!==n.id)});}}>Excluir</button></article>)}</Surface>
 <Surface><h2>Dúvidas para a consulta</h2><p className="muted small">Sugestões para conversar com sua equipe:</p><div className="programa-suggestions no-print">{catalog.questions.map(q=><button className="plain" key={q} disabled={locked} onClick={()=>setQuestion(q)}>{q}<Icon name="plus" size={16}/></button>)}</div>{g.duvidas.map(q=><label className="gestacao-question" key={q.id}><input type="checkbox" disabled={locked} checked={q.respondida} onChange={()=>save({...g,duvidas:g.duvidas.map(x=>x.id===q.id?{...x,respondida:!x.respondida}:x)})}/><span className="grow">{q.texto}<small>{q.respondida?'Conversado':'Para conversar'}</small><button className="link danger no-print" disabled={locked} onClick={e=>{e.preventDefault();if(window.confirm('Excluir esta dúvida?'))void save({...g,duvidas:g.duvidas.filter(x=>x.id!==q.id)});}}>Excluir</button></span></label>)}<form className="stack no-print" onSubmit={async e=>{e.preventDefault();if(question.trim()&&await save({...g,duvidas:[...g.duvidas,{id:crypto.randomUUID(),texto:question.trim(),respondida:false}]}))setQuestion('');}}><Field label="Minha dúvida" maxLength={500} value={question} disabled={locked} onChange={e=>setQuestion(e.target.value)}/><Button type="submit" disabled={locked||!question.trim()||g.duvidas.length>=100}>Guardar dúvida</Button></form></Surface></section>
 <section id="panel-plano" role="tabpanel" aria-labelledby="tab-plano" className={`programa-panel ${tab!=='plano'?'inactive':''}`}><Surface><h2>Meu plano de cuidado</h2><p className="muted small">Guarde aqui o que foi combinado no atendimento. Este texto não altera a receita, os horários ou as metas de medição da ficha.</p><div className="print-only"><b>{g.objetivo}</b><p className="programa-text">{g.orientacoes||"Nenhuma orientação registrada."}</p></div><form className="stack no-print" onSubmit={async e=>{e.preventDefault();await save({...g,objetivo:goal.trim(),orientacoes:instructions.trim()});}}><Field label="O que quero organizar?" maxLength={150} value={goal} disabled={locked} onChange={e=>setGoal(e.target.value)}/><TextArea label="Orientações recebidas da equipe" rows={6} maxLength={4000} value={instructions} disabled={locked} onChange={e=>setInstructions(e.target.value)}/><Button className="no-print" type="submit" disabled={locked}>Salvar meu plano</Button></form></Surface><Surface><h2>Levar para a consulta</h2><p>Imprima os dados já salvos deste programa. Para histórico de remédios e medições, abra o resumo da pessoa.</p><div className="row wrap no-print"><Button className="plain" onClick={()=>window.print()}>Imprimir programa</Button><Link to={`/p/${phone}/resumo`}>Resumo de remédios e medições</Link></div></Surface><Surface className="no-print"><h2>{g.status==='arquivado'?'Retomar este programa':'Pausar este espaço'}</h2><p>Arquivar preserva as anotações e retira o programa da lista “Em uso”. Não interrompe medicamentos nem seus lembretes.</p><Button className="plain" disabled={busy||conflict} onClick={()=>{if(g.status==='arquivado'||window.confirm('Arquivar este programa e preservar o histórico?'))void save({...g,status:g.status==='ativo'?'arquivado':'ativo'});}}>{g.status==='arquivado'?'Retomar programa':'Arquivar programa'}</Button></Surface></section>
 <p className="muted small">O Care ajuda a organizar seus cuidados. Mudanças no tratamento devem ser combinadas com sua equipe. Se precisar de atendimento, procure um serviço de saúde; não espere resposta por este caderno.</p>
 </>}
 {g&&appointment!==undefined&&<Appointment initial={appointment??undefined} busy={busy} error={error||null} onClose={()=>setAppointment(undefined)} onSave={async c=>{if(await save({...g,compromissos:appointment?g.compromissos.map(x=>x.id===c.id?c:x):[...g.compromissos,c]}))setAppointment(undefined);}}/>}
 </div>;
}
