import { useContext, useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { AppContext } from '../App';
import { api, errorText } from '../api';
import { Button, Field, Icon, Notice, Surface } from '../ui';
import { buscarProgramas, categorias, programas, programaLink, programaUrl, type ResumoPrograma } from './model';
import type { Registro } from '../gestacao/model';
export default function Programas() {
 const app=useContext(AppContext)!,{phone}=useParams(),navigate=useNavigate();
 const [query,setQuery]=useState(''),[category,setCategory]=useState('Todos'),[items,setItems]=useState<ResumoPrograma[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false),[retry,setRetry]=useState(0);
 const pessoa=app.patients.find(p=>p.phone===phone);
 useEffect(()=>{let alive=true;setItems([]);setError('');if(!phone)return;setLoading(true);
 Promise.all([api<{programas:ResumoPrograma[]}>(programaUrl(phone)),api<Registro>(`/care2/pessoas/${phone}/gestacao`)]).then(([r,g])=>{if(alive)setItems([...r.programas,...(g.data?[{programa:'gestacao',status:g.data.status==='ativa'?'ativo' as const:'arquivado' as const,objetivo:''}]:[])]);}).catch(e=>{if(alive)setError(errorText(e));}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[phone,retry]);
 const active=items.filter(p=>p.status==='ativo');const list=buscarProgramas(query,category);
 return <div className="page programas-page"><header className="programas-hero"><span className="eyebrow">PROGRAMAS VYTAL CARE</span><h1>Escolha seu cuidado.</h1><p>Você pode escolher mais de um programa.</p></header>
 <Surface><label className="field"><span>Quem vamos cuidar?</span><select value={phone??''} onChange={e=>navigate(e.target.value?`/programas/${e.target.value}`:'/programas')}><option value="">Escolha uma pessoa</option>{app.patients.map(p=><option key={p.phone} value={p.phone}>{p.name}</option>)}</select></label>{app.loading&&<p>Carregando pessoas…</p>}<Notice>{app.error}</Notice>{phone&&!app.loading&&!pessoa&&<Notice>Pessoa não encontrada nesta conta.</Notice>}<button className="link" onClick={app.openNewPatient}>+ Cadastrar pessoa</button></Surface>
 <Notice>{error}</Notice>{error&&<Button onClick={()=>setRetry(x=>x+1)}>Tentar novamente</Button>}{loading&&<p role="status">Carregando programas desta pessoa…</p>}
 {pessoa&&!loading&&!error&&<section aria-label="Meus programas"><div className="row between wrap"><h2>Em uso por {pessoa.name.split(' ')[0]}</h2><span className="chip ok">{active.length} {active.length===1?'programa':'programas'}</span></div>{active.length?<div className="programas-active">{active.map(x=>{const p=programas.find(p=>p.id===x.programa);return p?<Link className="programa-active" key={p.id} to={programaLink(phone!,p.id)}><Icon name={p.icon}/><div className="grow"><b>{p.title}</b><p>{x.objetivo||'Abrir meu cuidado'}</p></div><Icon name="chev"/></Link>:null;})}</div>:<p className="muted">Nenhum programa ativado. Escolha abaixo para começar.</p>}</section>}
 <div className="programas-search"><h2>Encontrar um programa</h2><Field label="Buscar por condição ou cuidado" placeholder="Ex.: diabetes, pressão, cirurgia…" type="search" value={query} onChange={e=>setQuery(e.target.value)}/><label className="field"><span>Categoria</span><select value={category} onChange={e=>setCategory(e.target.value)}><option>Todos</option>{categorias.map(c=><option key={c}>{c}</option>)}</select></label></div>
 <p className="muted small" role="status">{list.length} {list.length===1?'programa encontrado':'programas encontrados'}{!pessoa?' · Escolha uma pessoa acima para abrir.':''}</p>
 <div className="programas-grid">{list.map(p=>{const status=items.find(i=>i.programa===p.id)?.status;return <article className="surface programa-card" key={p.id}><div className="row between"><span className="programa-icon"><Icon name={p.icon} size={24}/></span>{status&&<span className={`chip ${status==='ativo'?'ok':''}`}>{status==='ativo'?'Em uso':'Arquivado'}</span>}</div><span className="eyebrow">{p.category}</span><h3>{p.title}</h3>{pessoa?<Link className="programa-open" to={programaLink(phone!,p.id)} aria-label={`${status?'Abrir':'Conhecer'} ${p.title}`}>{status?'Abrir programa':'Conhecer e ativar'}<Icon name="chev" size={18}/></Link>:<span className="muted small">Selecione uma pessoa para começar</span>}</article>;})}</div>{!list.length&&<Surface><h3>Não encontrou?</h3><p>Tente outro nome ou use o programa Outros cuidados.</p><Button className="plain" onClick={()=>{setQuery('');setCategory('Todos');}}>Ver todos os programas</Button></Surface>}
 <p className="muted small">Seus programas usam a mesma assinatura.</p>
 </div>;
}
export function ProgramasEntry({phone}:{phone:string}){return <Link className="surface gestacao-entry" to={`/programas/${phone}`}><Icon name="list" size={28}/><div className="grow"><b>Programas de cuidado</b><p className="muted small">Diabetes, pressão alta, gestação e outros cuidados. Escolha os seus.</p></div><Icon name="chev"/></Link>;}
