import {useEffect,useRef,useState} from 'react';
import {api,errorText} from '../api';
import {Button,Field,Icon,Notice,Surface} from '../ui';
export type WhatsappConfig={enabled:boolean;consent:boolean;question:string;time:string;days:number[]};
type Entry={id:number;question:string;status:string;response:string|null;createdAt:string;sentAt:string|null;respondedAt:string|null};
export type WhatsappState={data:WhatsappConfig|null;version:number;available:boolean;questions:string[];history:Entry[]};
export const resposta=(e:Entry)=>e.response?({sim:'Sim',nao:'Não',pular:'Pulou hoje'}[e.response]??'Resposta registrada'):e.status==='sent'?'Enviada · sem resposta':e.status==='failed'?'Não foi enviada':e.status==='unknown'?'Envio não confirmado':'Envio em andamento';
const days=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'];
export default function Whatsapp({phone,id,active}:{phone:string;id:string;active:boolean}){
 const [state,setState]=useState<WhatsappState|null>(null),[draft,setDraft]=useState<WhatsappConfig|null>(null),[error,setError]=useState(''),[saved,setSaved]=useState(''),[busy,setBusy]=useState(false),[conflict,setConflict]=useState(false),[retry,setRetry]=useState(0);
 const saving=useRef(false),url=`/care2/pessoas/${encodeURIComponent(phone)}/whatsapp/${id}`;
 useEffect(()=>{let alive=true;api<WhatsappState>(url).then(r=>{if(alive){setState(r);setDraft(r.data??{enabled:false,consent:false,question:r.questions[0],time:'18:00',days:[1,3,5]});setConflict(false);setError('');}}).catch(e=>{if(alive)setError(errorText(e));});return()=>{alive=false;};},[url,retry]);
 async function save(){if(!draft||!state||saving.current||conflict)return;saving.current=true;setBusy(true);setError('');setSaved('');try{const r=await api<WhatsappState>(url,{method:'PUT',body:{version:state.version,data:draft}});setState({...state,...r});setDraft(r.data);setSaved(r.data?.enabled?(r.available?'Salvo. As perguntas seguirão os dias e o horário escolhidos.':'Salvo. As novas perguntas ainda aguardam a liberação do envio pelo WhatsApp.'):'Salvo. As perguntas deste programa estão desligadas.');}catch(e){setError(errorText(e));if((e as {status?:number}).status===409)setConflict(true);}finally{saving.current=false;setBusy(false);}}
 return <div className="care2-whatsapp"><Surface><div className="row between wrap"><div><span className="eyebrow">CUIDADO PELO WHATSAPP</span><h2>Configure aqui. Responda por lá.</h2></div><Icon name="wa" size={32}/></div><p>Escolha uma pergunta para acompanhar a rotina. No WhatsApp, a pessoa responde com um toque. A resposta fica guardada aqui.</p><Notice>{error}</Notice><Notice tone="ok">{saved}</Notice>{(!state||conflict)&&<Button onClick={()=>setRetry(n=>n+1)} disabled={busy}>Atualizar configuração</Button>}
 {state&&draft&&<><div className="row wrap"><span className="chip">{!active?'Programa pausado':!state.data?.enabled?'Perguntas desligadas':!state.available?'Envio ainda não liberado':'Perguntas ligadas'}</span><span className="muted small">Uma pergunta por dia escolhido</span></div>{!state.available&&<Notice tone="info">Você já pode salvar sua preferência. As novas perguntas ainda não serão enviadas. Os lembretes de remédios e de medições que você já usa continuam como antes.</Notice>}
 <form className="stack no-print" onSubmit={e=>{e.preventDefault();void save();}}><label className="stack"><span>O que vamos perguntar?</span><select value={draft.question} disabled={busy||conflict||!active} onChange={e=>setDraft({...draft,question:e.target.value})}>{state.questions.map(q=><option key={q}>{q}</option>)}</select></label><fieldset className="whatsapp-days" disabled={busy||conflict||!active}><legend>Em quais dias?</legend><div className="row wrap">{days.map((label,n)=><label key={label}><input type="checkbox" checked={draft.days.includes(n)} onChange={e=>setDraft({...draft,days:e.target.checked?[...draft.days,n].sort():draft.days.filter(d=>d!==n)})}/>{label}</label>)}</div></fieldset><Field label="A que horas? (horário de Brasília)" type="time" value={draft.time} disabled={busy||conflict||!active} onChange={e=>setDraft({...draft,time:e.target.value})}/>
 <div className="whatsapp-preview"><small>Exemplo da mensagem</small><p>Olá! Vamos registrar um cuidado de hoje?</p><b>{draft.question}</b><div className="row wrap"><span>Sim</span><span>Não</span><span>Pular hoje</span></div><small>A resposta fica no seu histórico. Este canal não tem atendimento em tempo real.</small></div>
 <label className="row"><input type="checkbox" checked={draft.enabled} disabled={busy||conflict||!active} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/><span>Receber esta pergunta pelo WhatsApp</span></label>{draft.enabled&&<label className="row"><input type="checkbox" checked={draft.consent} disabled={busy||conflict||!active} onChange={e=>setDraft({...draft,consent:e.target.checked})}/><span>Esta pessoa concorda em receber as perguntas no número cadastrado e guardar as respostas nesta conta.</span></label>}<Button type="submit" busy={busy} disabled={!active||conflict||!draft.days.length||!draft.time||(draft.enabled&&!draft.consent)}>Salvar configuração</Button><p className="muted small">Você pode desligar as perguntas quando quiser. Isso não muda os lembretes dos remédios. Escolha só os cuidados que fazem sentido para esta pessoa.</p></form></>}
 </Surface><Surface><div className="row between wrap"><h2>Respostas do WhatsApp</h2><Button className="plain no-print" disabled={busy} onClick={()=>{if(!draft||JSON.stringify(draft)===JSON.stringify(state?.data)||window.confirm('Atualizar e descartar os ajustes ainda não salvos?'))setRetry(n=>n+1);}}>Atualizar</Button></div>{state?.history.length?state.history.map(e=><article className="gestacao-event" key={e.id}><small>{new Date(e.createdAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</small><p>{e.question}</p><b>{resposta(e)}</b></article>):<p className="muted">As respostas vão aparecer aqui. Não precisa preencher tudo de novo no site.</p>}<p className="muted small">Aqui aparecem as últimas 30 perguntas. “Sem resposta” não significa que o cuidado deixou de ser feito.</p></Surface></div>;
}
