import {useContext,useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {AppContext} from '../App';
import {api,errorText} from '../api';
import {Button,Field,Icon,Notice,Surface} from '../ui';
import MeasurementEditor from '../pages/MeasurementEditor';
export type WhatsappConfig={mode?:'programa';enabled:boolean;consent:boolean;question:string;time:string;days:number[]};
type Entry={id:number;question:string;status:string;response:string|null;createdAt:string;sentAt:string|null;respondedAt:string|null};
export type WhatsappState={data:WhatsappConfig|null;version:number;available:boolean;questions:string[];history:Entry[]};
export const resposta=(e:Entry)=>e.response?({sim:'Sim',nao:'Não',pular:'Pulou hoje'}[e.response]??'Resposta registrada'):e.status==='sent'?'Enviada · sem resposta':e.status==='failed'?'Não foi enviada':e.status==='unknown'?'Envio não confirmado':'Envio em andamento';
const days=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'];
export default function Whatsapp({phone,id,active}:{phone:string;id:string;active:boolean}){
 const app=useContext(AppContext)!,person=app.patients.find(p=>p.phone===phone),measurement=id==='diabetes'?'glicemia':id==='hipertensao'?'pressao':null;
 const [state,setState]=useState<WhatsappState|null>(null),[draft,setDraft]=useState<WhatsappConfig|null>(null),[error,setError]=useState(''),[saved,setSaved]=useState(''),[busy,setBusy]=useState(false),[conflict,setConflict]=useState(false),[retry,setRetry]=useState(0),[editing,setEditing]=useState(false);
 const [schedules,setSchedules]=useState<{id:number;tipo:string;scheduleTimes:string;startDate?:string;endDate?:string}[]|null>(null),[measurementError,setMeasurementError]=useState('');
 const saving=useRef(false),url=`/care2/pessoas/${encodeURIComponent(phone)}/whatsapp/${id}`;
 useEffect(()=>{let alive=true;api<WhatsappState>(url).then(r=>{if(alive){setState(r);setDraft({...r.data??{enabled:false,consent:false,question:r.questions[0],time:'18:00',days:[1,3,5]},mode:'programa'});setConflict(false);setError('');}}).catch(e=>{if(alive)setError(errorText(e));});return()=>{alive=false;};},[url,retry]);
 useEffect(()=>{let alive=true;if(measurement)api<NonNullable<typeof schedules>>(`/patients/${encodeURIComponent(phone)}/medicoes-agendadas`).then(r=>{if(alive){setSchedules(r.filter(x=>x.tipo===measurement&&(!x.endDate||x.endDate.slice(0,10)>=new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'}))));setMeasurementError('');}}).catch(e=>{if(alive)setMeasurementError(errorText(e));});return()=>{alive=false;};},[phone,measurement,retry]);
 async function save(start=false,pause=false){if(!draft||!state||saving.current||conflict)return;saving.current=true;setBusy(true);setError('');setSaved('');try{const r=await api<WhatsappState>(url+(start?'/ativar':''),{method:start?'POST':'PUT',body:start?{consent:true}:{version:state.version,data:{...draft,mode:'programa',...(pause?{enabled:false}:{})}}});setState({...state,...r});setDraft(r.data);setSaved(pause?'Pausado. Remédios e medições continuam.':r.available?'Pronto. Horários salvos.':'Salvo. Novas mensagens aguardam liberação.');}catch(e){setError(errorText(e));if((e as {status?:number}).status===409)setConflict(true);}finally{saving.current=false;setBusy(false);}}
 return <div className="care2-whatsapp"><Surface><div className="row between wrap"><div><span className="eyebrow">SEU CUIDADO</span><h2>Seus lembretes</h2></div><Icon name="wa" size={32}/></div><Notice>{error}</Notice><Notice tone="ok">{saved}</Notice>{(!state||conflict)&&<Button onClick={()=>setRetry(n=>n+1)} disabled={busy}>Atualizar</Button>}
 <div className="gestacao-event"><b>Remédios</b><p>Lembretes nos horários da receita.</p><Link to={`/p/${phone}`}>Ver remédios</Link></div>
 {measurement&&<div className="gestacao-event"><b>{measurement==='glicemia'?'Glicemia':'Pressão'}</b><p>Responda com o valor no WhatsApp.</p><Notice>{measurementError}</Notice>{schedules===null&&!measurementError&&<p>Conferindo os horários…</p>}{schedules?.map(s=><p key={s.id}><b>{s.scheduleTimes.split(',').join(' · ')}</b>{s.startDate&&<> · a partir de {s.startDate.slice(0,10).split('-').reverse().join('/')}</>}{s.endDate&&<> · até {s.endDate.slice(0,10).split('-').reverse().join('/')}</>}</p>)}{schedules?.length?<><p><Link to={`/p/${phone}`}>Ajustar horários</Link></p></>:schedules&&<><p>Use os horários orientados pela sua equipe.</p><Button disabled={!active||busy} onClick={()=>setEditing(true)}>Adicionar horário</Button></>}</div>}
 {state&&draft&&<><div className="gestacao-event"><b>Acompanhamento</b><span className="chip">{!active?'Programa pausado':!state.data?.enabled?'Ainda não ativado':!state.available?'Envio pendente':'Ativo no WhatsApp'}</span>{!state.available&&<p className="muted small">Estas mensagens ainda não estão ativas. Remédios e medições continuam.</p>}
 {!state.data?.enabled&&<><p className="muted small">Ao ativar, confirmo a autorização desta pessoa para receber e registrar as respostas.</p><Button busy={busy} disabled={!active||conflict} onClick={()=>save(true)}>Ativar</Button></>}
 <details className="specific-routine no-print"><summary>Horários · {draft.days.map(n=>days[n]).join(', ')} às {draft.time}</summary><form className="stack" onSubmit={e=>{e.preventDefault();void save();}}><fieldset className="whatsapp-days" disabled={busy||conflict||!active}><legend>Dias</legend><div className="row wrap">{days.map((label,n)=><label key={label}><input type="checkbox" checked={draft.days.includes(n)} onChange={e=>setDraft({...draft,days:e.target.checked?[...draft.days,n].sort():draft.days.filter(d=>d!==n)})}/>{label}</label>)}</div></fieldset><Field label="Horário de Brasília" type="time" value={draft.time} disabled={busy||conflict||!active} onChange={e=>setDraft({...draft,time:e.target.value})}/><Button type="submit" busy={busy} disabled={!active||conflict||!draft.days.length||!draft.time}>Salvar horários</Button><p className="muted small">Não altera os horários dos remédios ou medições.</p></form></details>{state.data?.enabled&&<button className="link no-print" disabled={busy||conflict||!active} onClick={()=>save(false,true)}>Pausar</button>}</div></>}
 </Surface><details className="specific-routine"><summary>Respostas</summary><Surface><div className="row between wrap"><h2>Respostas</h2><Button className="plain no-print" disabled={busy} onClick={()=>{if(!draft||JSON.stringify(draft)===JSON.stringify({...state?.data,mode:'programa'})||window.confirm('Atualizar e descartar os horários ainda não salvos?'))setRetry(n=>n+1);}}>Atualizar</Button></div>{state?.history.length?state.history.map(e=><article className="gestacao-event" key={e.id}><small>{new Date(e.createdAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</small><p>{e.question}</p><b>{resposta(e)}</b></article>):<p className="muted">Nenhuma resposta ainda.</p>}<p className="muted small">Sem atendimento em tempo real.</p></Surface></details>{editing&&person&&measurement&&<MeasurementEditor patient={person} programType={measurement} onClose={changed=>{setEditing(false);if(changed)setRetry(n=>n+1);}}/>}</div>;
}
